### ISSUE TITLE
Galaxy J5 (2016) SM-J510F (j5xnlte)

### ISSUE THREAD

**Issue by benkhouya** [chenxiaolong/DualBootPatcher#1001]
Please add the **Galaxy J5 (2016) SM-J510F (j5xnlte)** to the supported devices, thanks :-)

**Comment by benkhouya** [comment]
There is an unofficial version of DualBoot Patcher for **Galaxy J5 (2016) SM-J510F (j5xnltejv)** but based on the old version 9.1.x

https://forum.xda-developers.com/galaxy-j5/samsung-galaxy-j5-2016-roms-kernels-recoveries--other-development/patcher-dualbootpatcher-j510-t3614376

**Comment by yshalsager** [comment]
If you have twrp, Flash logs https://dbp.noobdev.io/misc/getlogs/GetLogs-20161128-1.zip
attach tar file and let me add it.
@benkhouya

**Comment by benkhouya** [comment]
**20180312.165831.tar.gz** from **GetLogs** http://rgho.st/8spYP9kJr

**Comment by chenxiaolong** [comment]
#1053 is merged.
