### ISSUE TITLE
Could not update mbtool error on Oneplus 5T 

### ISSUE THREAD

**Issue by Rybens92** [chenxiaolong/DualBootPatcher#1005]
Root with magisk 15.3, Open Beta 3 with android 8.0.
I get this error by getting into Rom tab but it doesn't give any log. When I get to Settings tab it tries to update mbtool too and give some log in boot-ui-action.log file:
https://pastebin.com/VUAQehcf

**Comment by chenxiaolong** [comment]
Can you please try the latest version? This particular crash was fixed by #997.
