### ISSUE TITLE
mbtool/utilities: /tmp/dbu/aroma.zip: Failed to open stream 

### ISSUE THREAD

**Issue by klorinczi** [chenxiaolong/DualBootPatcher#1010]
Can not install  DualBootUtilities-9.3.0.r404.g40d5304a.zip in recovery.
Stops with error.

In recovery.log:
`Generating AROMA config based on installed ROMS
[2018-02-05T19:31:58.977030000+01:00][405:405][error] mbtool/utilities: /tmp/dbu/aroma.zip: Failed to open stream
Updater process ended with ERROR: 1
I:Legacy property environment disabled.
Error installing zip file '/external_sd/!inst/!ROMS/DualBootUtilities-9.3.0.r404.g40d5304a.zip' `

Attaching logs:
[20180205.193226.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/1696379/20180205.193226.tar.gz)

@chenxiaolong: Is it a bug?

**Comment by chenxiaolong** [comment]
Thank you for finding the bugs! There were actually 2.

This will be fixed by #1011.

**Comment by klorinczi** [comment]
Flashing mbtool does not stop with error now, but hangs, while flashing.
https://dbp.noobdev.io/files/9.3.0.r407.g9a902091/Utilities/DualBootUtilities-9.3.0.r407.g9a902091.zip

Attaching logs:
[20180206.075511.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/1698132/20180206.075511.tar.gz)

**Comment by chenxiaolong** [comment]
Thanks for the logs. It looks like it's hanging because AROMA (which is used by DualBootUtilities) doesn't work properly with TWRP 3.0+ on the Note 3: https://forum.xda-developers.com/galaxy-note-3/help/aroma-installer-t3322938

Unfortunately, it looks like the developer of AROMA stopped working on the project in 2015, so I'm not sure that it will be fixed: https://github.com/amarullz/AROMA-Installer/commits/master

**Comment by klorinczi** [comment]
@chenxiaolong:
This is bad news.
But you had Note3 earlier, right?
Didn't you have such freezing problems at flashing DualBootUtilities in recovery?

On XDA they suggest to use TWRP v2.8.7.0 and below.
But as I remember, I tried TWRP v2.8.7.0 which also freezed at flashing DualBootUtilities in recovery.

**Comment by chenxiaolong** [comment]
Perfect, glad you got it working!

Yeah, AROMA doesn't seem to work well on newer devices. I didn't have the Note 3, but I remember it didn't work on my Note 4 and S7 Edge.
