### ISSUE TITLE
Feature request: Cache version and build number during installation

### ISSUE THREAD

**Issue by klorinczi** [chenxiaolong/DualBootPatcher#1013]
DBP v9.3.0.r407 doesn't display version & build of all ROMS.
For some ROMS it displays:
Unknown version
Unknown build

Attaching screenshot
![screenshot_20180206-214301](https://user-images.githubusercontent.com/11757244/35883346-423087c0-0b87-11e8-980c-7ab6a5e83fbb.png)

**Comment by chenxiaolong** [comment]
The values for those come from the `/system/build.prop` for the ROM. Because extsd-slots are stored in an image file instead of a directory, they have to be mounted first, which would slow down the app significantly. I currently don't plan to add support for this.

This issue does not affect any ROM that's installed to the device's internal storage.

**Comment by klorinczi** [comment]
Could be possible to cache those version & build values? 
When a rom is booted, version & build values would be stored in a config file.

Booting into another rom and starting DBP, would read the config file of roms and displaying the last value of version & build. Would be helpful to know these info of the roms. 

Those roms, which were not booted yet, would still show unknown version & build. 

What do you think?

**Comment by chenxiaolong** [comment]
That's not a bad idea. I can probably update the installer to cache those values in `/sdcard/MultiBoot/[ROM ID]/config.json` after a zip is flashed.

**Comment by klorinczi** [comment]
I don't understand, why the version & build is displayed, when I boot into Lineage?
But it is not displayed in Resurrection Remix v5.8.3, which is based on Lineage...

![screenshot_20180208-061545](https://user-images.githubusercontent.com/11757244/35959632-b8edb4c6-0ca6-11e8-99a6-559755586cce.png)

**Comment by chenxiaolong** [comment]
If you boot into an extsd-slot ROM, then you can see the versions because the images have to be mounted anyway. If you're booted into a non-extsd-slot ROM, you won't see them.

**Comment by chenxiaolong** [comment]
@klorinczi This has been implemented in version `9.3.0.r420.gf5cc97c7`. You can either reflash your extsd-slot ROMs OR patch and flash the following "do nothing" zip in your extsd-slots.

https://dbp.noobdev.io/misc/donothing/DoNothing.zip

**Comment by klorinczi** [comment]
I patched DoNothing.zip for lineage141 with DBP v9.3.0.r420.gf5cc97c7, then flashed in-app. 
But no change after reloading the roms. 

Should I reboot to make the changes active?


Thanks, 
Konrad Lorinczi
