### ISSUE TITLE
The reason why DBP can't connect to mbtool when SELinux = enforcing.

### ISSUE THREAD

**Issue by vczilla** [chenxiaolong/DualBootPatcher#1020]
The wrong type gets injected by MBP.
It injects : 
"allow untrusted_app mb_exec: unix_stream_socket { connectto }"

But it should be:
"allow untrusted_app_25 mb_exec: unix_stream_socket { connectto }"

**Comment by chenxiaolong** [comment]
Which ROM and version are you seeing this on? Can you upload the sepolicy file?

**Comment by vczilla** [comment]
Oh yeah my bad, it happens on a OnePlus5 with OxygenOS 5 (beta 4 and beta 5).

**Comment by vczilla** [comment]
[policy.zip](https://github.com/chenxiaolong/DualBootPatcher/files/1723926/policy.zip)
That's /sys/fs/selinux/policy

**Comment by chenxiaolong** [comment]
Thanks for the policy file and the AVC log! This should be fixed by #1032 (version 9.3.0.r458.g2caf8287).
