### ISSUE TITLE
Error while make android app

### ISSUE THREAD

**Issue by XianxianofGit** [chenxiaolong/DualBootPatcher#1041]
I trying to compile the project but unable to solve this issue

/home/xiaoyixian/DualBootPatcher/libmbcommon/include/mbcommon/outcome.h:30:10: FATAL ERROR：outcome.hpp：No Such file or Directory
 #include "outcome.hpp"
          ^~~~~~~~~~~~~
Compile aborted.

**Comment by chenxiaolong** [comment]
Did you get all of the submodules with `git submodule update --init --recursive`?

**Comment by XianxianofGit** [comment]
Oh, Its work, Thank you.
