### ISSUE TITLE
Please add support for Xiaomi Redmi Note 5A (ugglite)

### ISSUE THREAD

**Issue by lunik1981** [chenxiaolong/DualBootPatcher#1067]
Please add support for xiaomi redmi note 5A (ugglite)

**Comment by lunik1981** [comment]
- name: Xiaomi Redmi Note 5A
  id: ugglite
  codenames:
    - ugglite
  architecture: arm64-v8a

  block_devs:
    base_dirs:
      - /dev/block/bootdevice/by-name
    system:
      - /dev/block/bootdevice/by-name/system
      - /dev/block/mmcblk0p24
    cache:
      - /dev/block/bootdevice/by-name/cache
      - /dev/block/mmcblk0p25
    data:
      - /dev/block/bootdevice/by-name/userdata
      - /dev/block/mmcblk0p48
    boot:
      - /dev/block/bootdevice/by-name/boot
      - /dev/block/mmcblk0p21
    recovery:
      - /dev/block/bootdevice/by-name/recovery
      - /dev/block/mmcblk0p22

**Comment by yshalsager** [comment]
@lunik1981 
If you have twrp, Flash logs https://dbp.noobdev.io/misc/getlogs/GetLogs-20161128-1.zip
attach tar file and let me add it.

**Comment by lunik1981** [comment]
Good. Here is the log

[20180321.115603.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/1832523/20180321.115603.tar.gz)
