### ISSUE TITLE
Please add support for Xiaomi Redmi Note 5A (ugglite)

### ISSUE THREAD

**Issue by lunik1981** [chenxiaolong/DualBootPatcher#1069]
Log

[20180321.115603.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/1833091/20180321.115603.tar.gz)

**Comment by yshalsager** [comment]
Here you are @lunik1981 
https://transfer.sh/AIKPJ/Android_GUI-debug-220318-05h01m.apk
https://transfer.sh/XYxdq/DualBootUtilities-9.3.0-220318-05h01m.zip

**Comment by lunik1981** [comment]
Thank you for your work!

**Comment by lunik1981** [comment]
Can you build a utility for Windows?

**Comment by lunik1981** [comment]
**yshalsager**
Vibrate 5 times and reboot into TWRP(((

**Comment by lunik1981** [comment]
T**he problem was fixed**
Go into TWRP and make a Backup of the Data section.
Wipe - Format Data (bottom Right) - Enter Yes and wait until is formatted
Restore your data and partition Data from the menu Restore (Partition Data will not be encrypted)

Put the second firmware, and I can not switch to the first, went to the settings of the main firmware in DualBootPatcher and pressed update ramdisk and now switch the firmware among themselves

**Comment by lunik1981** [comment]
**Bug**. Switching firmware is only displayed after restarting the application

**Comment by lunik1981** [comment]
@yshalsager
Everything checked out.Everything works as it should
But there is one mistake:
Switching firmware is only displayed after restarting the application

**Comment by yshalsager** [comment]
@lunik1981 nice!
I've made a pull request to merge the changes, you can close this issue.
