### ISSUE TITLE
Text is not viewable in some dialog windows, when using dark theme

### ISSUE THREAD

**Issue by webmaster33** [chenxiaolong/DualBootPatcher#112]
bug in r2561:
Text is not viewable in some dialog windows, when using dark theme, for example in Wipe dialog, the background & text is white, thus text is not viewable.

**Comment by chenxiaolong** [comment]
Thanks for the bug report! I'm able to reproduce this and I'll look into it tomorrow.

**Comment by chenxiaolong** [comment]
This is fixed by 492b65f386b71da86119d26f4fc37771b40c3232 and will be in version `8.0.0.r2594.ge30432b`.
