### ISSUE TITLE
Weird graphics on buttons of app and new error when installing/updating BootUI

### ISSUE THREAD

**Issue by Caio99BR** [chenxiaolong/DualBootPatcher#116]
This is one screenshot of graphics bug on app:
http://imgur.com/1QLxsdg

And this link for BootUI issue:
https://gist.github.com/Caio99BR/324202915dbc970da23677886a4ef011
Edit1: Error starts in Line 503

**Comment by chenxiaolong** [comment]
> This is one screenshot of graphics bug on app:
> http://imgur.com/1QLxsdg

I think this might be caused by the new version of the Android gradle plugin. I'll check tomorrow.

> And this link for BootUI issue:
> https://gist.github.com/Caio99BR/324202915dbc970da23677886a4ef011
> Edit1: Error starts in Line 503

This is caused by mixing the debug and test versions. The app thinks the debug version of mbtool ("8.99.16") is newer, but actually, the test version ("8.0.0.r2579") is newer. Try forcing a ramdisk update (tap button 7 times).

**Comment by Caio99BR** [comment]
> This is caused by mixing the debug and test versions. The app thinks the debug version of mbtool ("8.99.16") is newer, but actually, the test version ("8.0.0.r2579") is newer. Try forcing a ramdisk update (tap button 7 times).

Ok, sorry for it

> I think this might be caused by the new version of the Android gradle plugin. I'll check tomorrow.

I will wait for it, i just report things because other peoples can report it after.

**Comment by chenxiaolong** [comment]
> This is one screenshot of graphics bug on app:
> http://imgur.com/1QLxsdg

This is fixed now :) https://github.com/chenxiaolong/DualBootPatcher/commit/4b1c6eb9b733a638c87e9b56587ee043c6959099

**Comment by Caio99BR** [comment]
Thanks for it XD
