### ISSUE TITLE
[suggestion] Chaning device module to using database 

### ISSUE THREAD

**Issue by hankching** [chenxiaolong/DualBootPatcher#118]
I think if use database keeping device information is better then writing code for each device.
For example 
ROMID : P1_P2_P3_P4_P5_P6_P7_P8
               P1 : ro.product.brand
               P2 : ro.product.model
               P3 : ro.product.device
               P4 : ro.product.name
               P5 : ro.build.version.release
               P6 : Directory ID
               P7 : Boot UI ID
               P8 : (optional) for using by user
               For example
               ROMID1=Jiayu_S3_h560_RC5_051_D0001_B0001_00

Directory ID : D0000, D0001, D0002 ...
                        D0000 : auto detect / manual input
                        D0001... : load from database file
                        For example
                        D0001.base=/dev/block/platform/mtk-msdc.0/by-name
                        D0001.system=/dev/block/platform/mtk-msdc.0/by-name/system
                        D0001.cache=/dev/block/platform/mtk-msdc.0/by-name/cache
                        D0001.data=/dev/block/platform/mtk-msdc.0/by-name/userdata
                        D0001.boot=/dev/block/platform/mtk-msdc.0/by-name/boot
                        D0001.recovery=/dev/block/platform/mtk-msdc.0/by-name/recovery
                        D0001.extra=/dev/block/platform/mtk-msdc.0/by-name/lk,/dev/block/platform/mtk-msdc.0/by-name/logo,/dev/block/platform/mtk-msdc.0/by-name/para,/dev/block/platform/mtk-msdc.0/by-name/tee1,/dev/block/platform/mtk-msdc.0/by-name/tee2,/dev/block/platform/mtk-msdc.0/by-name/uboot
                        D0002.base=/dev/block/platform/mtk-msdc.0/11230000.MSDC0/by-name
                        D0002.system=/dev/block/platform/mtk-msdc.0/11230000.MSDC0/by-name/system
                        D0002.cache=/dev/block/platform/mtk-msdc.0/11230000.MSDC0/by-name/cache
                        D0002.data=/dev/block/platform/mtk-msdc.0/11230000.MSDC0/by-name/userdata
                        D0002.boot=/dev/block/platform/mtk-msdc.0/11230000.MSDC0/by-name/boot
                        D0002.recovery=/dev/block/platform/mtk-msdc.0/11230000.MSDC0/by-name/recovery
                        D0002.extra=/dev/block/platform/mtk-msdc.0/11230000.MSDC0/by-name/lk,/dev/block/platform/mtk-msdc.0/11230000.MSDC0/by-name/logo,dev/block/platform/mtk-msdc.0/11230000.MSDC0/by-name/para,/dev/block/platform/mtk-msdc.0/11230000.MSDC0/by-name/tee1,/dev/block/platform/mtk-msdc.0/11230000.MSDC0/by-name/tee2,/dev/block/platform/mtk-msdc.0/11230000.MSDC0/by-name/uboot

If new device comes, only need to add it to database. The app does not need to modify when changing device information.

**Comment by chenxiaolong** [comment]
Thanks for the suggestion! This is not a bad idea in the future. For now, I have to keep the binaries as small as possible because some of the supported devices only have a few hundred KB of space available in the ramdisk. If I keep all this data separate and write some code to parse the files, it might cause `mbtool` to be too big.

**Comment by hankching** [comment]
On mbtool, only keeps the selected romid information, not the whole data, that will minimize mbtool size.
