### ISSUE TITLE
DualBoot patcher won't flash any rom on my oneplus2

### ISSUE THREAD

**Issue by rantoine78** [chenxiaolong/DualBootPatcher#119]
I don't understand why dualboot can't flash any android 6 rom on my oneplus 2. I had try cm13 and broken os, and DBP show me the same error:
"Failed to run real update-binary"
And before this error the log say than "System is image file: false
[V] - Cache is image file: false
[V] - Data is image file: false"

If someone can help me for this issue.
thank you in advance.

And sorry for my bad english i had just 15 and i'm French. :)

**Comment by rantoine78** [comment]
And if someone needs the log file, ask me!

**Comment by hankching** [comment]
check free space and update-script.

**Comment by rantoine78** [comment]
I have 30 go free on my sdcard (the internal sdcard of the phone)  and on the root i have 97 mo free.
What's update-script?

**Comment by rantoine78** [comment]
On the log the only occurence for script is script aborted: oppo.verify_trustzone() failed to read current TZ version: 2

**Comment by hankching** [comment]
Missing mounted block calls TZ, pls send getlogs to verfy

**Comment by rantoine78** [comment]
The log file [clic here](https://drive.google.com/file/d/0BzwOjp0DGhhHYmxGdWpFSXNrck0/view?usp=drivesdk) (it's a google drive file)

**Comment by hankching** [comment]
Change the timezone for the ROM, or the ROM is mismatch your device.

**Comment by chenxiaolong** [comment]
@rantoine78 The issue is caused by the installer wanting to read from the TrustZone partition, which wasn't whitelisted. Please try `8.0.0.r2596.ga5b4886`. It should hopefully fix the issue.

Relevant commit: a5b48865a9b5fc69faf77d46e449ef99b196c418

**Comment by rantoine78** [comment]
@chenxiaolong i gonna try this new update right now, I hope it will work because dual boot is an amazing think for testing new rom!!

**Comment by rantoine78** [comment]
Yes it work Well i have installation correctly cm13 but i've just one more question SuperSU tell me than i've to update the su binary, how can i do it?

**Comment by hankching** [comment]
You should ask who provides the ROM.

close it.

**Comment by rantoine78** [comment]
Thanks for your answer and your time

**Comment by chenxiaolong** [comment]
> Yes it work Well i have installation correctly cm13 but i've just one more question SuperSU tell me than i've to update the su binary, how can i do it?

You should be able to patch and flash SuperSU if you need to.
