### ISSUE TITLE
ramdisk_patcher cannot properly handle symlinked default.prop

### ISSUE THREAD

**Issue by kykdev** [chenxiaolong/DualBootPatcher#1191]
While patching LineageOS 15.1 for S9+ I got this error:
`[E] mbtool/ramdisk_patcher: /multiboot/boot.img.JNUU6Y/ramdisk.out.Bqx8Dv/default.prop: Failed to open for reading: No such file or directory`

And I found out that S9+'s /default.prop is actually a symlink to /system/etc/prop.default:

>star2lteks:/ # ls -l /default.prop
lrwxrwxrwx 1 root root 23 1970-01-01 09:00 /default.prop -> system/etc/prop.default

Looks like there needs to be a workaround to handle these kinds of props.

**Comment by chenxiaolong** [comment]
Thanks for the bug report! This should be fixed in `9.3.0.r694.gd7def580`. DualBootPatcher will use `/dbp.prop` and load it during boot instead of modifying `/default.prop` now.

**Comment by kykdev** [comment]
Wow, didn't expect you would address it this quickly. Thanks a lot! :)
