### ISSUE TITLE
Either of two commits in mbtool/utilities.cpp preventing aroma from launching

### ISSUE THREAD

**Issue by kykdev** [chenxiaolong/DualBootPatcher#1197]
Just noticed that both my unofficial build and official snapshot build of DualBootUtilites cannot launch Aroma installer(tested on S9+ and Nexus5). Looks like reverting either [5f92909](https://github.com/chenxiaolong/DualBootPatcher/commit/5f929095fb7d71a42b9b54bcb5d0e44327993a78) or [241f148](https://github.com/chenxiaolong/DualBootPatcher/commit/241f1486a252ce0170172b1c56cc1878f4ad99aa) fixes the problem.

[recovery.log](https://github.com/chenxiaolong/DualBootPatcher/files/2092815/recovery.log)

**Comment by chenxiaolong** [comment]
Thanks, I'll take a look after work today.
