### ISSUE TITLE
[Request] Please add Galaxy S5 (EXYNOS)

### ISSUE THREAD

**Issue by wajdidhc** [chenxiaolong/DualBootPatcher#12]
Please add the galaxy s5 exynos i know it is different than the qualcomm but i saw that the patcher works with the note 3 exynos can you please add it

**Comment by chenxiaolong** [comment]
Can you flash the GetLogs zip from https://snapshot.noobdev.io/ and send me the log file it creates in /sdcard/logs/? That will provide all the information I need to add support for the device. Thanks!

**Comment by wajdidhc** [comment]
Here is the link http://www.mediafire.com/?3y771ug8cg663yv

**Comment by wajdidhc** [comment]
Please answer
