### ISSUE TITLE
Boot-UI reboots to fastboot (Robin, logs included)

### ISSUE THREAD

**Issue by AnierinBliss** [chenxiaolong/DualBootPatcher#1224]
@chenxiaolong after switching ROM or when booting primary with ramdisk updated and boot ui installed the device goes right into fastboot mode after it countsdown. Also, when it's done counting down it just freezes at that screen unless I force reboot it half the time. Here are logs, I'd appreciate if someone took a look at them please.
[20180624.233933.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/2131760/20180624.233933.tar.gz)

I'd really like to get this working

**Comment by chenxiaolong** [comment]
I'm not sure if this is possible to fix. On some devices, scanning for hardware events (uevents) causes the hardware to get initialized. With the boot UI, uevents are scanned twice: once before the boot UI is displayed and once between Android starts up. Some devices crash or hang during the second initialization, which I assume is what's happening on your device. On my Galaxy S8+, for example, enabling boot UI causes the modem and bluetooth to fail ~20% of the time.

**Comment by chenxiaolong** [comment]
Please try repatching and reflashing the ROM with version `9.3.0.r770.g5561b1d9` or newer. An issue was found that caused the boot image (specifically the device tree entry) to get corrupted. This can lead to hardware sometimes failing to initialize.

More details are available at #1227

**Comment by AnierinBliss** [comment]
@chenxiaolong  Yeah, I'll have to test android 7.1.2 as primary and everything installed through the app as 71.2. or below before I submit a poll request to just disable it entirely .. I've already tried android 8.1 as primary and 7.1.2 as secondary or data slot with the new snapshot apk with no success, so I'm sure you'll see that pull request soon. Thank's a lot for responding as this project has become very very useful for my rom testing needs. porting and testing miui 8 and it seems to do me a lot of justice. Hopefully oreo as secondary is added sometime in the future!
