### ISSUE TITLE
BUG: Backup error if filename contains UTF8 characters

### ISSUE THREAD

**Issue by klorinczi** [chenxiaolong/DualBootPatcher#1265]
It seems, there is a backup bug in DBP v9.3.0.r806.

Backup process stops with UTF8 error. See attached screenshots.
It seems UTF8 characters like éáóőö causes the backup to stop. 

The filename shows correctly in FX file manager. 

![screenshot_20180820-143904](https://user-images.githubusercontent.com/11757244/44341683-26df4f80-a478-11e8-93f4-5dd64cefc0c5.png)

![screenshot_20180820-144445](https://user-images.githubusercontent.com/11757244/44341689-2cd53080-a478-11e8-99dd-03d08901f36c.png)

**Comment by klorinczi** [comment]
@chenxiaolong: Could you check this bug? I can not use backup until this is not fixed. Thanks!

**Comment by klorinczi** [comment]
@chenxiaolong: This is a blocker bug. Can not do successful backups until it is not finished. Should be fixed as soon as possible. Thanks!

**Comment by chenxiaolong** [comment]
This should be fixed by #1348. The PR also adds an automated test that will fail the build if it happens again in the future.

**Comment by klorinczi** [comment]
Thank you very much for the fix!
I really grateful for it!
