### ISSUE TITLE
ndk problem

### ISSUE THREAD

**Issue by nikandlv** [chenxiaolong/DualBootPatcher#134]
hey @chenxiaolong i was able to compile before adding other toolchain support , now everytime i try i get 
```
`CMake Error at external/android-cmake/android.toolchain.cmake:764 (message):
  Specified toolchain "x86_64-clang3.6" is missing in your NDK or broken.
  Please verify that your NDK is working or select another compiler
  toolchain.

  To configure the toolchain set CMake variable ANDROID_TOOLCHAIN_NAME to one
  of the following values:
```

    * aarch64-linux-android-4.9
    * aarch64-linux-android-clang
    * arm-linux-androideabi-4.9
    * arm-linux-androideabi-clang
    * mips64el-linux-android-4.9
    * mips64el-linux-android-clang
    * mipsel-linux-android-4.9
    * mipsel-linux-android-clang
    * x86-4.9
    * x86-clang
    * x86_64-4.9
    * x86_64-clang

```
Call Stack (most recent call first):
  build/android/android-system_x86_64-prefix/src/android-system_x86_64-build/CMakeFiles/3.6.0/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
See also "/home/nikan/DualBootPatcher/build/android/android-system_x86_64-prefix/src/android-system_x86_64-build/CMakeFiles/CMakeOutput.log".
android/CMakeFiles/android-system_x86_64.dir/build.make:105: recipe for target 'android/android-system_x86_64-prefix/src/android-system_x86_64-stamp/android-system_x86_64-configure' failed
make[2]: *** [android/android-system_x86_64-prefix/src/android-system_x86_64-stamp/android-system_x86_64-configure] Error 1
CMakeFiles/Makefile2:1643: recipe for target 'android/CMakeFiles/android-system_x86_64.dir/all' failed
make[1]: *** [android/CMakeFiles/android-system_x86_64.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
`
```
for ndk-r12b
also same for 
ndk-r10d
just with more options !
any idea how to fix it !?
i tried setting a custom variable in the cmake  but no luck
`set(ANDROID_TOOLCHAIN_NAME "x86_64-clang")`

**Comment by chenxiaolong** [comment]
You need version `r11c` for now, unfortunately. There's an issue with `r12*` where static executables cannot be built: https://github.com/android-ndk/ndk/issues/132

This is supposed to be fixed in `r13` when it's released.

**Comment by nikandlv** [comment]
@chenxiaolong ah alright,  thanks for informing :)

**Comment by nikandlv** [comment]
@chenxiaolong ah alright,  thanks for informing :)
