### ISSUE TITLE
Samsung Galaxy Core Prime G360H , cant boot into secondary rom

### ISSUE THREAD

**Issue by DreamStar001** [chenxiaolong/DualBootPatcher#138]
I can flash the patched rom in philz ( i also used twrp ) but if I want to boot it, the phone is stuck at sammy Logo and reboots back to philz.
Here is Logs:
https://drive.google.com/file/d/0B8zcvuiwZu4XMFhMTjFNWndYSG8/view?usp=sharing

**Comment by wazeeahmed** [comment]
Try new builds mentioned on #148 #146 . I had similar issues . It's fixed now .
