### ISSUE TITLE
Apk is crashing when flashing is started in landscape mode

### ISSUE THREAD

**Issue by klorinczi** [chenxiaolong/DualBootPatcher#1392]
Apk is crashing when flashing is started in landscape mode.

I was not able to create exact reproducing steps.

**Comment by klorinczi** [comment]
Attaching crash log. 
[crash.log.txt](https://github.com/chenxiaolong/DualBootPatcher/files/2854507/crash.log.txt)
Is it enough?

**Comment by chenxiaolong** [comment]
I can't seem to reproduce this. I tried launching the app from a landscape homescreen and also rotating a few times while in the app before flashing in landscape mode.

**Comment by klorinczi** [comment]
I am not able to reproduce, either.
Maybe the same crash happened, what happens when putting DBP into background. 

So closing currently.
