### ISSUE TITLE
ExtSD slot ROMs not bootable

### ISSUE THREAD

**Issue by Simon1511** [chenxiaolong/DualBootPatcher#1402]
When trying to install a ROM to ExtSD slot, the flash process end successfully without any errors shown, but in the ROMs folder on SD card there is only a system.img generated. The ROM wont boot up at all, just 5 vibrations at start.
My multiboot.log is attached.

[MultiBoot.log](https://github.com/chenxiaolong/DualBootPatcher/files/2871784/MultiBoot.log)

**Comment by klorinczi** [comment]
Why did you close it?

**Comment by Simon1511** [comment]
@klorinczi Because I fixed it. Im (finally) able to boot from extSD

**Comment by klorinczi** [comment]
Describe how you fixed it.
May be useful for others, too.

**Comment by Simon1511** [comment]
Cant describe it.
Thought I fixed it, but I didnt
