### ISSUE TITLE
(Closed) Extsd option not working

### ISSUE THREAD

**Issue by wazeeahmed** [chenxiaolong/DualBootPatcher#146]
I tried installing rom on sd card . But it didn't work . I did it like you instructed . It always fails on running real update binary . Forgot to mention system.img gets created . But doesn't get extracted . I tried many things . That includes formatting sd card , partitioning etc etc . Nothing helped . My device is sprout4 and the primary rom is cm13-nightly-20160806-sprout4 .

new addition to the google.cpp , new device android one , blockdevs , sd card sysfs path - /dev/block/mmcblk1p1

**Comment by hankching** [comment]
Pls show multiboot.log file.

**Comment by hankching** [comment]
Problem solved.
You need to close this issue.
