### ISSUE TITLE
(Closed) Extsd option not working at all ( I apologize for reposting , last one was incomplete ; but this one complete and easy to diagnose)

### ISSUE THREAD

**Issue by wazeeahmed** [chenxiaolong/DualBootPatcher#147]
I patched a rom zip to install in my sd card and it did create a system.img . But didn't extract it at all . Now here the comes all your question and my answer . I apologize in advance if i missed anything . i followed all the instructions accordingly as you said in xda @chenxiaolong 

Q.1 : Did you removed the battery when the rom didn't boot ?
Ans. : No . I didn't .
Q.2 : Did your phone hanged up in the manufacturer logo or boot animation ?
Ans. : Manufacturer logo .
Q.3 : After hanging up in the manufacturer logo ; did your phone directly booted into recovery ?
Ans. : Yes , it directly did .

All the zips you asked for bug reporting are obtained and attached here .
[20160808.120326.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/407334/20160808.120326.tar.gz)

**Comment by hankching** [comment]
System partition didn't find is error which is /raw/extSD.....

Your system maybe miss something, did you try to install this version to data-slot? If it works when the location is data-slot, you can try to format as FAT for extSD card, currently it is EXT4, and install it into extSD. If it doesn't work which means your system misses to mount extSD before booting complete.

**Comment by wazeeahmed** [comment]
I tried with fat32 too . Same result . Now what is the solution ? Does any sysfs path missing ? Or it's something @chenxiaolong Have to fix ?

**Comment by hankching** [comment]
Your boot system cannot find a device  (ie voldmanaged=sdcard1), so the system cannot boot extSD slot. 
I find another device (ie voldmanaged=sdcard0) which normally is internal SD card. Maybe your system uses it as external SD.

Waiting @chenxiaolong find the issue or fix it.

**Comment by wazeeahmed** [comment]
You just snatched my suspicion from my mind . Exactly that's what i was what i ad in mind but couldn't be quite sure of it . You made it clear . well now it's upto @chenxiaolong . I guess I'll have to wait a few more days .

**Comment by chenxiaolong** [comment]
Thanks for the logs! Based on the kernel log, mbtool is not detecting the SD card in the fstab file because the vold argument `voldmanaged=sdcard0` is not recognized. It previously only recognized the following four strings:

* `voldmanaged=sdcard1`
* `voldmanaged=extSdCard`
* `voldmanaged=external_SD`
* `voldmanaged=MicroSD`

This is now fixed in commit 554d8f920a80d4958511a1dcded13a9da302ffeb (version `8.0.0.r2709.g554d8f9`).

**Comment by wazeeahmed** [comment]
Thank you thank you thank you thank you so so so so much :) I'll help keeping your project alive anyhow . I'll contribute by donating once I get my credit card . I have set in my to do list from now on . I had a dream and now it's getting fullfilled . :)

**Comment by hankching** [comment]
Problem solved.
You need to close this issue.

**Comment by wazeeahmed** [comment]
@chenxiaolong Please close this issue as resolved . Or permission for closing by myself .

**Comment by Caio99BR** [comment]
This will be closed more earlier or more later, you don't need to flood it.
Just wait.

Em qua, 10 de ago de 2016 09:55, DarkHeart Z <notifications@github.com>
escreveu:

**Comment by wazeeahmed** [comment]
Sorry bro . I never closed an issue before . i thought I can do it myself . Didn't know ; it requires permission .
