### ISSUE TITLE
extsd issue (same as before , now with different rom such as resurrection remix and xosp )

### ISSUE THREAD

**Issue by wazeeahmed** [chenxiaolong/DualBootPatcher#148]
I tried dual booting sd card with different rom now . tried inapp flash and recovery . It does create the system.img and takes awhile in 'it may take awhile' ; but doesn't set kernel as it should  in the end and failure to switch roms which are installed in sd card ) . I tried flashing boot.img manually but phone hanged up in boot logo and directly booted into recovery . I didn't remove battery at all . I attached two logs of the two roms I tried to flash on sd card just as you instructed @chenxiaolong .
[20160811.064120.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/414626/20160811.064120.tar.gz)
[20160812.100715.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/414627/20160812.100715.tar.gz)

**Comment by wazeeahmed** [comment]
@hankching Can you help me out here bro ? Been waiting for the last 2 days .

**Comment by wazeeahmed** [comment]
Can anyone help me please ?

**Comment by chenxiaolong** [comment]
Can you post a link to the ROM you're trying to flash? If it is using the (very bad quality) Mediatek `update-binary` file, I might not be able to fix it.

**Comment by wazeeahmed** [comment]
of course . Here you go xosp : [http://downloads.xosp.org/dlfile.php?o=dl&d=sprout4&z_n=XOSP-6.3-FINAL-MM-OFFICIAL-20160717-sprout4.zip](url)
resurrection remix 5.7.3 : [https://www.androidfilehost.com/?w=files&flid=91371](url)

**Comment by wazeeahmed** [comment]
I wanna add something . Can't flash gapps either . I checked your supported gapps list and tried banks gapps too . it said compatibility issue . tried other gapps too . Didn't work . Here's the link of gapps : [https://download.dirtyunicorns.com/files/gapps/Banks/](url)

**Comment by hankching** [comment]
This error maybe uses SELinux policy version for Android M compatible mode.
This error needs time to fix, it's not a easy way to change permission issue.

ONLY flash unmodified boot.img file to boot partition, it can't boot is that expected.

TRY format your sd card, some errors can fix with this method.

DON'T aggressive!!!

**Comment by wazeeahmed** [comment]
but it did boot dirty unicorn 10.4 . it worked without issue then . After upgrading to 10.5 it didn't work anymore . I did format sd card as you suggested before . It didn't help me either . sd card is class 10 . Very fast write speed i checked . 11mb/second on average . Even much higher sometime . Is sd card has issues u mean ? You are facing no issue at all . We both use mtk hardware right ? Then why it's not working out for me ? should I try formatting to exfat like you did ?

**Comment by hankching** [comment]
1 My sd card takes 70MB/s. This is UHS-I.
2 You aren't a developer, so you don't understand something about facing how many issues in here.
3 MTK, right.
4 I haven't any new features about this. I found unknown rom id from log files.

**Comment by wazeeahmed** [comment]
1. You're right in some point . Yes I don't understand the whole thing completely . 
2. Yes , my sd is slower than yours , no big deal .
3. If I encounter any issues , first thing I gotta do is report here according to the instructions .
4. same thing happened with me too . All I'm trying to find out is why ? If I would've got that by now anyhow ; I'm to help dev fix it in all way I can . It's my sole responsibility to help making this app as its my favourite one and as a android lover I'd help tracking issues and provide to help organizing every issues one by one to get it fixed within the time dev thinks is right .

**Comment by hankching** [comment]
1 You have reported the issue and then waiting for solve it.
2 Everyone wants to know why too, but it need time.
3 Now, dev is doing a big change about this app. dev is no time to solve it. After changed, it will get more flexible to support many devices, so be patient!

**Comment by wazeeahmed** [comment]
Exactly thats what I'm waiting for . I will a bit longer if required .

**Comment by chenxiaolong** [comment]
Thanks! You should be able to flash XOSP from recovery. In-app flashing will not work because the `update-binary` file is badly written. The installer will crash if there are more than 32 directories that are mounted and that is usually the case when booted into Android.

I'll try to work around this issue somehow.

**Comment by wazeeahmed** [comment]
Thanks bro . I'll test and let you know .

**Comment by wazeeahmed** [comment]
Ok bro . I tried again and same error pops up like everytime .

**Comment by chenxiaolong** [comment]
@wazeeahmed Please give the test build at #160 a try. it should fix the issues you were encountering with XOSP.

If XOSP still does not flash properly. Please grab the logs again. Thanks!

**Comment by wazeeahmed** [comment]
sure thing bro . You made the wait worthwhile . Done downloading . Giving it a test and will let you know the results .

**Comment by wazeeahmed** [comment]
Bro successful with xosp and it's additional apps ; But tried open gapps and it failed to install . I attached the multiboot log .
[MultiBoot.log.zip](https://github.com/chenxiaolong/DualBootPatcher/files/446381/MultiBoot.log.zip)

**Comment by wazeeahmed** [comment]
@chenxiaolong Bro confirmed . Extsd is working with dirty unicorn too . But gapps packages ( both opengapps and banks ) are unable in get installed .

**Comment by webmaster33** [comment]
I also have problems installing to external sdcard, but not sure if related to this thread. 
Installation of Imperium ROM 15.0, finished with error. 
Also the copy of files were extremely slow (several minutes per file). 
Attaching logs. 

[logs.zip](https://github.com/chenxiaolong/DualBootPatcher/files/447263/logs.zip)

**Comment by wazeeahmed** [comment]
#160 give this a try . And then let him know .

**Comment by webmaster33** [comment]
It doesn't have recovery build, just apk. 
Should I try flashing using the apk? 
Imperium ROM has Aroma installer, not sure if this is supported...

**Comment by wazeeahmed** [comment]
It's a test build with a lot of improvements . Remember to set kernel of your primary rom and use the previous aroma switcher . Better yet keep a backup of primary kernel in recovery or terminal command if you know about using dd command .

**Comment by webmaster33** [comment]
What do you mean by "use the previous aroma switcher"?
I installed the DualBootPatcherAndroid-8.0.0.r2759.g70d0546-snapshot.apk, patched the Imperium rom zip file, now flashing to external sdcard slot. I started about 1 hour ago, and still not finished.
It hangs at the following point:
[MultiBoot] Creating image ...
[MultiBoot] This may take a while
Is it normal, that the install takes one or more hours?

Also when using the Flash ZIP files in apk version, I have no Aroma installer interface, don't know how Dual Boot Patcher is handling this case...

**Comment by wazeeahmed** [comment]
yeah it's normal . It takes awhile to complete the process . Flash using inapp flashing utility . And if you can try upgrading to a class 10 sd card for better result . Or uhs-1 sdxc will be tremendous . Class 5 or 4 sd card will be so slugish and isn't recommended for dual booting . Though it works but you'll have a slower  performance .

**Comment by webmaster33** [comment]
I have Samsung EVO 64gb external sdcard, class 10.
So it should not take so much time. 

Also I tried installing from recovery, done the Aroma installer. It finished successfully.
 
Then after exit from the Aroma installer, I got error in the recovery terminal window, that got 1 as return value, so mbtool understands as error and stopped. 
Attached logs again. 

[20160831.201028.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/447990/20160831.201028.tar.gz)

**Comment by wazeeahmed** [comment]
I think you should let the dev take a look in those logs . Open up an issue and let him say whats the resolve .

**Comment by chenxiaolong** [comment]
@wazeeahmed I am not able to reproduce the Gapps issue with the latest nano OpenGapps (`open_gapps-arm-6.0-nano-20160828.zip`) and the test build of DualBootPatcher from #160. I saw in the logs you were not using the latest versions. Would you mind trying again?

**Comment by chenxiaolong** [comment]
@webmaster33 Please open a new issue for the problems you're experiencing. Thanks!

**Comment by wazeeahmed** [comment]
No problem at all . I am up for it right now .

**Comment by wazeeahmed** [comment]
Bro I tried . Same result . Here's the log . 
[MultiBoot.log.zip](https://github.com/chenxiaolong/DualBootPatcher/files/448664/MultiBoot.log.zip)

**Comment by chenxiaolong** [comment]
Unfortunately, I can't seem to reproduce the error at the moment (though I'm using a data-slot, which does not rely on an ext4 image). I'll give extsd-slot a try tomorrow.

http://i.imgur.com/pTPGBJz.png

**Comment by wazeeahmed** [comment]
No sweat bro . I have waited 20+ days . I can wait a bit longer . Take your time . I'm in no hurry . :)

**Comment by chenxiaolong** [comment]
I think I found the bug :) The OpenGapps installer only mounts the system partition/image if `/system` is listed in `/etc/fstab`, but this file doesn't exist when flashing from the app. This should hopefully be an easy fix.

**Comment by wazeeahmed** [comment]
I think For the same reason banks gapps don't install either . it says 'checking whether the android version is compatible and fails . You sdk version is not 23 gapps can't install .' This means it can't mount the system image either thats why it pops up the error messege . Hopefully this'll be automatically fixed mount issue of opengapps are fixed :)

**Comment by chenxiaolong** [comment]
@wazeeahmed Can you give the test build at #168 a try and let me know if OpenGapps works now? If not, please attach the MultiBoot.log file. Thanks!

**Comment by wazeeahmed** [comment]
Sure . I am testing it right now .

**Comment by wazeeahmed** [comment]
Tested . Working with both opengapps and banks gapps . Looks like you've won this war . :D

**Comment by webmaster33** [comment]
Flashed 
cm-13.0-20160830-NIGHTLY-jfltexx_extsd-slot-cm13.zip
Flashed in recovery:
open_gapps-arm-6.0-pico-20160902_extsd-slot-cm13.zip
Result: after reboot, a lot crashes after unlocking the lock screen.

Flashed in recovery:
BaNkS-Dynamic-GApps-6.x.x-10-20-15_extsd-slot-cm13.zip
Result: install failed with error.

Logs attached.

[logs.zip](https://github.com/chenxiaolong/DualBootPatcher/files/452869/logs.zip)

**Comment by webmaster33** [comment]
[20160902.224715.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/452887/20160902.224715.tar.gz)

**Comment by chenxiaolong** [comment]
@webmaster33 Are you sure your external SD card is not corrupted? I'm seeing signs of filesystem corruption in the ext4 image file.

I'm currently using the same setup on my S4 (except with nano OpenGapps).

**Comment by webmaster33** [comment]
Just tested the Samsung EVO 64GB external sdcard with A SD Bench and got 17 mb/s read and 13 mb/s write result with long test.

**Comment by hankching** [comment]
@webmaster33
Pls read the following article:
www.pcmag.com/article2/0,2817,2471083,00.asp

**Comment by webmaster33** [comment]
@hankching: thanks for the article. 
The benchmarks in article shows similar performance for Samsung EVO 64GB. 
What did you want to suggest with the article?

**Comment by hankching** [comment]
I don't understand why you posted about speed test.
Speed test is ONLY some area, not whole. Corruption maybe is a small part, usually, otherwise it got error. Maybe format sd card can solve.

**Comment by webmaster33** [comment]
@chenxiaolong : what are the signs, that my external sdcard is corrupted? 
I tried to install flash opengapps again, but this time I also cleared data too for ext-slot-cm13. 
The flash went successfully, booted successfully, Google Play apps appears. 
The only thing I noticed, that Setup wizard crashed once. 
Otherwise working well. 
Now I will do a full clean flash to check it again with clean conditions. 

@hankching: yes, you are right, I should take out my card and test it with flash card reader  under Windows. Otherwise benchmarking is useless. But at least I know it is original card, not a false one. 
Just I had no time to take out the card & test it.

**Comment by chenxiaolong** [comment]
> @chenxiaolong : what are the signs, that my external sdcard is corrupted? 

@webmaster33 I mistakenly read your logs incorrectly. The `e2fsck` command was run during the flashing process to repair the ext4 image and it printed a few warnings, but those warnings are completely normal.

On another note, is your primary ROM patched? If it's not, there's a good chance it might be interfering with your other ROMs.

**Comment by webmaster33** [comment]
@chenxiaolong: cm13 + opengapps was flashed successfully. 
Before flashing, I cleaned ccompletely the cm13 slot. 
Also cleaned the primary slot, so currently I have no primary OS. 

So success may also happen because primary slot was completely cleared...
