### ISSUE TITLE
dualbootpatcher app gets forceclose

### ISSUE THREAD

**Issue by TheScarastic** [chenxiaolong/DualBootPatcher#16]
@chenxiaolong i tried to compile this app after adding support to my device but after installing app on my phone it gets force closed can u tell is it a source issue or i am compiling it in wrong way :)

**Comment by Caio99BR** [comment]
Logcat is very usefull, any way to put this this file here?
I can't help but maybe the chenxiaolong can help with this

**Comment by zeeshanhussain** [comment]
Try a debug build and then get logs

**Comment by TheScarastic** [comment]
solved
