### ISSUE TITLE
Flashing opengapps 6.0 from Miui v5 Android 4.4 shows not compatible error

### ISSUE THREAD

**Issue by webmaster33** [chenxiaolong/DualBootPatcher#166]
Flashing opengapps 6.0 from Miui v5 Android 4.4 shows not compatible error.

**Comment by hankching** [comment]
What do you want?
opengapps for Android 6.0 to put inside MIUI v5 which is Android 4.4.
6.0 => 4.4, I can't believable!

Pls close it.

**Comment by webmaster33** [comment]
NO!

I'm inside Miui v5 Android 4.4.
Starting Dual Boot Patcher app.
I wanted to flash opengapps 6.0 into CM13 (which is Android 6.0).

Is it not a real world case, that I want to flash CM13 from MIUI v5???

**Comment by wazeeahmed** [comment]
Yeah had similar issues . Wait till @chenxiaolong checks it out .

**Comment by chenxiaolong** [comment]
Please post the log files. Thanks!

**Comment by webmaster33** [comment]
Log attached.
Strange, that first time it failed, but when patched again, finished flash correctly.
Also, when failed, was not the same error I reported in first post.

[20160903.223259.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/453617/20160903.223259.tar.gz)

**Comment by webmaster33** [comment]
I was successfully flashed opengapps 6.0 from MIUI. 
However depending on where I do flash the opengapps into cm13, I get different results:
1) flashing with inapp release 2777, flashing without error, but when I reboot into cm13, boots well, works well, but there are no Google Play apps available. 

2) flashing from recovery, flashing is successful, no errors, but after rebooting and unlocking the lock screen, I get continously crashes from Setup wizard with security exception. 
Also Google Play Services are crashing with some security exception continously. 

I cleared dalvik cache & cache before flashing in both cases.

**Comment by webmaster33** [comment]
Attaching logs about flashing.
[20160904.192207.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/454034/20160904.192207.tar.gz)

**Comment by chenxiaolong** [comment]
@webmaster33 Thanks, I'll do some testing on my S4.

**Comment by webmaster33** [comment]
I used this files:
https://download.cyanogenmod.org/get/jenkins/176782/cm-13.0-20160830-NIGHTLY-jfltexx.zip
https://github.com/opengapps/arm/releases/download/20160902/open_gapps-arm-6.0-pico-20160902.zip

Also patched both using DBP r2777 version, to be flashed as ext-slot-cm13.

**Comment by chenxiaolong** [comment]
@webmaster33 Using the exact builds you linked (flashed to `extsd-slot-cm13`), TWRP 3.0.2-0 (for jfltexx), and an exFAT-formatted Samsung 64GB Evo SD card, I am unable to reproduce the issue.

The setup wizard complete fine without throwing any `SecurityException` errors and I'm able to log in to my Google account and use apps that depend on Google Play Services.

**Comment by webmaster33** [comment]
@chenxiaolong: cm13 + opengapps was flashed successfully.
Before flashing, I cleaned ccompletely the cm13 slot.
Also cleaned the primary slot, so currently I have no primary OS.

So success may also happen because primary slot was completely cleared...

**Comment by webmaster33** [comment]
Anyway, closing this issue.
Original problem & others were fixed.

**Comment by webmaster33** [comment]
BTW: flashing of cm13 to external slot in recovery took more than 6 hours. 
Is it normal?

**Comment by chenxiaolong** [comment]
> BTW: flashing of cm13 to external slot in recovery took more than 6 hours. 
> Is it normal?

Wow, I have not seen that before. On my slowest class 4 SD card, the longest it would take would be around 20 minutes.

**Comment by webmaster33** [comment]
@chenxiaolong: Today I flashed Resurrection Remix 5.7.3. It took 423 minutes. 
It is more than 7 hour.
This is why I did external sdcard speed test.
But the speed test did not show bad speed.

**Comment by hankching** [comment]
Can you try to flash data slot? Is it normal?

**Comment by wazeeahmed** [comment]
@chenxiaolong Can you take a look at the issue #176 ?
