### ISSUE TITLE
miui 7 (android 4.4 based) rom installation issue

### ISSUE THREAD

**Issue by wazeeahmed** [chenxiaolong/DualBootPatcher#169]
I tried installing miui 7 on extsd . But for failed to install at last . Used inapp flashing utility . Please add options for choosing between various android versions . I attached the log .
[MultiBoot.log.zip](https://github.com/chenxiaolong/DualBootPatcher/files/453136/MultiBoot.log.zip)

**Comment by chenxiaolong** [comment]
@wazeeahmed Please post a link to the ROM. This issue is unrelated the the Android version, which the patcher doesn't care about. Thanks!

**Comment by wazeeahmed** [comment]
Here it is bro .
[Miui7](http://www.mediafire.com/?a3m2wt72u2rsrfu)

**Comment by chenxiaolong** [comment]
Which ROM are you doing the in-app flashing from? I can't seem to reproduce the issue.

**Comment by chenxiaolong** [comment]
Please give #170 a try. It should get the `getprop` issue leading to the failure.

@webmaster33 Could you give that build a try too? It should hopefully fix the OpenGapps incompatibility issues you were encountering.

**Comment by wazeeahmed** [comment]
Confirmed ! Working ! Great ! Looks like most of the fixee upper are done here :D

**Comment by chenxiaolong** [comment]
Great! Thanks for testing!

**Comment by wazeeahmed** [comment]
You're mostly welcome bro . I will help you in everyway possible .
