### ISSUE TITLE
Device goes into bootloop after switching back to the secondary rom

### ISSUE THREAD

**Issue by wazeeahmed** [chenxiaolong/DualBootPatcher#173]
@chenxiaolong My device stuck at boot animation . So I waited a while but but device didn't vibrate at all ( to make confirmations of successful boot ) . It stuck in a bootloop . I haven't even flashed any mods which will be the sole reason for this . Complete fresh installations . Before that I went back to primary and after a whole day I booted into the secondary rom and it stuck at boot . The rom booted successfully at the first time . But when I tried booting into it from primary rom using switches it didn't boot rather than stuck at boot animation . I tried wiping dalvik cache and then it booted successfully but rapid force close of all system apps ( especially phone app ) . The logcat is attached . Though I captured it after a fresh install of the rom because the bootloop is still there .

Primary rom : resurrection remix 5.7.3
secondary rom ( on extsd slot ) : dirty unicorn 10.5
Log : 
[logcat_v3.txt](https://github.com/chenxiaolong/DualBootPatcher/files/454001/logcat_v3.txt)

**Comment by chenxiaolong** [comment]
Is your primary ROM patched (either by flashing a patched ROM or updating the ramdisk)? If not, it will screw up the SELinux labels for the secondary ROM's data files. The only way to fix this is to wipe the data for the secondary ROM.

**Comment by wazeeahmed** [comment]
Bro This happens when I try to update the ramdisk of primary rom : 
![screenshot_20160905-070937](https://cloud.githubusercontent.com/assets/8226683/18235097/327ca108-7338-11e6-8b99-70765ce247ec.png)

And here is the log of ramdisk update : 
[ramdisk-update.log.zip](https://github.com/chenxiaolong/DualBootPatcher/files/454219/ramdisk-update.log.zip)

**Comment by chenxiaolong** [comment]
Thanks for the logs! I will take a look.

> And I tried wiping data and but everytime I do it and whenever switch back to secondary rom things become the same as before .

Yep, without a patched primary ROM, when the primary ROM boots, it will break the other ROMs you have installed.

**Comment by wazeeahmed** [comment]
And one more thing ; if I flash a custom kernel for my primary rom through patching the flashable zip ; will this issue be resolved ?

**Comment by Caio99BR** [comment]
>And one more thing ; if I flash a custom kernel for my primary rom through patching the flashable zip ; will this issue be resolved ?

Like a workaround, so yes, but obvious its need to have a boot.img inside zip (if not have, not will work :P)

**Comment by chenxiaolong** [comment]
Hmm, do you have adoptable storage enabled or somehow point the storage to an external SD? The paths in the log file are all incorrect (eg. `/storage/6CD9-FA8F/MultiBoot/primary/boot.img` should be on internal storage).

> And one more thing ; if I flash a custom kernel for my primary rom through patching the flashable zip ; will this issue be resolved ?

Yes, that should solve the problem. Be sure to make a backup in case anything goes wrong :)

**Comment by wazeeahmed** [comment]
Is this log correct bro ?
[ramdisk-update.log.zip](https://github.com/chenxiaolong/DualBootPatcher/files/454227/ramdisk-update.log.zip)

**Comment by chenxiaolong** [comment]
Nope. For some reason, it still tries to access `/storage/32AA-2FD7/MultiBoot/primary/boot.img`, which is not internal storage.

**Comment by wazeeahmed** [comment]
yeap that is my external sd card fs path . sprout4 doesn't have support for adopted internal storage .

**Comment by wazeeahmed** [comment]
And bro my sprout4 has another clone ; sprout8 . So basically the zip file only contains zimage and other tools to extract the ramdisk . But it doesn't contain a bootimage ; rather than that it creates one and flashes . Will this work through patching too ?

**Comment by chenxiaolong** [comment]
It should work. Just switch to primary before flashing from recovery.

**Comment by wazeeahmed** [comment]
I'm already in primary . No worries . I'll check this out . And bro Can you please take a look at ' why dbp confuses extsd with internal storage ?' because last time I checked ; The kernel is set under internal storage . And also saved multiboot.log there .

**Comment by wazeeahmed** [comment]
Status report : It didn't work . Though device booted properly . But still ramdisk update error .

**Comment by wazeeahmed** [comment]
New update : Tried patching the primary rom and flashed over current state . It worked . Ramdisk is up to date now . The reason it wasn't before is ; The kernel zip didn't contain any ramdisk only zImage and mkbootimg etc. So the patch was unsuccessful . Going to check if the secondary rom works properly .

**Comment by chenxiaolong** [comment]
@wazeeahmed Right, the ramdisk update issue will need some workarounds in DualBootPatcher. However, you should now be able to flash a second ROM without the primary ROM breaking it.

**Comment by wazeeahmed** [comment]
Great ! Then everything'll be good as new . Checking the secondary rom now . :)

**Comment by wazeeahmed** [comment]
Confirmed ! Working ! Bootloop issue fixed . Sprout4 users ; Don't forget to patch the primary rom before flashing it . Ramdisk update has some issues . Will report an issue on that .

**Comment by wazeeahmed** [comment]
closed #173
