### ISSUE TITLE
[REQ] Support for Peregrine

### ISSUE THREAD

**Issue by Dark98** [chenxiaolong/DualBootPatcher#175]
Could you add support for Motorola Moto G 4G(Peregrine) the Mount points are the same as Motorola Moto G(Falcon)

**Comment by Caio99BR** [comment]
Can you paste the link to device tree of this device?

**Comment by Dark98** [comment]
https://github.com/CyanogenMod/android_device_motorola_peregrine
https://github.com/CyanogenMod/android_device_motorola_msm8226-common
