### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by kostoulhs** [chenxiaolong/DualBootPatcher#179]
staging-9.0.0 branch
terminal output:

```
[100%] Linking CXX executable yaml2json
CMakeFiles/yaml2json.dir/yaml2json.cpp.o: In function `yaml_node_to_json_node(YAML::Node const&)':
/home/kotzir/Desktop/DualBootPatcher/yaml2json/yaml2json.cpp:22: undefined reference to `Json::Value::Value(unsigned long)'
/home/kotzir/Desktop/DualBootPatcher/yaml2json/yaml2json.cpp:23: undefined reference to `Json::Value::Value(long)'
collect2: error: ld returned 1 exit status
yaml2json/CMakeFiles/yaml2json.dir/build.make:96: recipe for target 'yaml2json/yaml2json' failed
make[5]: *** [yaml2json/yaml2json] Error 1
CMakeFiles/Makefile2:630: recipe for target 'yaml2json/CMakeFiles/yaml2json.dir/all' failed
make[4]: *** [yaml2json/CMakeFiles/yaml2json.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make[3]: *** [all] Error 2
hosttools/CMakeFiles/hosttools.dir/build.make:110: recipe for target 'hosttools/hosttools-prefix/src/hosttools-stamp/hosttools-build' failed
make[2]: *** [hosttools/hosttools-prefix/src/hosttools-stamp/hosttools-build] Error 2
CMakeFiles/Makefile2:257: recipe for target 'hosttools/CMakeFiles/hosttools.dir/all' failed
make[1]: *** [hosttools/CMakeFiles/hosttools.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

Any help? BTW the Build guide should be updated I think

**Comment by chenxiaolong** [comment]
Ah yes, that happens if you have an older version of jsoncpp. I've updated the branch to use the jansson library instead since there's no reason to depend on two JSON libraries.

**Comment by ashoksoni** [comment]
I am having something similar to this error even though I just forked your repo. 
However my error is not pointing to jsoncpp or any other relevant dependencies.

ashoksoni@sanjay:~/DualBootPatcher/build$ make
[  1%] Performing build step for 'hosttools'
make[3]: *** No targets specified and no makefile found.  Stop.
hosttools/CMakeFiles/hosttools.dir/build.make:110: recipe for target 'hosttools/hosttools-prefix/src/hosttools-stamp/hosttools-build' failed
make[2]: *** [hosttools/hosttools-prefix/src/hosttools-stamp/hosttools-build] Error 2
CMakeFiles/Makefile2:257: recipe for target 'hosttools/CMakeFiles/hosttools.dir/all' failed
make[1]: *** [hosttools/CMakeFiles/hosttools.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Caio99BR** [comment]
The main issue can be fixed with this:

```
wget http://www.digip.org/jansson/releases/jansson-2.9.tar.gz
tar xzf jansson-2.9.tar.gz
cd jansson-2.9/
./configure
make
sudo make install
```

Maybe `docs` needs to be updated, a warning or something like this `jansson-2.9 or updated`

**Comment by ashoksoni** [comment]
Will test and report. Thanks.

**Comment by ashoksoni** [comment]
Surprisingly without doing anything, my error was gone now. Build was successful.

**Comment by ashoksoni** [comment]
Surprisingly without doing anything, my error was gone now. Build was successful.

**Comment by ashoksoni** [comment]
My issue is gone without doing anything and I was able to build successfully.

**Comment by Caio99BR** [comment]
Could be closed.
