### ISSUE TITLE
Error messages during patching are not helpful

### ISSUE THREAD

**Issue by ckrooss** [chenxiaolong/DualBootPatcher#18]
I had two problems that both resulted in error 15. This message doesn't really help and also the errors should have been different

First I used Solid Explorer to select the file which somehow messed up the filepath, adding /1/ to the beginning:

    Patching file:
    - Path:       /1/storage/extSdCard/cm-12.1-20151223-NIGHTLY-trltexx.zip.zip
    Not stopping: # of operations: 0, is bound: true

I used ES Explorer to select the file, but patching failed (error 15) because afaik Android >=5 doesn't allow access to the SDcard by default:

    Patching file:
    - Path:       /storage/extSdCard/cm-12.1-20151223-NIGHTLY-trltexx.zip.zip
    Not stopping: # of operations: 0, is bound: true

So I moved it to the internal card which finally worked.
I suggest displaying "Failure: Access denied $filename" and "Failure: File not found $filename" if something goes wrong.

**Comment by chenxiaolong** [comment]
This external SD issue is fixed now that the app uses Android's Storage Access Framework. I completely agree on having better error messages, but I'll need to find a way to make them translatable. I'd prefer not to have English-only strings anywhere in the app.

**Comment by ckrooss** [comment]
Thanks for the update.

I'll read the docs at http://developer.android.com/guide/topics/resources/localization.html and see if I can maybe commit a patch

**Comment by Caio99BR** [comment]
Issue #29 already closed, the errors related already fixed.

**Comment by Caio99BR** [comment]
Issue can be closed
