### ISSUE TITLE
[general] some things to hide

### ISSUE THREAD

**Issue by Caio99BR** [chenxiaolong/DualBootPatcher#180]
EDIT: I changed title because not is easy support many with only fstab :/

---

I think you observed when we have only primary ROM, the BootUI not is showed up, but some peoples not observed it.
I think is better hide the option (or show something) before install BootUI, to not make troubles.

---

For now is it

---

Check <https://material.uplabs.com/posts/c/resources/interface> for PR #83 
It have a lot of good styles

**Comment by hankching** [comment]
@Caio99BR
When I try to remain primary rom only , BootUI shows too.
Pls use root explorer to see a file (/raw/cache/multiboot/bootui/skip) exists or not, if exists, just delete it and reboot. After that, you can see it again.
