### ISSUE TITLE
[sony][xperia t2 ultra/tianchi] Unable to patch stock sony xperia boot

### ISSUE THREAD

**Issue by Caio99BR** [chenxiaolong/DualBootPatcher#181]
We are getting error when trying to patch the stock boot of sony via app.

> The logs:
> https://gist.github.com/Caio99BR/c819dab3a3b7c2b434ea64984dd9edde
> [daemon.txt](https://github.com/chenxiaolong/DualBootPatcher/files/460018/daemon.txt)
> [patch-file.txt](https://github.com/chenxiaolong/DualBootPatcher/files/460019/patch-file.txt)
> [boot-ui-install.txt](https://github.com/chenxiaolong/DualBootPatcher/files/460021/boot-ui-install.txt)

**Comment by chenxiaolong** [comment]
Can you link to the `boot.img`/`boot.elf` (or the entire ROM) and also to the device tree for any AOSP-based ROM? Looks like the file format changed compared to `pepper` (Xperia Sola).

**Comment by Caio99BR** [comment]
The AOSP device tree is on sonyxperiadev (sony open source account of all device tree - except some devices like falconss 😑) but it use common Android boot img 😐, idk why sony use elf (WHY?!), and this device not have many dev (it have MM AOSP ROM to be build but no one do it) also it not have many custom ROM only CM11 and variants of same.

I will get links and boot.elf tomorrow, my friend not is on now

----

After all you ask, why have MultiBoot if it not have Custom ROMs? This device have CM1,  like a said before, and Carbon also but camera in these not is AWESOME like in stock and other thing this device have potential, maybe someone can start something with a DualBoot ;P

Good night and sorry :)

**Comment by Caio99BR** [comment]
* boot.elf: <https://drive.google.com/file/d/0ByZfGgiAqjigZWNmamNYZkZuNHc/view?usp=sharing>
* aosp device tree: <https://github.com/sonyxperiadev/device-sony-tianchi>
* common aosp device tree: <https://github.com/sonyxperiadev/device-sony-yukon>
* kitkat carbon: <http://forum.xda-developers.com/t2-ultra/development/rom-carbon-rom-t3038205>
* kitkat pacman rom: <http://forum.xda-developers.com/t2-ultra/development/p-c-rom-4-4-4-xperia-t2-ultra-dual-t3021941>
* kitkat cm11: <http://forum.xda-developers.com/t2-ultra/development/rom4-4-4-cyanogenmod-11-0-unofficial-t2918431>
* stock modded 5.1: <http://forum.xda-developers.com/t2-ultra/development/decepticon-rom-t2-dual-xposed-t3269970>

**Comment by chenxiaolong** [comment]
Can this device boot from a normal `boot.img`? If yes, I will only implement read support (but not write support) for this kind of Sony ELF. The format is much worse than the ELF format for `pepper` (Xperia Sola).

**Comment by Caio99BR** [comment]
>Can this device boot from a normal boot.img?

I think the format of Carbon ROM is `.img`, so yes, if it not pass of 20MB :P 

>I'll just have it convert the file to boot.img during patching.

Its ok but any way to backup it to something like `boot.elf-before-conversion.elf`? 
Because the `boot.img-before-ramdisk-update.img` will overwrite elf with the time

**Comment by chenxiaolong** [comment]
I might not be able to fix this. Unlike the other ELF format, this one is completely undocumented and there are quite a few places in the file I don't recognize/understand.


Details:

* There are 3 ELF32 program segments, all with `p_type` and `p_flags` set to the magic values for the kernel in the other ELF boot image format. In the boot image posted above, the order is kernel -> ramdisk -> device tree, though it is unclear if this is the case for all boot images of this type.
* There's a single ELF32 section segment at offset 0x967177 with a size of 4096 bytes. The section starts at an unaligned offset and contains 8 unknown bytes at the beginning, followed by the cmdline of unknown length and no terminating sequence. I can't seem to spot a length field either.
* At offset 0x96738B, there's a sequence of 1264 bytes. 302 bytes into this sequence, there is a DER-encoded X509 cert: https://gist.github.com/chenxiaolong/9fef2ca2e8180debaea8da5602558b2a The bytes before and after the cert are unknown.

Section breakdown:

| From (inclusive) | To (exclusive) | Description                     |
|-------------|-----------|---------------------------------|
| 0x0         | 0x34      | ELF32 header                    |
| 0x34        | 0x94      | 3 ELF32 program segment headers |
| 0x94        | 0x657854  | Data for program segment 0      |
| 0x657854    | 0x913977  | Data for program segment 1      |
| 0x913977    | 0x967177  | Data for program segment 2      |
| 0x967177    | 0x968177  | Data for section segment 0      |
| 0x968177    | 0x96819F  | 1 ELF32 section segment header  |
| 0x96819F    | 0x1400000 | *Unknown* (Padding? Junk?)      |

**Comment by Caio99BR** [comment]
Could be moved to Milestone 10 (or closed)
Just for reference: https://github.com/AdrianDC/android_development_shell_tools/commit/a323715a45f16cc846d128e7710d91eb7e31b55e

**Comment by Caio99BR** [comment]
I'm abandoning my changes.
