### ISSUE TITLE
[Peregrine]Ramdisk Update Failed

### ISSUE THREAD

**Issue by Dark98** [chenxiaolong/DualBootPatcher#185]
Logs link here http://s000.tinyupload.com/index.php?file_id=94957851833904678611

**Comment by chenxiaolong** [comment]
Can you set the kernel beforehand and try again? Looks like it can't find the boot image at `/sdcard/MultiBoot/primary/boot.img`

**Comment by Dark98** [comment]
I've fixed it now, the problem was i was using adopted storage and the application wasn't copying the boot image to that directory when setting the kernel, It works perfectly fine without adopted storage

**Comment by wazeeahmed** [comment]
How does your device uses external sd while mine doesn't ? I was so anxious about it . your adopted storage was mounted in /data/media/0 right ?
