### ISSUE TITLE
[Request] Support for LG G5? 

### ISSUE THREAD

**Issue by onestyle007** [chenxiaolong/DualBootPatcher#188]
Is there a chance you could support LG G5 H850 ? 

[Twrp.me-LG H850](https://twrp.me/devices/lgg5h850.html)

**Comment by chenxiaolong** [comment]
Can you flash the GetLogs zip at https://snapshots.noobdev.io/ and upload the file it creates in /sdcard/logs/? The TWRP device tree link only provides the information I need to add support for the Boot UI. Thanks!

**Comment by onestyle007** [comment]
Here already the logs
[https://www.dropbox.com/s/sq6aovnysy324tr/20160101.230246.tar.gz?dl=0  ](logs)
Thank you for your work 👍

**Comment by chenxiaolong** [comment]
@onestyle007 Thanks for the logs! Please give the test build at #195 a try.

**Comment by onestyle007** [comment]
After trying to boot to the second rom,boot ui shows,restarts,black screen and boot directly to twrp. 
Here are the logs : [Logs](https://dl.dropboxusercontent.com/u/66517134/20160101.235643.tar.gz)
and logs from multiboot folder after booting in the first rom [Multiboot](https://dl.dropboxusercontent.com/u/66517134/Archive.zip)

**Comment by chenxiaolong** [comment]
@onestyle007 Please give this test build a try and grab the logs again: https://jenkins.noobdev.io/job/DualBootPatcher_Build/219/label_exp=dualbootpatcher-builder%20&&%20fast,target=android-all-gcc/

This build does not fix anything. It just enables more logging.

**Comment by onestyle007** [comment]
I'm having an sd card error at the moment,i'll put the logs as soon as i transfer files and format it. Thanks again for all your work :)

**Comment by onestyle007** [comment]
Okay i did a stupid thing and forgot to install bootUi.
Dual boot works. Just after patching kernel next step is installing bootUI from settings and that is it. Dual boot officially supported on LG G5 . I've used this 
https://github.com/chenxiaolong/DualBootPatcher/pull/195

**Comment by onestyle007** [comment]
There is a bug with the sd card. When booting stock primary rom,everything is okay,but when i boot in secondary rom (cm13) i get corrupted sd card . what can i do?

**Comment by wazeeahmed** [comment]
the bug is with cm13 not dualboot patcher . Ask your device maintainer to sort this out .

**Comment by onestyle007** [comment]
Might be,but when i boot cm13 as primary rom and stock lg as secondary rom,cm13 has sd card support and stock shows it's corrupted. Do you need logs after booting secondary rom?

**Comment by wazeeahmed** [comment]
backup sd card contents and format it as fat32 and try again .

**Comment by onestyle007** [comment]
Still the same, it shows as corrupted when booting secondary rom,no matter if i format it using android format option or my laptop.

**Comment by wazeeahmed** [comment]
wait for @chenxiaolong then .

**Comment by chenxiaolong** [comment]
@onestyle007 Do you know how to use adb? If so, could you grab a logcat while CM13 is booting and also grab the dmesg output?

```sh
adb logcat > logcat.txt
adb shell dmesg > dmesg.txt
```

**Comment by onestyle007** [comment]
@chenxiaolong 
Here are the logs grabbed while cm13 is booting as secondary rom 
https://www.dropbox.com/s/zs1dhzns8p6ownk/Logcat-Dmesg.zip?dl=0

**Comment by Nonta72** [comment]
@chenxiaolong 
Any update on the fake "SDCard is corrupted" message ?
I'm also experiencing it.
As @onestyle007 stated, it isn't actually an sd card issue. Even if you format it, it will become corrupted again after few reboots.

**Comment by KaMyKaSii** [comment]
http://forum.xda-developers.com/showthread.php?t=2447534&p=69033267

In my post I have attached a log generated by Liveboot app and apparently has the information needed to fix the error. But you could also generate the same? Thus the dev is more likely to compare what is wrong on both devices

**Comment by Nonta72** [comment]
Liveboot doesn't work on my device. I can provide a logcat if needed instead.

**Comment by onestyle007** [comment]
Since the build that was released on the 25.10.2016, there is no more SD card bug. Everything works perfect
