### ISSUE TITLE
About cach/bootui/skip file.

### ISSUE THREAD

**Issue by hankching** [chenxiaolong/DualBootPatcher#189]
When did switch rom, the skip file doesn't delete. Next, the skip file will exist forever, it is needed to delete by manually.

Maybe change skip file to next file, which means it will boot what on next.

Pls solve this minor bug.

Thanks

**Comment by chenxiaolong** [comment]
Ah crap, you're right. Give me a few minutes and I'll create a new PR with a fix.

**Comment by chenxiaolong** [comment]
@hankching Please give #194 a try.

**Comment by hankching** [comment]
Solved.
