### ISSUE TITLE
About voldmanaged=sdcard issue

### ISSUE THREAD

**Issue by hankching** [chenxiaolong/DualBootPatcher#196]
My phone has one kernel includes both sdcard0 and sdcard1, therefore, /raw/extsd is wrongly located at internal storage because of orderring.

The extraction as follows:
> /devices/mtk-msdc.0/11230000.MSDC0 auto vfat defaults voldmanaged=sdcard0:emmc@intsd,noemulatedsd
> 
> /devices/mtk-msdc.0/11240000.MSDC1 auto vfat defaults voldmanaged=sdcard1:auto

Other kernels have removed internal storage from voldmanaged. 

Therefore, I'm facing this issue. I can manually reorder it for temporary.

Pls consider it and solve it.

Thanks in advanced.

**Comment by chenxiaolong** [comment]
@hankching Please give the test build at #197 a try. Thanks!

**Comment by hankching** [comment]
It works too.
Thanks

**Comment by wazeeahmed** [comment]
@hankching Never mind for this silly question bro . How do you use the boot ui ? Do I have to patch the recovery to use that ?

**Comment by hankching** [comment]
Settings -≥ install Boot UI

**Comment by wazeeahmed** [comment]
I did that and rebooted the device . yet nothing happens .
