### ISSUE TITLE
[Request] Xiaomi MI5

### ISSUE THREAD

**Issue by Simon90x** [chenxiaolong/DualBootPatcher#209]
Hi,
could you provide support for Xiaomi MI5? 

[20160929.090413.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/500856/20160929.090413.tar.gz)

Thanks

**Comment by chenxiaolong** [comment]
@Simon90x Please give the test build at #212 a try.

**Comment by Simon90x** [comment]
Works perfectly, many thanks.

**Comment by chenxiaolong** [comment]
Great! Thanks for testing! This will be officially available in version 9.0.0.
