### ISSUE TITLE
[Request] Samsung Galaxy Tab S 8.4 LTE

### ISSUE THREAD

**Issue by haimann951** [chenxiaolong/DualBootPatcher#21]
Could you please add the the Samsung Tab S 8.4 LTE? The codename is klimtlte and it's using the Exynos 5420. The partitions are the same like the already supported wifi models.

Here is the link to the getlogszip output tar: https://www.dropbox.com/s/mure8kmfnahz0v0/Dualbootpatcherlogs-SM-T705.tar?dl=0

**Comment by chenxiaolong** [comment]
Done, thanks! It's grouped together with the other Galaxy Tab S devices.
