### ISSUE TITLE
CMake Error Unknown option to -E tar: --format=zip

### ISSUE THREAD

**Issue by Nonta72** [chenxiaolong/DualBootPatcher#215]
Hi,
I'm still having this error. I used to skip the bootui creation but now I want to test it on my device but I keep getting this error.
How do I fix it ?
Ubuntu 14.04 LTS x64
Cmake version: 3.2.2
Tar version: 1.29
Make version: 3.81

**Comment by Nonta72** [comment]
Fixed by upgrading to cmake 3.6.2
But g++ still have an error related to " no-pedantic " option related to terminal.cpp
How do I fix that ?
Thanks

**Comment by chenxiaolong** [comment]
Can you post the full build log?

**Comment by Nonta72** [comment]
Surprisingly it didn't happen again.
I removed the whole repo and cloned it again. Then no more errors.
Maybe it was due to my previous commits ? Because I have reverted most of them lately.
For now, everything seems fine. I may reopen it if it happens again.
