### ISSUE TITLE
[Request] Moto E 2015 (surnia)

### ISSUE THREAD

**Issue by f1vefour** [chenxiaolong/DualBootPatcher#22]
I would like to see this device supported please.

**Motorola Moto E - XT1526 (*surnia*)**

Partition | Location
------------ | -------------
boot | /dev/block/mmcblk0p33
cache | /dev/block/mmcblk0p42
recovery | /dev/block/mmcblk0p34
system | /dev/block/mmcblk0p41
userdata | /dev/block/mmcblk0p43

**Comment by Caio99BR** [comment]
Close this

**Comment by chenxiaolong** [comment]
Closing due to your PR #25
