### ISSUE TITLE
How to restore the backup ?

### ISSUE THREAD

**Issue by wazeeahmed** [chenxiaolong/DualBootPatcher#235]
I made a backup of current rom . But how do I restore it ? This feature is missing . 😔

**Comment by chenxiaolong** [comment]
It's not missing 🙂  You just flash it from the in-app flasher. I made it this way because backups can be restored to any slot, just like flashing ROMs.

[![blah](http://i.imgur.com/jGCaRsCl.png)](http://i.imgur.com/jGCaRsC.png)

**Comment by wazeeahmed** [comment]
That is not only great ; but the coolest thing you ever gave us all 😊
