### ISSUE TITLE
SDCard corruption false alarms after enabling DBP in P1a4(1|2)

### ISSUE THREAD

**Issue by MSF-Jarvis** [chenxiaolong/DualBootPatcher#236]
Logs here : 

P1a41 - https://transfer.sh/vfiJc/20161010.095719.tar.gz

P1a42 - https://transfer.sh/XW41K/20161010.100504.tar.gz

**Comment by chenxiaolong** [comment]
This will no longer happen with the latest snapshot at https://snapshots.noobdev.io as long as you don't boot from an SD card.
