### ISSUE TITLE
Missing wipe and backup option in the boot ui

### ISSUE THREAD

**Issue by wazeeahmed** [chenxiaolong/DualBootPatcher#239]
Won't it be great to wipe a rom so that I can clean flash it without disrupting the second one ! I hope so . If bootui had at least backup and wipe option ; we wouldn't have to worry about clean flashing any rom ; would we ? hoping it will get added in time . Regards ! Enjoying all the fruits of your work and they are a delight of eyes if you ask me :)

**Comment by webmaster33** [comment]
Yeah, I would also welcome these features in boot ui. Also patching feature. Chenxiaolong wrote it is difficult to do it in Aroma. 
I hope sometime there will be possible to have implemented.
