### ISSUE TITLE
wrong parameter for Getlogs-xxxxxxxx.zip

### ISSUE THREAD

**Issue by hankching** [chenxiaolong/DualBootPatcher#246]
Gettloggs includes those parameters as follows:
> ls -lR /system > listings/system_full
> ls -lR /system > listings/system_contexts

Maybe second line uses -IZ

**Comment by chenxiaolong** [comment]
Thanks! Fixed in https://snapshots.noobdev.io/misc/getlogs/GetLogs-20161019-2.zip
