### ISSUE TITLE
transifex: Portuguese Brazil updated!

### ISSUE THREAD

**Issue by Caio99BR** [chenxiaolong/DualBootPatcher#247]
It's now full ready to use!

Can you update it?

**Comment by chenxiaolong** [comment]
I did a pull and it looks like nothing changed?

**Comment by Caio99BR** [comment]
But i made it.
![image](https://cloud.githubusercontent.com/assets/7280407/19837867/843f623a-9eaa-11e6-9a45-af6e3c620746.png)
![image](https://cloud.githubusercontent.com/assets/7280407/19837872/9a59446e-9eaa-11e6-952b-a764b1648043.png)

**Comment by chenxiaolong** [comment]
Hmm, I might need to download manually. Their command line `tx` tool can't pull it for some reason.
