### ISSUE TITLE
BootUI - change countdown value in settings

### ISSUE THREAD

**Issue by webmaster33** [chenxiaolong/DualBootPatcher#249]
On Samsung Galaxy S4 i9505, jfltexx:
The BootUI shows a counter, which counts down from 5 to 1.

Could be possible to change countdown value in settings?

**Comment by chenxiaolong** [comment]
Thanks for the feature request! This has now been implemented.

[![settings](http://i.imgur.com/GanAp4Jm.png)](http://i.imgur.com/GanAp4J.png) [![sample](http://i.imgur.com/nLurtXvm.png)](http://i.imgur.com/nLurtXv.png)

**Comment by webmaster33** [comment]
Thank you very much implementing this feature!
