### ISSUE TITLE
BootUI - add button to start booting default slot

### ISSUE THREAD

**Issue by webmaster33** [chenxiaolong/DualBootPatcher#250]
Could be possible to add button to BootUI, to start booting default slot immediately, without waiting the countdown?

**Comment by chenxiaolong** [comment]
This has been implemented now!

[![sample](http://i.imgur.com/1D8g474m.png)](http://i.imgur.com/1D8g474.png)

**Comment by webmaster33** [comment]
Thank you very much!

**Comment by webmaster33** [comment]
Could you rename the button from Skip countdown to Start booting?
