### ISSUE TITLE
[Suggestion] Add ROMID at the end backup folder

### ISSUE THREAD

**Issue by hankching** [chenxiaolong/DualBootPatcher#251]
Would you mind add ROMID/ROM name at the end of backup name for folder?

For example folder of backup as below:
ROMID : data-slot-CM13
DATE    : 2016.10.21
TIME     : 10.20.40

Current : 2016.10.21-10.20.40

Suggest : 2016.10.21-10.20.40_data-slot-CM13
       OR    : 2016.10.21-10.20.40-CM13

Which we can directly know what inside backup.

Thanks

**Comment by chenxiaolong** [comment]
Thanks! This has been implemented.
