### ISSUE TITLE
Does the patcher supports f2fs ?

### ISSUE THREAD

**Issue by wazeeahmed** [chenxiaolong/DualBootPatcher#269]
I'm willing to try f2fs partition scheme in data and cache partition . Just wanted to know if the patcher faces mount issue if I convert my data and cache as f2fs partition .

**Comment by chenxiaolong** [comment]
The patcher doesn't care about the filesystem, but if you switch to f2fs, every ROM you flash must support it.

**Comment by wazeeahmed** [comment]
Yeah it really doesn't . As it just has to be patched from dbp to get it working like everything else ☺
