### ISSUE TITLE
[Request] Support to all Languages

### ISSUE THREAD

**Issue by Caio99BR** [chenxiaolong/DualBootPatcher#27]
I have tried to translate to my language but the App only support part of all languages in the world, my language is pt-BR and the app only support pt-PT.
Idk how to do this, if not i already have opened a Pull Request :P

**Comment by chenxiaolong** [comment]
Translations are handled in Transifex: https://www.transifex.com/dualbootpatcher/dualbootpatcher/dashboard/ I've just added pt_BR to the list of available languages. :)

**Comment by Caio99BR** [comment]
OK :D

**Comment by Caio99BR** [comment]
The correct is https://www.transifex.com/dualbootpatcher/dualbootpatcher for new users.
I think is needed to create a WiKi for this big project :P

**Comment by Caio99BR** [comment]
And Crowdin is better of Transifex (used by Kernel Adiutor)

**Comment by Caio99BR** [comment]
pt-BR 100% translated
Test crowdin after.

**Comment by chenxiaolong** [comment]
Merged in commit 0aae56b16605827b8818715166228cfbb76cf94b.

CrowdIn stuff will be tracked in issue #30.

**Comment by Caio99BR** [comment]
Ok

**Comment by benrap** [comment]
Can you go to transifex and enable the language i requested to be enabled? It's Hebrew

**Comment by chenxiaolong** [comment]
@benrap Added, thanks!

**Comment by benrap** [comment]
Hebrew translations finished, ready to be merged.
