### ISSUE TITLE
[Request] Change Dualbootpatcher to use first Partition on external SDcard 

### ISSUE THREAD

**Issue by gcgeforce** [chenxiaolong/DualBootPatcher#28]
Is it possible to change Dualbootpatcher to use first Partition on external SDcard? as if you have 2 partitions on your external SDcard: 1st = fat32, 2nd (last) = EXT4, dualbootpatcher will use EXT4 instead of the fat32 partition and when you boot into recovery you will not see the EXTSD slots.  I am using the EXT4 for app2sd to expand my memory to install apps, and is mapped to /raw/extsd and dualbootpatcher is using the same thing.

**Comment by chenxiaolong** [comment]
Yep, I'll need to modify the uevent device scanning code. The current method is very hacky (https://github.com/chenxiaolong/DualBootPatcher/blob/master/mbtool/initwrapper/devices.cpp#L413); every time the kernel detects a new partition, that partition will be used.

When I get to fixing this, I'll probably make it behave similar to how storage is handled in Android with `vold`.

**Comment by gcgeforce** [comment]
Thank you for looking at this.

**Comment by chenxiaolong** [comment]
This has finally been implemented.
