### ISSUE TITLE
Cm14 boot issue on extsd slot

### ISSUE THREAD

**Issue by wazeeahmed** [chenxiaolong/DualBootPatcher#286]
Just tried flashing cm14 on extsd slot today from build r71 . The following thing occured : 

1. After finishing flashing on twrp recovery ; there was an red marked messege called E:\ log : no command found . But the flashing was successful .

2. Device rebooted and hung up in boot logo and vibrated thrice . And rebooted into recovery . Battery wasn't pulled out .

3. Used latest getlog zip from snapshot.noobdev.io and flashed it instantly while I was in recovery .

Here is the log : 
[20161109.124824.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/580390/20161109.124824.tar.gz)

**Comment by chenxiaolong** [comment]
You probably solved this by now, but is your `/cache` partition formatted with f2fs? The ROM only supports ext4.

**Comment by wazeeahmed** [comment]
I guess that must be it . I'll test and let you know :)

**Comment by wazeeahmed** [comment]
Sorry for being too late . Yeah it was only file system issue . Flashed f2fs supported kernel and it's all good .
