### ISSUE TITLE
[Backup] Choice for default in External Card is not possible

### ISSUE THREAD

**Issue by Caio99BR** [chenxiaolong/DualBootPatcher#292]
Without no one reason, i can't select any folder inside of External Card.
https://gist.github.com/Caio99BR/fcf1d72c4d6fd9e1b1e5799666275c58
Tested only in Android 4.4.2 (Sony Stock) and in Android 4.4.4 (CM11) with SanDisk Class 4 16GB.

Also you need to make some check of storage space before do anything, big problems for most of supported devices.

---

- [x] Fix dealing of backup in external partitions(?)
- [ ] Provide a check of storage in the time of backup to prevent users to do something stupid (:P)

**Comment by Caio99BR** [comment]
@chenxiaolong here the log:
https://gist.github.com/Caio99BR/fcf1d72c4d6fd9e1b1e5799666275c58

**Comment by chenxiaolong** [comment]
Hmm, I'll look into this now. I completely forgot Android 4.4 also uses DocumentsUI and didn't test it there.

**Comment by Caio99BR** [comment]
It have Android 4.3 too :P

**Comment by chenxiaolong** [comment]
@Caio99BR Do you have a logcat for Android 4.3? It doesn't use DocumentsUI so it might be a different issue.

**Comment by Caio99BR** [comment]
No, because the DBP still not support ELF images and i can't MultiBoot with this.
So i can't manage to boot it, sorry :(

**Comment by chenxiaolong** [comment]
@Caio99BR Can you try the test build at #311? I think it should fix the issue.

> DBP still not support ELF images

I still cannot any documentation on that format :( It's very different from the other ELF format used by Sony devices.

**Comment by Caio99BR** [comment]
Fixed!!
![photo_2016-11-27_22-09-54](https://cloud.githubusercontent.com/assets/7280407/20653099/42207e5c-b4ee-11e6-8921-f9a2cfdb3913.jpg)

Now i need to make the backup :)
Thanks :+1:

**Comment by chenxiaolong** [comment]
Great! I'll merge the changes.

**Comment by Caio99BR** [comment]
Now you need to put a check for free space, like in recovery

**Comment by chenxiaolong** [comment]
I don't know of a good way to do that. The backups are compressed and there's no way to calculate how big the compressed files will be.

**Comment by Caio99BR** [comment]
You can add a way to disable the check of free space, and do it like in recovery
