### ISSUE TITLE
Sign mbtool binaries

### ISSUE THREAD

**Issue by chenxiaolong** [chenxiaolong/DualBootPatcher#31]
We should look into signing the mbtool binaries. That way, the app can send newer mbtool builds to the currently running mbtool daemon and the daemon can safely upgrade itself. Once is done, we're one step closer to removing the root requirement as the app will no longer need to manually execute `mbtool daemon --replace`.

I'm planning to use an extremely simple method to sign the binaries: just sign them with the same private key as the one used to sign the Android app and store it in a separate file with the extension `.sig`. The certificates are already hardcoded in mbtool's `validcerts.cpp`, so verification will be very easy.

Implementing signing and verification:
- [x] Have CMake extract private key from the Java keystore
- [x] Use either the `openssl` command or a custom program to sign the binaries during the build
- [x] Implement verification procedure in mbtool
- [x] Add functions in mbtool to verify the signature of a file
- [x] Update mbtool_recovery to enforce signature checking when executing any of our binaries that are in the patched zip
- [x] Update Android app to use mbtool's SignedExec call instead of root to launch the in-app flashing process
- [x] Update mbtool to enforce signature checking when executing any of our binaries during boot
- [x] Update Android app to never replace mbtool using root unless the interface versions are mismatched or mbtool isn't running (eg. unpatched primary ROM)
- [x] Bump minimum in-app flashing version and daemon version before merging

**Comment by chenxiaolong** [comment]
The signed-exec branch now signs `mbtool`, `mbtool_recovery`, `odinupdater`, and `fuse-sparse`. The next step is to sign everything else that goes into patched files (including third party binaries).

**Comment by chenxiaolong** [comment]
All asset files are now signed (both DualBootPatcher binaries and thirdparty binaries) and the signature files are placed in the output zip alongside the original files. The next step is to update mbtool to verify these files before executing or using them.

**Comment by chenxiaolong** [comment]
The branch switched to using BoringSSL on Android. It has all the features we need for and results in far smaller binaries (~200KB extra vs >1MB).

**Comment by Caio99BR** [comment]
Why BoringSSL?

**Comment by chenxiaolong** [comment]
@Caio99BR All three forks/variants (OpenSSL, BoringSSL, LibreSSL) are well-maintained and provide the code signing/verification features we need, but OpenSSL and LibreSSL are far larger than BoringSSL. After adding the signature verification code, the armeabi-v7a mbtool size increased by:

OpenSSL: ~640KB -> ~1.6MB
BoringSSL: ~640KB -> ~828KB
LibreSSL: ~640KB -> ~1.8MB

It would be impossible to use OpenSSL and LibreSSL for the Galaxy S4 because the boot partition is too small.

**Comment by Caio99BR** [comment]
Ok, look good :)

**Comment by chenxiaolong** [comment]
In-app flashing now no longer requires root :) Though root is still required to update mbtool.

**Comment by Caio99BR** [comment]
How it works now?

**Comment by Caio99BR** [comment]
Other thing, after this you will bump up?

**Comment by chenxiaolong** [comment]
> How it works now?

Instead of running the `mbtool rom-installer -r <ROM ID> /sdcard/blah.zip` command with root, the app will provide the mbtool binary and signature paths to the mbtool daemon. The daemon will copy those 2 files to a private `tmpfs` mountpoint and verify the signature. If the signature is valid, it will run the process and send the output back to the app. The daemon always exists in patched ROMs, so this allows in-app flashing and backup/restore to work in unrooted ROMs.

> Other thing, after this you will bump up?

What do you mean?

**Comment by Caio99BR** [comment]
From Major version 8 to 9, a lot of time have passed since last bump up

**Comment by chenxiaolong** [comment]
Ahh, yes! After this is completely implemented (and backup/restore is available in the app), I will bump the major version.

**Comment by Caio99BR** [comment]
Ok, thanks for reply! :)
Ps: before bump up, check loading icon of patch zip.
Ps2: organize the options of app, like "Interface", "Patcher", "etc, look more good than actual.
Ps3: why you not pack the app in patched zip?
Ps4: the transitions can look more good, like Telegram (example), because the app is Material but have transitions of JB.
Ps5: put the three dot button more bigger, because is a sacrifice press it on a ldpi device.
Ps6: why not a option button to change location before patch or install zip.
Ps7: the last, since i need to stop with this things the app already is very good, fix rotation of about page in ldpi, i not can see the links, put a fake button in end of page, anything, you not can read all.
Ps8: after solve Sony FalconSS support, i will stop with this things. "If you can't solve it, don't say to others solve it :)"

**Comment by chenxiaolong** [comment]
> Ok, thanks for reply! :)
> Ps: before bump up, check loading icon of patch zip.
> Ps2: organize the options of app, like "Interface", "Patcher", "etc, look more good than actual.
> Ps4: the transitions can look more good, like Telegram (example), because the app is Material but have transitions of JB.
> Ps5: put the three dot button more bigger, because is a sacrifice press it on a ldpi device.
> Ps7: the last, since i need to stop with this things the app already is very good, fix rotation of about > page in ldpi, i not can see the links, put a fake button in end of page, anything, you not can read all.

Created this issue for all the UI issues and Material Design inconsistencies: https://github.com/chenxiaolong/DualBootPatcher/issues/83 :)

> Ps3: why you not pack the app in patched zip?

Two reasons for this. The first reason is because I don't want to increase the size of every patched zip by 10+ MB. The second reason is that there's no easy way to get the version number of an APK from C++. If, say, a SuperSU zip was patched with an older version and a CM nightly was patched with a newer version, flashing CM and then SuperSU should not downgrade the app.

> Ps6: why not a option button to change location before patch or install zip.

What location are you talking about? If you're referring to the DocumentsUI file picker, unfortunately, the SAF APIs don't provide a way for me to do that.

> Ps8: after solve Sony FalconSS support, i will stop with this things. "If you can't solve it, don't say to others solve it :)"

Yes, lets definitely fix this :)

**Comment by Caio99BR** [comment]
Wait a moment, the app have access to write /boot partition now?

**Comment by chenxiaolong** [comment]
> Wait a moment, the app have access to write /boot partition now?

It always did? That's how it switches ROMs.

**Comment by Caio99BR** [comment]
I mean without root now

Em seg, 4 de abr de 2016 03:22, Andrew Gunnerson <notifications@github.com>
escreveu:

**Comment by chenxiaolong** [comment]
Ah okay. So the `mbtool` daemon has always done the work for writing to the boot partition. As long as mbtool was running, the app could write to the boot partition. The only two things that required root were:

* Updating mbtool after apk update
* In-app flashing

The new changes allow both cases to work without root.
