### ISSUE TITLE
ROMs list is not reloaded when a ROM is wiped

### ISSUE THREAD

**Issue by chenxiaolong** [chenxiaolong/DualBootPatcher#35]
Just need to have `RomDetailActivity` pass back a flag to `SwitcherListFragment` indicating that a ROM is wiped.

```java
    @Override
    public void onActivityResult(int request, int result, Intent data) {
        switch (request) {
        case REQUEST_FLASH_ZIP:
            reloadRomsState();
            break;
        }

        // TODO: Something for RomDetailActivity here

        super.onActivityResult(request, result, data);
    }
```

From: http://forum.xda-developers.com/showthread.php?p=64725633#post64725633

**Comment by Caio99BR** [comment]
http://stackoverflow.com/questions/10570243/asynctask-after-execution-how-to-update-view

I cant help much because idk absolutely nothing about Android App Source, i understand the basic.

**Comment by Caio99BR** [comment]
I can only help with GUI.
I have see various things in UI what needs to be changed :P
