### ISSUE TITLE
Add proper Guide For how to compile apk on Windows os

### ISSUE THREAD

**Issue by dg28gadhavi** [chenxiaolong/DualBootPatcher#368]
I want to compile apk and give it a try but i am unable to compile apk from sources on windows as the guide is for Linux only I tried git bash & cygwin but both has it's own incapabilities plz someone provide guide how to compile apk on Windows os

**Comment by wazeeahmed** [comment]
Are you on windows 10 64 bit ?

**Comment by dg28gadhavi** [comment]
Win 7 32 bit

**Comment by dg28gadhavi** [comment]
I shifted to linux mint to compile apk can you just plz help me hpw to compile ap i am getting error while compiling during execution of make command i have pushed a different issue plz look at that error and guide me

**Comment by wazeeahmed** [comment]
If your computer is on win 10 64 bit , then you can try ubuntu on windows feature . Which will provide all the unix like functionality in windows environment .
