### ISSUE TITLE
Building: OpenSSL not is found by find_package

### ISSUE THREAD

**Issue by Caio99BR** [chenxiaolong/DualBootPatcher#372]
> -- NOTE: Android actually uses BoringSSL
> CMake Error at /usr/local/share/cmake-3.6/Modules/FindOpenSSL.cmake:345 (list):
>   list GET given empty list
> Call Stack (most recent call first):
>   cmake/dependencies/openssl.cmake:12 (find_package)
>   cmake/Dependencies.cmake:67 (include)
>   CMakeLists.txt:180 (include)
> 
> 
> CMake Error at /usr/local/share/cmake-3.6/Modules/FindOpenSSL.cmake:346 (list):
>   list GET given empty list
> Call Stack (most recent call first):
>   cmake/dependencies/openssl.cmake:12 (find_package)
>   cmake/Dependencies.cmake:67 (include)
>   CMakeLists.txt:180 (include)
> 
> 
> CMake Error at /usr/local/share/cmake-3.6/Modules/FindOpenSSL.cmake:348 (list):
>   list GET given empty list
> Call Stack (most recent call first):
>   cmake/dependencies/openssl.cmake:12 (find_package)
>   cmake/Dependencies.cmake:67 (include)
>   CMakeLists.txt:180 (include)
> 
> 
> CMake Error at /usr/local/share/cmake-3.6/Modules/FindOpenSSL.cmake:350 (list):
>   list GET given empty list
> Call Stack (most recent call first):
>   cmake/dependencies/openssl.cmake:12 (find_package)
>   cmake/Dependencies.cmake:67 (include)
>   CMakeLists.txt:180 (include)
> 
> 
> -- Found OpenSSL: /home/travis/build/Caio99BR/DualBootPatcher/build/thirdparty/prebuilts/boringssl/r2486.a2d4c0c-1/x86_64/lib/libssl.a;/home/travis/build/Caio99BR/DualBootPatcher/build/thirdparty/prebuilts/boringssl/r2486.a2d4c0c-1/x86_64/lib/libcrypto.a (found version ".0.0`") 
> -- Configuring incomplete, errors occurred!
> See also "/home/travis/build/Caio99BR/DualBootPatcher/build/android/android-system_x86_64-prefix/src/android-system_x86_64-build/CMakeFiles/CMakeOutput.log".
> See also "/home/travis/build/Caio99BR/DualBootPatcher/build/android/android-system_x86_64-prefix/src/android-system_x86_64-build/CMakeFiles/CMakeError.log".
> make[2]: *** [android/android-system_x86_64-prefix/src/android-system_x86_64-stamp/android-system_x86_64-configure] Error 1
> make[1]: *** [android/CMakeFiles/android-system_x86_64.dir/all] Error 2
> make: *** [all] Error 2
> 
> 
> The command "make" exited with 2.

Log is here: https://s3.amazonaws.com/archive.travis-ci.org/jobs/193916752/log.txt
TravisCI script here: https://github.com/Caio99BR/DualBootPatcher/blob/master/.travis.yml

All dependencies are installed, but it not work, please help @chenxiaolong

**Comment by Caio99BR** [comment]
Fixed after using CMake 3.7.2.
I will do a Pull Request to add warnings to `docs`

**Comment by dg28gadhavi** [comment]
Thnx man your guide helped me can you just help me the above problem is solved by your guide the boring ssl one ,but when i type make apk this error comes can you just look at it and help me how to resolve it plz

**Comment by dg28gadhavi** [comment]
dhruv@dhruv-System-Product-Name ~/Desktop/DualBootPatcher/build $  rm -rf assets && cpack -G TXZ
CPack: Create package using TXZ
CPack: Install projects
CPack: - Run preinstall target for: DualBootPatcher
CPack: - Install project: DualBootPatcher
CPack: Create package
CPack: - package: /home/dhruv/Desktop/DualBootPatcher/build/assets/data-9.1.0.tar.xz generated.
dhruv@dhruv-System-Product-Name ~/Desktop/DualBootPatcher/build $ make apk
Scanning dependencies of target apk
/usr/bin/env: ‘sh\r’: No such file or directory
Android_GUI/CMakeFiles/apk.dir/build.make:57: recipe for target 'Android_GUI/CMakeFiles/apk' failed
make[3]: *** [Android_GUI/CMakeFiles/apk] Error 127
CMakeFiles/Makefile2:709: recipe for target 'Android_GUI/CMakeFiles/apk.dir/all' failed
make[2]: *** [Android_GUI/CMakeFiles/apk.dir/all] Error 2
CMakeFiles/Makefile2:716: recipe for target 'Android_GUI/CMakeFiles/apk.dir/rule' failed
make[1]: *** [Android_GUI/CMakeFiles/apk.dir/rule] Error 2
Makefile:299: recipe for target 'apk' failed
make: *** [apk] Error 2
