### ISSUE TITLE
error while executing "make apk" command

### ISSUE THREAD

**Issue by dg28gadhavi** [chenxiaolong/DualBootPatcher#373]
dhruv@dhruv-System-Product-Name ~/Desktop/DualBootPatcher/build $  rm -rf assets && cpack -G TXZ
CPack: Create package using TXZ
CPack: Install projects
CPack: - Run preinstall target for: DualBootPatcher
CPack: - Install project: DualBootPatcher
CPack: Create package
CPack: - package: /home/dhruv/Desktop/DualBootPatcher/build/assets/data-9.1.0.tar.xz generated.
dhruv@dhruv-System-Product-Name ~/Desktop/DualBootPatcher/build $ make apk
Scanning dependencies of target apk
/usr/bin/env: ‘sh\r’: No such file or directory
Android_GUI/CMakeFiles/apk.dir/build.make:57: recipe for target 'Android_GUI/CMakeFiles/apk' failed
make[3]: *** [Android_GUI/CMakeFiles/apk] Error 127
CMakeFiles/Makefile2:709: recipe for target 'Android_GUI/CMakeFiles/apk.dir/all' failed
make[2]: *** [Android_GUI/CMakeFiles/apk.dir/all] Error 2
CMakeFiles/Makefile2:716: recipe for target 'Android_GUI/CMakeFiles/apk.dir/rule' failed
make[1]: *** [Android_GUI/CMakeFiles/apk.dir/rule] Error 2
Makefile:299: recipe for target 'apk' failed
make: *** [apk] Error 2

**Comment by dg28gadhavi** [comment]
I am on linux mint 64bit plz someone help if possible...

**Comment by webmaster33** [comment]
It seems, you have a script with DOS linefeeds:
/usr/bin/env sh\r

The \r is the DOS linefeed (\n\r). If you are under Linux, then you have to use Linux linefeed (just \n). 

So you have to find, which file has DOS linefeeds left, when copied from Windows...

**Comment by dg28gadhavi** [comment]
thnx for the kind help i solved that error but a newone arised plz help

**Comment by dg28gadhavi** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Android_GUI'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.android.support:support-v4:25.1.0.
     Required by:
         project :
   > Could not find com.android.support:appcompat-v7:25.1.0.
     Required by:
         project :
   > Could not find com.android.support:cardview-v7:25.1.0.
     Required by:
         project :
   > Could not find com.android.support:palette-v7:25.1.0.
     Required by:
         project :
   > Could not find com.android.support:design:25.1.0.
     Required by:
         project :
   > Could not find com.android.support:recyclerview-v7:25.1.0.
     Required by:
         project :
   > Could not find com.android.support:support-v13:25.1.0.
     Required by:
         project :
   > Could not find com.android.support:appcompat-v7:25.1.0.
     Required by:
         project : > com.afollestad.material-dialogs:core:0.8.6.1
         project : > com.afollestad.material-dialogs:commons:0.8.6.1
   > Could not find com.android.support:support-v4:25.1.0.
     Required by:
         project : > com.afollestad.material-dialogs:core:0.8.6.1
   > Could not find com.android.support:support-annotations:24.0.0.
     Required by:
         project : > com.afollestad.material-dialogs:core:0.8.6.1
   > Could not find com.android.support:recyclerview-v7:25.1.0.
     Required by:
         project : > com.afollestad.material-dialogs:core:0.8.6.1
   > Could not find com.android.support:appcompat-v7:25.1.0.
     Required by:
         project : > com.afollestad.material-dialogs:core:0.8.6.1 > me.zhanghai.android.materialprogressbar:library:1.1.6
   > Could not find com.android.support:support-annotations:24.0.0.
     Required by:
         project : > com.afollestad.material-dialogs:core:0.8.6.1 > me.zhanghai.android.materialprogressbar:library:1.1.6

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 20 mins 27.879 secs
Android_GUI/CMakeFiles/apk.dir/build.make:57: recipe for target 'Android_GUI/CMakeFiles/apk' failed
make[3]: *** [Android_GUI/CMakeFiles/apk] Error 1
CMakeFiles/Makefile2:709: recipe for target 'Android_GUI/CMakeFiles/apk.dir/all' failed
make[2]: *** [Android_GUI/CMakeFiles/apk.dir/all] Error 2
CMakeFiles/Makefile2:716: recipe for target 'Android_GUI/CMakeFiles/apk.dir/rule' failed
make[1]: *** [Android_GUI/CMakeFiles/apk.dir/rule] Error 2
Makefile:299: recipe for target 'apk' failed
make: *** [apk] Error 2
dhruv@dhruv-System-Product-Name ~/Desktop/DualBootPatcher/build $

**Comment by dg28gadhavi** [comment]
Solved downloaded Android repositories from sdk manager
