### ISSUE TITLE
Can not boot extsd-slot ROMS

### ISSUE THREAD

**Issue by webmaster33** [chenxiaolong/DualBootPatcher#375]
Can not boot extsd-slot ROMS, however they were successfully flashed.
Using Samsung Galaxy S4 i9505 and DBP v9.1.0.r136.ge​7995287.

1) Just flashed patched [ROM][7.1.1_r9] Resurrection Remix N v5.8.0-20170109 for jfltexx to extsd successfully. 
It took about 7 minutes to flash.
 
Then immediately flashed patched opengapps nano v7.1.1.
 
Updated ramdisk, rebooted, but after some vibrations, I was taken into TWRP recovery. 

2) Next flash was just the ROM. 
Then updated ramdisk and reboot. 
Still 5 vibration and TWRP recovery. 

Logs attached. 

I found the following external sd relevant log information in kmsg.log file:
```
[   12.435272] mblog: 1 fstab entries for the external SD
[   12.435394] mblog: [Attempt 1/10] Finding and mounting external SD
[   12.435607] mblog: Matching devices against pattern: /devices/platform/msm_sdcc.2/mmc_host/mmc2*
[   13.163726] [SSP] Updated 88487 bytes / 107440 bytes
[   13.340209] synaptics_rmi4_i2c 3-0020: synaptics_init_power_on: until lcd does not turn on.
[   13.435913] mblog: [Attempt 2/10] Finding and mounting external SD
[   13.436035] mblog: Matching devices against pattern: /devices/platform/msm_sdcc.2/mmc_host/mmc2*
[   13.924163] max77693-muic max77693-muic: func:max77693_muic_usb_detect info->muic_data->sw_path:0
[   14.197753] [SSP] Updated 103374 bytes / 107440 bytes
[   14.349060] synaptics_rmi4_i2c 3-0020: synaptics_init_power_on: until lcd does not turn on.
[   14.436370] mblog: [Attempt 3/10] Finding and mounting external SD
[   14.436553] mblog: Matching devices against pattern: /devices/platform/msm_sdcc.2/mmc_host/mmc2*
[   14.957031] [SSP] Firmware download is success.(107440 bytes)
[   15.080261] [SSP]: debug_work_func(0) - Sensor state: 0x0, RC: 0, MS: 0
[   15.080383] [SSP] : debug_work_func firmware downloading state = 3
[   15.340240] synaptics_rmi4_i2c 3-0020: synaptics_init_power_on: until lcd does not turn on.
[   15.436828] mblog: [Attempt 4/10] Finding and mounting external SD
[   15.436950] mblog: Matching devices against pattern: /devices/platform/msm_sdcc.2/mmc_host/mmc2*
[   16.340209] synaptics_rmi4_i2c 3-0020: synaptics_init_power_on: until lcd does not turn on.
[   16.437255] mblog: [Attempt 5/10] Finding and mounting external SD
[   16.437377] mblog: Matching devices against pattern: /devices/platform/msm_sdcc.2/mmc_host/mmc2*
[   17.340209] synaptics_rmi4_i2c 3-0020: synaptics_init_power_on: until lcd does not turn on.
[   17.437683] mblog: [Attempt 6/10] Finding and mounting external SD
[   17.437866] mblog: Matching devices against pattern: /devices/platform/msm_sdcc.2/mmc_host/mmc2*
[   17.960235] [SSP] forced_to_download_binary, DL state = 4
[   17.962554] [SSP] MCU device ID = 85, reading ID = 85
[   17.962707] [SSP] Sensor Posision A : 3, G : 3, M: 5, P: 0
[   17.963592] ssp_enable, enable = 1, old enable = 1
[   17.964355] [SSP]: Proximity Threshold - 0, 0
[   17.964874] [SSP]: set_hw_offset: x: 0, y: 0, z: 0
[   17.964965] ssp_sensorhub_report_notice: reset
[   17.965057] [SSP] forced_to_download_binary, DL state = 5
[   17.965698] [SSP] MCU Firm Rev : New = 14111200
[   18.340240] synaptics_rmi4_i2c 3-0020: synaptics_init_power_on: until lcd does not turn on.
[   18.438110] mblog: [Attempt 7/10] Finding and mounting external SD
[   18.438293] mblog: Matching devices against pattern: /devices/platform/msm_sdcc.2/mmc_host/mmc2*
[   19.340240] synaptics_rmi4_i2c 3-0020: synaptics_init_power_on: until lcd does not turn on.
[   19.438537] mblog: [Attempt 8/10] Finding and mounting external SD
[   19.438720] mblog: Matching devices against pattern: /devices/platform/msm_sdcc.2/mmc_host/mmc2*
[   20.340240] synaptics_rmi4_i2c 3-0020: synaptics_init_power_on: until lcd does not turn on.
[   20.438964] mblog: [Attempt 9/10] Finding and mounting external SD
[   20.439147] mblog: Matching devices against pattern: /devices/platform/msm_sdcc.2/mmc_host/mmc2*
[   21.340240] synaptics_rmi4_i2c 3-0020: synaptics_init_power_on: until lcd does not turn on.
[   21.439392] mblog: [Attempt 10/10] Finding and mounting external SD
[   21.439575] mblog: Matching devices against pattern: /devices/platform/msm_sdcc.2/mmc_host/mmc2*
[   21.439788] mblog: Failed to mount /raw/extsd
[   21.439910] mblog: Failed to mount fstab

```

Note the "Failed to mount /raw/extsd" line after 10 attempts. 
I think this is a bug available since about 2016 November or earlier. 
@chenxiaolong : could you check this issue? 

3) Next flash was  [ROM][6.0.1_r66] Resurrection Remix M v5.7.4-20160930, but same result. 
Log attached.

[19700101.020027.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/721177/19700101.020027.tar.gz)
[19700101.020031.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/721176/19700101.020031.tar.gz)
[19700101.020038.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/721178/19700101.020038.tar.gz)

**Comment by webmaster33** [comment]
I think this is a bug available since about 2016 November or December. 

See this line:
[ 17.437866] mblog: Matching devices against pattern: /devices/platform/msm_sdcc.2/mmc_host/mmc2*

1) I found the following path:
/sys/devices/platform/msm_sdcc.2/mmc_host/mmc2
But if this external sdcard path exists, why DBP didn't match the 
/devices/platform/msm_sdcc.2/mmc_host/mmc2*
pattern in it? 

2) Strange, that when I look into directory /sys/devices/platform/ I see the following sd devices:
```
root@jflte:/sys # ls -la /sys/devices/platform/ | grep msm_sd
drwxr-xr-x root     root              2017-01-21 12:57 msm_sdcc.1
drwxr-xr-x root     root              2017-01-21 12:57 msm_sdcc.2
drwxr-xr-x root     root              2017-01-21 12:11 msm_sdcc.3
```

3) Also, when I check /system/etc/vold.fstab I see the following:
[CODE]root@jflte:/system # cat /system/etc/vold.fstab
# ...
dev_mount sdcard /storage/sdcard1 auto /devices/platform/msm_sdcc.3/mmc_host[/CODE]

The question is, shouldn't DBP want to mount 
/devices/platform/msm_sdcc.3/mmc_host/mmc1*
instead 
/devices/platform/msm_sdcc.2/mmc_host/mmc2*
???

**Comment by webmaster33** [comment]
/fstab.qcom file and boot.img attached. 

[fstab.qcom.txt](https://github.com/chenxiaolong/DualBootPatcher/files/741186/fstab.qcom.txt)


[extsd-slot-rr574.zip](https://github.com/chenxiaolong/DualBootPatcher/files/741182/extsd-slot-rr574.zip)

**Comment by chenxiaolong** [comment]
I will test this on my S4 (jfltetmo), but I believe I've found the issue. In the fstab file you attached, there are multiple paths specified:

```
/devices/platform/msm_sdcc.2/mmc_host/mmc2,/devices/platform/msm_sdcc.3/mmc_host/mmc1        auto                    vfat    default      voldmanaged=extSdCard:auto,noemulatedsd
```

My code for handling multiple paths is incorrect (https://github.com/chenxiaolong/DualBootPatcher/blob/2cb576d4147278c5cee6bc2c6771434122335206/mbtool/mount_fstab.cpp#L530).

Currently, it will only try mounting the next path if the previous one does not exist. In this case, `/devices/platform/msm_sdcc.2/mmc_host/mmc2` exists, so it will **not** try `/devices/platform/msm_sdcc.3/mmc_host/mmc1`.

This is definitely a bug and I will fix it tonight.

**Comment by chenxiaolong** [comment]
@webmaster33 Can you give the test build here a try and see if it works? https://github.com/chenxiaolong/DualBootPatcher/pull/385

RR can't boot on my jfltetmo probably because of the old bootloader, so I can't test it myself.

**Comment by webmaster33** [comment]
Unfortunately, still doesn't boot on jfltexx. 
Logs attached. 
[19700101.020028.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/744134/19700101.020028.tar.gz)

**Comment by webmaster33** [comment]
Still doesn't boot. 5 vibrations. 
The 10 attempts are done, but external sdcard is not found.

**Comment by webmaster33** [comment]
I see the following:
https://github.com/chenxiaolong/DualBootPatcher/blob/4626226abffe06362873a5a1faff9d412d4b0159/mbtool/mount_fstab.cpp

Around line 529 the code is following:
```
            // Match sysfs path pattern
            for (const std::string &pattern : patterns) {
                LOGD("Matching devices against pattern: %s", pattern.c_str());

                for (auto const &pair : devices_map) {
                    const BlockDevInfo &info = pair.second;

                    if (path_matches(pair.first.c_str(), pattern.c_str())
                            && info.partition_num == 1) {
                        LOGV("Matched external SD block dev: "
                             "major=%d; minor=%d; name=%s; number=%d; path=%s",
                             info.major, info.minor, info.partition_name.c_str(),
                             info.partition_num, info.path.c_str());

                        if (try_extsd_mount(info.path.c_str(), mount_point)) {
                            return true;
                        }
                    }
                }

```

The change was affecting "if (try_extsd_mount(info.path.c_str(), mount_point))", but it will never executed, because it is within the "if (path_matches(pair.first.c_str(), pattern.c_str()) && info.partition_num == 1)" block, which doesn't match, because I don't find the "Matched external SD block dev:" string in logs.

I don't know C++ language (I'm PHP developer), nor how to fix, just seen, that likely the block, where the change was done, will be not executed.

**Comment by chenxiaolong** [comment]
I just realized you are using the Marshmallow version of RR, not the Nougat version. The MM version (`ResurrectionRemix-M-v5.7.4-20161004-jfltetmo.zip`) boots fine for me (from `extsd-slot-rr`) on the test build.

I will update this post in a little bit with a test build that logs more information.

**Comment by webmaster33** [comment]
Hmmm, I see the "unknown partition table" message. 
Strange, because external sdcard was formatted to exFAT on Windows 7. 
I also tested against surface errors.

**Comment by webmaster33** [comment]
Updated ramdisk, changed to RR rom, rebooted.
Attaching the collected logs file. 
[19700101.020045.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/747227/19700101.020045.tar.gz)

**Comment by chenxiaolong** [comment]
OK, this is good. The external SD is mounted now:

```
[   27.944396] mblog: Successfully mounted /dev/block/mmcblk1 (fuse-exfat) at /raw/extsd
```

RR is actually starting to boot, but then runs into this error:

```
[   29.550659] loop: Write error at byte offset 0, length 4096.                                                                                                                                
[   29.550750] Buffer I/O error on device loop1, logical block 0                                                                                                                               
[   29.550872] lost page write due to I/O error on loop1                                                                                                                                       
[   29.550964] EXT4-fs error (device loop1): ext4_find_entry:941: inode #486: comm init: reading directory lblock 0                                                                            
[   29.551116] Aborting journal on device loop1-8.
[   29.551300] loop: Write error at byte offset 1075802112, length 4096.
[   29.551361] Buffer I/O error on device loop1, logical block 262647
[   29.551483] lost page write due to I/O error on loop1
[   29.551574] JBD2: Error -5 detected when updating journal superblock for loop1-8.
[   29.551605] loop: Write error at byte offset 1075802112, length 4096.
[   29.551605] Buffer I/O error on device loop1, logical block 262647
[   29.551635] lost page write due to I/O error on loop1
[   29.551635] JBD2: Error -5 detected when updating journal superblock for loop1-8.
...
[   29.594207] init: cannot execve('/system/bin/logd'): I/O error
[   29.594665] init: cannot execve('/system/bin/vold'): I/O error
[   30.316406] init: cannot execve('/system/bin/tzdatacheck'): I/O error
...
```

I noticed in `MultiBoot.log`, after flashing the zip, this is printed:

```
[V] e2fsck: skipping journal recoverybecause INCOMPAT_RECOVER was clear.
```

which seems to indicate that maybe `system.img` is getting corrupted. Does it make a difference if you flash from recovery?

**Comment by webmaster33** [comment]
In last version I did not reflash the rom. I don't know if it matters. 
First I will reflash from the app. 
Then if doesn't boot, I will reflash from recovery.

**Comment by chenxiaolong** [comment]
Thanks. I posted a new test build at https://github.com/chenxiaolong/DualBootPatcher/pull/385 that contains a newer exFAT driver. I don't know if it will make a difference.

**Comment by webmaster33** [comment]
Repatched the rom, reflashed in app (version before driver update). Took less than 10 minutes. Rebooted but got into TWRP recovery. Will post logs later. 

Then wipe, and reflashed from recovery. 
Flashing is doing since about 6 hours. Usually takes about 6-7 hours to finish. Will post logs of both flash. 

Then I will have to test your new exFAT driver. Should I test with both in app & recovery flashing?

**Comment by webmaster33** [comment]
1) flashing in app took about 7-10 minutes 
Log:
[19700101.020040.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/749830/19700101.020040.tar.gz)

2) flashing from recovery took 9 hours, 11 minutes
Log: 
[19700101.020121.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/749831/19700101.020121.tar.gz)
After reboot both are arriving into recovery. 

These did not contain the updated exFAT driver. 
Next will be the updated version.

**Comment by webmaster33** [comment]
Flashing the new version with updated exFAT driver (r157) :
1) In app flashing took 5 minutes 26 seconds

**Comment by webmaster33** [comment]
Flashing the new version (r158) :

In app flashing took 1 minutes 59 seconds
EDIT1: After reboot, ended with recovery. 
Did not find the external sdcard after 10 attempts. 

Log:
[19700101.020030.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/756840/19700101.020030.tar.gz)

**Comment by webmaster33** [comment]
I just noticed, that the reason, why r158 did not work is, that the changes of the 
because the pull request "mbtool: mount_fstab.cpp: Try next vold pattern if first existing pattern fails to mount #385" (branch fstab-pattern-fail-fix) was not merged. 

So I have to go back to test build #385.

**Comment by webmaster33** [comment]
@chenxiaolong: would you have some spare time to check this issue?

I would not want to disturb you, if you are occupied.

**Comment by webmaster33** [comment]
@chenxiaolong: it seems I located the problem. 
If the 64GB external card is formatted to exFAT, then will Dual Boot Patcher will not boot it. 

If I format the external sdcard to FAT32, then it can boot correctly from external sdcard. 
It seems there is a problem with the exFAT driver or kernel has no exFAT support compiled into. 

How could be possible to fix this?

**Comment by webmaster33** [comment]
When used the r157 with updated fuse exFAT 1.2.6 driver, I see the following errors in the log:
```

[   40.231262] mblog: Assigning /raw/extsd/multiboot/extsd-slot-rr574/system.img to loop device /dev/block/loop1
[   40.272338] EXT4-fs (loop1): mounted filesystem with ordered data mode. Opts: 
[   40.512237] mblog: Assigning /raw/extsd/multiboot/extsd-slot-rr574/system.img to loop device /dev/block/loop2
[   40.513977] EXT4-fs (loop2): recovery complete
[   40.514068] EXT4-fs (loop2): mounted filesystem with ordered data mode. Opts: 
[   40.560974] mblog: /system/bin/fsck_msdos: SELinux label is: u:object_r:fsck_exec:s0
[   40.561157] mblog: Failed to bind mount /wrapped/fsck_msdos to /system/bin/fsck_msdos: Invalid argument
[   40.563171] mblog: /system/bin/fsck_msdos_mtk: Failed to stat: No such file or directory
[   40.565216] mblog: /system/bin/fsck.exfat: SELinux label is: u:object_r:fsck_exec:s0
[   40.565429] mblog: Failed to bind mount /wrapped/fsck.exfat to /system/bin/fsck.exfat: Invalid argument
[   40.566711] mblog: /system/bin/mount.exfat: SELinux label is: u:object_r:system_file:s0
[   40.566894] mblog: Failed to bind mount /wrapped/mount.exfat to /system/bin/mount.exfat: Invalid argument
[   40.567077] mblog: /wrapped: Failed to remount read-only: Invalid argument
```


Why was the 
```
Failed to bind mount /wrapped/fsck.exfat to /system/bin/fsck.exfat: Invalid argument
```
error happen? 
Might be related to the booting problem? 
Or is it an exFAT driver problem?

**Comment by webmaster33** [comment]
I will test exFAT sdcard format, if it works fine with the new release.

**Comment by webmaster33** [comment]
Unfortunately latest DBP r233 still can not boot from external sdcard, if formatted to exFAT. 
Just 5 vibrations and reboots to recovery. 

Flashed logs. 
Will post soon.

**Comment by webmaster33** [comment]
In the meantime, please read my discussion with the developer of exFAT driver here:
https://github.com/relan/exfat/issues/52

The developer suggested to add some debugging code to the exFAT driver:
In libexfat/log.c:

replace vsyslog(LOG_ERR, format, aq); with __android_log_vprint(ANDROID_LOG_ERROR, "exfat", fmt, aq);
add #include <android/log.h>

Could you add it?

**Comment by webmaster33** [comment]
Attaching log.
[20170328.084614.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/875439/20170328.084614.tar.gz)
I see the following in /multiboot/sdcard/logs/kmsg.log:
```
<3>[    9.297454] mblog: 1 fstab entries for the external SD
<3>[    9.297576] mblog: [Attempt 1/10] Finding and mounting external SD
<3>[    9.297790] mblog: Matching devices against pattern: /devices/platform/msm_sdcc.2/mmc_host/mmc2*
<3>[    9.301574] mblog: /default.prop contains fuse-exfat override: false
<6>[    9.312347] synaptics_rmi4_i2c 3-0020: synaptics_init_power_on: until lcd does not turn on.
<3>[    9.391937] mblog: Using fuse-exfat: 0
<3>[    9.392089] mblog: Failed to mount /dev/block/mmcblk1p1 (exfat) at /raw/extsd: No such device
<3>[    9.395996] mblog: /default.prop contains fuse-exfat override: false
<3>[    9.482238] FAT-fs (mmcblk1): invalid media value (0x01)
<6>[    9.482330] FAT-fs (mmcblk1): Can't find a valid FAT filesystem
<3>[    9.482757] mblog: Failed to mount /dev/block/mmcblk1 (vfat) at /raw/extsd: Invalid argument
<6>[   10.312316] synaptics_rmi4_i2c 3-0020: synaptics_init_power_on: until lcd does not turn on.
<3>[   10.483032] mblog: [Attempt 2/10] Finding and mounting external SD
<3>[   10.483215] mblog: Matching devices against pattern: /devices/platform/msm_sdcc.2/mmc_host/mmc2*
<3>[   10.486938] mblog: /default.prop contains fuse-exfat override: false
<3>[   10.577423] mblog: Using fuse-exfat: 0
<3>[   10.577606] mblog: Failed to mount /dev/block/mmcblk1p1 (exfat) at /raw/extsd: No such device
<3>[   10.581420] mblog: /default.prop contains fuse-exfat override: false
<3>[   10.667724] FAT-fs (mmcblk1): invalid media value (0x01)
<6>[   10.667816] FAT-fs (mmcblk1): Can't find a valid FAT filesystem
<3>[   10.668151] mblog: Failed to mount /dev/block/mmcblk1 (vfat) at /raw/extsd: Invalid argument
<6>[   10.912353] max77693-muic max77693-muic: func:max77693_muic_usb_detect info->muic_data->sw_path:0
<6>[   11.312316] synaptics_rmi4_i2c 3-0020: synaptics_init_power_on: until lcd does not turn on. 
```

**Comment by Simon1511** [comment]
I know this issue is old, but did you fixed it? Im getting the same error, but Im not able to boot from sd card at all.
It doesnt matter if Im using FAT32 or exFat, result is the same (system.img isnt extracted)
