### ISSUE TITLE
Updating the ramdisk for non-currently booted ROM does not update boot.img sha512sums

### ISSUE THREAD

**Issue by chenxiaolong** [chenxiaolong/DualBootPatcher#38]
We'll need an additional RPC call in the mbtool daemon for updating the checksums.

**Comment by webmaster33** [comment]
Was it fixed?

**Comment by hankching** [comment]
@chenxiaolong 
How about this issue?
Add two missing components as follows:
ro.patcher.device (even on current ROM)
ro.patcher.use_fuse_exfat (only for non-current ROM)

Thanks in advanced.

**Comment by hankching** [comment]
@chenxiaoling
I don't understand what SET KERNEL doing.

I have tried to run update ramdisk and then set kernel, I found sha512sums is correct and ro.patcher.device and ro.patcher.use_fuse_exfat are correct too. At the same time, ROMID is changed to another location.

**Comment by chenxiaolong** [comment]
Set kernel copies the boot partition to `/sdcard/MultiBoot/[ROM ID]/boot.img` and that's it. The ROM ID will be incorrect if you update the ramdisk and the set the kernel.

For example:

1. Boot into primary ROM. (/dev/block/.../boot is primary boot.img)
2. Update ramdisk for secondary ROM. (/dev/block/.../boot is still primary boot.img)
3. Set kernel for secondary ROM. This copies /dev/block/.../boot to /sdcard/MultiBoot/dual/boot.img. Now /sdcard/MultiBoot/dual/boot.img becomes the primary ROM's boot.img, causing incorrect ROM ID.

**Comment by hankching** [comment]
@chenxiaolong 
Which means boot.img is same as current one.
The function only for someone needs to boot the same OS at the different slot. MAYBE change set kernel to copy boot partition.
For current ROM, it needs because the boot.img accidentally deleted but for non-current ROM is misleading.
I prefer disable set kernel for non-current ROM.

Anyway, Thank you for replying me.

**Comment by chenxiaolong** [comment]
@hankching

> I prefer disable set kernel for non-current ROM.

100% agree. This will be done for version 9.0.0

**Comment by hankching** [comment]
Thanks

When you enhance update ramdisk, it can help someone accidentally deleted boot.img to recover.
I tried to copy unmodified (ie no patched boot.img) to > /sdcard/MultiBoot/[ROM ID]/boot.img, the image only misses updatimg default.prop and sha512sums. Therefore, it is a simple way to recover system when only missing kernel.

Thank you for your work. That awesome program.

**Comment by webmaster33** [comment]
Descriptions about doing ramdisk & kernel updates misses the information, if it can be updated from current rom or needs to be restarted to be able to update it correctly. A help feature & detailed descriptions would help this situation.

**Comment by Caio99BR** [comment]
Could be moved to Milestone 10

**Comment by chenxiaolong** [comment]
Closing. This was fixed by #450, which turned ramdisk updates into flashing an empty zip (and thus, updating the checksums correctly).

**Comment by Caio99BR** [comment]
Ok :)
