### ISSUE TITLE
[Request]skip verification in in app recovery

### ISSUE THREAD

**Issue by TheScarastic** [chenxiaolong/DualBootPatcher#41]
@chenxiaolong can u please skip the verification of cm.Verify_trustzone and  ro.build.date.utc from in app recovery. it causes very hassles to  users as they have to manually remove these lines to dualboot another rom

Thanking in Advance

**Comment by chenxiaolong** [comment]
No, I will not remove any safety features from the ROM's installer. However, I might be able to change the installation environment such that those two functions can complete successfully. Can you post a link to the zip/ROM that you're trying to flash?

**Comment by TheScarastic** [comment]
@chenxiaolong these are the lines 

https://github.com/AOSParadox/android_build/blob/812ef3094820430902d810fdadc814dbf4d8e1fd/tools/releasetools/edify_generator.py#L113 
 
this causes a issue as primary rom may be newer then the secondary rom which user want to flash and this aborts the installation

https://github.com/YUMarshmallow/android_device_yu_yu-8939-common/commit/c9610c02fe24f717af9d027f5bdedfffa22f7a80

and this one as trustzone never matches from primary and secondry rom so users have to manually edit updater script to remove these lines so it would be really helpful if you get a solution for them ;)

**Comment by chenxiaolong** [comment]
Ah, the tz issue should be pretty easy to solve. I just need to allow access to `/dev/block/platform/7824900.sdhci/by-name/tz`. As for the `ro.build.date.utc` issue, are you sure it's not failing because the recovery is too new. As far as I know, the recovery does not load /system/build.prop and the value is set to the build date of the recovery image.

```
chenxiaolong@cxl-4270cto ~ » adb shell
~ # cat /default.prop | grep ro.build.date.utc
ro.build.date.utc=1435235607
~ # getprop ro.build.date.utc
1435235607
```

Does the issue only occur when using in-app flashing? In that case, `ro.build.date.utc` would indeed be the build date of the ROM.

**Comment by chenxiaolong** [comment]
Once I finish implementing #45, I believe the `ro.build.date.utc` issue will be fixed.

**Comment by TheScarastic** [comment]
@chenxiaolong yes i am using custom build of it :)

**Comment by chenxiaolong** [comment]
@TheScarastic `9801105d6a43f09f1b39d050f1e0d4b369f60b04` (8.0.0.r2118.g9801105) should fix the `ro.build.date.utc` issue. mbtool will no longer copy the system properties to the installation environment. It will read the ones from recovery (`/default.prop`).

As far the the trustzone partition issue, adding the following line to the device specification should be enough:

```
device->setExtraBlockDevs({ "/dev/block/platform/7824900.sdhci/by-name/tz" });
```

**Comment by TheScarastic** [comment]
@chenxiaolong thanks will check and report you back :)

**Comment by Caio99BR** [comment]
You broken the installation in unified devices (with fix for issue #45), this not is writed to *.prop files, this only get via getprop.
The log: 
[MultiBoot.txt](https://github.com/chenxiaolong/DualBootPatcher/files/93475/MultiBoot.txt)

**Comment by chenxiaolong** [comment]
@Caio99BR 07373f6414bdbdc7d4868de013c1934a0748871d should fix that issue. If `ro.product.device` and `ro.build.product` do not exist in the properties files, it will be copied from the running system.

**Comment by Caio99BR** [comment]
Oh thanks!!
