### ISSUE TITLE
[Bug]Windows Application

### ISSUE THREAD

**Issue by TehMerkMods** [chenxiaolong/DualBootPatcher#417]
The windows application just does not work for me
Windows 10
http://i.imgur.com/rDCruQe.png

**Comment by superyu2010** [comment]
yes ,but also for win7 , lack of libnettle-6-1.dll file

**Comment by Garry050** [comment]
me too. Please fix it or stop build useless win32 DBP

**Comment by chenxiaolong** [comment]
This is fixed in the latest version.
