### ISSUE TITLE
Add support for OnePlus 3T

### ISSUE THREAD

**Issue by timocapa** [chenxiaolong/DualBootPatcher#422]
If I'm not wrong, partition tables etc should all be the same as they're basically the same device, just slightly updated.

**Comment by Glove007** [comment]
Hello timocapa, I already ported DualBootPatcher to the OnePlus 3T: [https://forum.xda-developers.com/oneplus-3t/themes/port-dualbootpatcher-multiboot-oneplus-t3567692](https://forum.xda-developers.com/oneplus-3t/themes/port-dualbootpatcher-multiboot-oneplus-t3567692)
