### ISSUE TITLE
Please add support for Lenovo A6000

### ISSUE THREAD

**Issue by unknownbaka** [chenxiaolong/DualBootPatcher#467]
- name: Lenovo A6000
  id: a6000
  codenames:
    - a6000
    - wt86518
  architecture: armeabi-v7a

  block_devs:
    base_dirs:
      - /dev/block/platform/soc.0/7824900.sdhci/by-name
      - /dev/block/bootdevice/by-name
    system:
      - /dev/block/platform/soc.0/7824900.sdhci/by-name/system
      - /dev/block/bootdevice/by-name/system
      - /dev/block/mmcblk0p23
    cache:
      - /dev/block/platform/soc.0/7824900.sdhci/by-name/cache
      - /dev/block/bootdevice/by-name/cache
      - /dev/block/mmcblk0p25
    data:
      - /dev/block/platform/soc.0/7824900.sdhci/by-name/userdata
      - /dev/block/bootdevice/by-name/userdata
      - /dev/block/mmcblk0p30
    boot:
      - /dev/block/platform/soc.0/7824900.sdhci/by-name/boot
      - /dev/block/bootdevice/by-name/boot
      - /dev/block/mmcblk0p22
    recovery:
      - /dev/block/platform/soc.0/7824900.sdhci/by-name/recovery
      - /dev/block/bootdevice/by-name/recovery
      - /dev/block/mmcblk0p26

**Comment by DroidThug** [comment]
PR this, it'll do
