### ISSUE TITLE
.exe not working what so ever?

### ISSUE THREAD

**Issue by TehMerkMods** [chenxiaolong/DualBootPatcher#489]
This seems to be an issue that's been running for a while

Screenies here...
http://i.imgur.com/OBLIQ1y.png
and when i fix this issue i get this

http://i.imgur.com/diolXv8.png

another error by installing QTCreator and QT Libraries placed exe in QT's bin folder

http://i.imgur.com/0tNqbyA.png

**Comment by SkiFire13** [comment]
Same problem here.
I get the error with older versions too (tried all versions from 9.1.0.r247.gf21ecf84)

**Comment by chenxiaolong** [comment]
This is fixed in the latest version.
