### ISSUE TITLE
Dual boot utilities wrong device

### ISSUE THREAD

**Issue by wajdidhc** [chenxiaolong/DualBootPatcher#49]
When I flash utilities in recovery it thinks my device is klte when it is k3g

**Comment by chenxiaolong** [comment]
Could you post a link to the recovery image you're using? The utilities zip doesn't do any device detection. It simply uses what the recovery reports as the device.

**Comment by hankching** [comment]
Confirmed that recovery is wrongly showed because of ro.product.device.

@chenxiaolong
Pls close it.
