### ISSUE TITLE
update-script

### ISSUE THREAD

**Issue by TugaPowerROM** [chenxiaolong/DualBootPatcher#51]
If the updater-script have some lines relative to firmware check partition it will fail the installation.
It cannot detect the firmware partition corrected so it will fail the installation and stop when flashing.

http://pastebin.com/1c2duMtW

**Comment by chenxiaolong** [comment]
@TugaPowerROM Which device do you have? Direct access to partitions must be manually allowed in the device specification. Eg.: https://github.com/chenxiaolong/DualBootPatcher/blob/master/libmbp/devices/nexus.cpp#L54

```
    device->setExtraBlockDevs({ QCOM_ABOOT, QCOM_IMGDATA, QCOM_MISC, QCOM_MODEM,
                                QCOM_RPM, QCOM_SBL1, QCOM_SDI, QCOM_TZ });
```

**Comment by TugaPowerROM** [comment]
Using OnePlus One, its missing a bunch of then over the oneplus.cpp

Here the partitions over this device for firmware check:


> LOGO -> /dev/block/mmcblk0p22
aboot -> /dev/block/mmcblk0p5
dbi -> /dev/block/mmcblk0p3
modem -> /dev/block/mmcblk0p1
oppostanvbk -> /dev/block/mmcblk0p13
reserve4 -> /dev/block/mmcblk0p27
rpm -> /dev/block/mmcblk0p6
sbl1 -> /dev/block/mmcblk0p2
tz -> /dev/block/mmcblk0p8


Hope it helps...

**Comment by chenxiaolong** [comment]
Holy cow, that's a lot it needs to access. I've added all of those in commit 6b20dff6ebf9beeb609dc505d331c767e880bc71 (build 8.0.0.r2132.g6b20dff)

Please let me know if it fixes the issue.

**Comment by TugaPowerROM** [comment]
Perfect

![2016-01-19 20 53 50](https://cloud.githubusercontent.com/assets/9769460/12431827/f9844fbc-bef7-11e5-9e0a-473b7ef5dd0a.png)

Thanks for the fast update
