### ISSUE TITLE
dualboot not patching in oneplus two

### ISSUE THREAD

**Issue by ciupanezul** [chenxiaolong/DualBootPatcher#53]
Hello, 
When i try to enter the menu for patching zip file it browses the zip file instead of selecting it. The same thing happens when I try to go in the rom page and push the Add button. Every time it is supposed to select a zip file instead it enters it.

**Comment by ciupanezul** [comment]
I have also tried it with older Oxygen OS (2.0.1 - being the oldest) . same thing happens

**Comment by chenxiaolong** [comment]
That is the fault of OxygenOS. They probably added the ability to view the contents zip files, but forgot to disable it when opening files.

With that said, please try patching using this debug build (but don't flash anything preduced by it) https://snapshots.noobdev.io/misc/GitHub/Issue53/Android_GUI-debug.apk I've simply removed the filter for zip files, so the file browser will show all files.

**Comment by ciupanezul** [comment]
Hi chenxiaolong,
I have installed this build but It also enters zip. I am using an older version from December, that allows me to use strong explorer. If you need me to run more tests just email me. Why not allowing other browsers?
George
On Jan 22, 2016 03:35, Andrew Gunnerson <notifications@github.com> wrote:That is the fault of OxygenOS. They probably added the ability to view the contents zip files, but forgot to disable it when opening files.

With that said, please try patching using this debug build (but don't flash anything preduced by it) https://snapshots.noobdev.io/misc/GitHub/Issue53/Android_GUI-debug.apk I've simply removed the filter for zip files, so the file browser will show all files.

**Comment by ciupanezul** [comment]
Hey. Another one: if I try to make another system with cm 13 it is not working and in the log I could observe the following lines
] Copied /dev/block/mmcblk0p36 to the chroot [D] Symlinked /mb/system.img to /chroot//dev/block/platform/f9824900.sdhci/by-name/system in the chroot [D] Symlinked /mb/system.img to /chroot//dev/block/bootdevice/by-name/system in the chroot [D] Symlinked /mb/system.img to /chroot//dev/block/mmcblk0p42 in the chroot
Why double slashes? Is it correct?
George
On Jan 22, 2016 03:35, Andrew Gunnerson <notifications@github.com> wrote:That is the fault of OxygenOS. They probably added the ability to view the contents zip files, but forgot to disable it when opening files.

With that said, please try patching using this debug build (but don't flash anything preduced by it) https://snapshots.noobdev.io/misc/GitHub/Issue53/Android_GUI-debug.apk I've simply removed the filter for zip files, so the file browser will show all files.

**Comment by chenxiaolong** [comment]
@ciupanezul I had to switch to using Android's Storage Access Framework (http://developer.android.com/guide/topics/providers/document-provider.html) because starting from Lollipop, it is the only way to write to an external SD card without root. Could you send me your build.prop file? I could add a simple check for OxygenOS so it uses the old file selection method.

**Comment by ciupanezul** [comment]
#
#
#
#
# autogenerated by oem_buildinfo.sh
ro.build.oemfingerprint=5.1.1/LMY47V/1436933050:user/release-keys
persist.sys.oem.region=OverSeas
ro.build.date.Ymd=151211
ro.build.date.ymd=151211
ro.build.date.YmdHM=201512111634
ro.build.product=OnePlus2
ro.common.soft=OnePlus2
ro.display.series=OnePlus 2
persist.sys.assert.panic=false
persist.oem.dump=0
persist.sys.assert.enable=false
persist.sys.cfu_auto=1
ro.build.soft.version=A.11
ro.xxversion=v0.5
ro.build.kernel.id=3.10.49-G1512111634
sys.foreground_process=android
persist.sys.timezone=Asia/Shanghai
persist.power.useautobrightadj=true
persist.sys.modem=yes
ro.frp.pst=/dev/block/bootdevice/by-name/config
vidc.debug.perf.mode=2
ro.build.ota.versionname=OnePlus2Oxygen_14_1512111634
ro.build.version.ota=OnePlus2Oxygen_14.A.11_GLO_011_1512111634
ro.build.soft.majorversion=A
# end build oem properties
persist.sys.kernel=yes
persist.sys.main=yes
persist.sys.system=yes
persist.sys.radio=yes
persist.sys.event=yes
persist.sys.crash=yes
persist.sys.qxdm=no
debug.sf.dump.primary=true
debug.sf.dump.external=true
debug.sf.dump.enable=true
debug.sf.dump=0
# begin build properties
# autogenerated by buildinfo.sh
ro.build.id=LMY47V
ro.build.version.incremental=25
ro.build.version.sdk=22
ro.build.version.codename=REL
ro.build.version.all_codenames=REL
ro.build.version.release=5.1.1
ro.build.version.security_patch= 2015-12-01
ro.build.version.base_os=
ro.build.date=Fri Dec 11 16:34:52 CST 2015
ro.build.date.utc=1449822892
ro.build.type=user
ro.build.user=OnePlus
ro.build.host=ubuntu-21
ro.build.tags=dev-keys
ro.build.flavor=OnePlus2-user
ro.product.board=msm8994
# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,
# use ro.product.cpu.abilist instead.
ro.product.cpu.abi=arm64-v8a
ro.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=arm64-v8a
ro.product.locale.language=en
ro.product.locale.region=US
ro.wifi.channels=
ro.board.platform=msm8994
# ro.build.product is obsolete; use ro.product.device
# Do not try to parse description, fingerprint, or thumbprint
ro.build.description=OnePlus2-user 5.1.1 LMY47V 25 dev-keys
ro.build.characteristics=nosdcard
# end build properties
#
# from vendor/oneplus/config/OnePlus2/system.prop
#
#
# system.prop for plutonium
#

rild.libpath=/vendor/lib64/libril-qc-qmi-1.so
rild.libargs=-d /dev/smd0
persist.rild.nitz_plmn=
persist.rild.nitz_long_ons_0=
persist.rild.nitz_long_ons_1=
persist.rild.nitz_long_ons_2=
persist.rild.nitz_long_ons_3=
persist.rild.nitz_short_ons_0=
persist.rild.nitz_short_ons_1=
persist.rild.nitz_short_ons_2=
persist.rild.nitz_short_ons_3=
ril.subscription.types=NV,RUIM
DEVICE_PROVISIONED=1
# Start in global mode
#ifndef VENDOR_EDIT
#dhj@PM, 2015/03/24, del this prop, which will be set in self-init
#ro.telephony.default_network=10
#endif /* VENDOR_EDIT */

#ifdef VENDOR_EDIT
#chenzhongping@network add for support multisim  2015-04-02
persist.radio.multisim.config=dsds
#hanqingpu@network set persist.radio.disable_flexmap to 0, as MBN auto active needed 2015-06-19
persist.radio.disable_flexmap=0
#endif  /* VENDOR_EDIT */

#ifdef VENDOR_EDIT
#wangzhicheng@network add for customize startup log to close QC-QMI  2015-05-23
persist.data.qmi.adb_logmask=0
#endif  /* VENDOR_EDIT */

debug.sf.hw=1
debug.egl.hw=1
debug.composition.type=c2d
persist.hwc.mdpcomp.enable=true
persist.mdpcomp.4k2kSplit=1
persist.hwc.mdpcomp.maxpermixer=5
persist.mdpcomp_perfhint=50
debug.mdpcomp.logs=0
persist.metadata_dynfps.disable=true
persist.hwc.ptor.enable=true
#ifdef VENDOR_EDIT
#hieu@oneplus.net, 2015/07/11, update dalvik heap
#dalvik.vm.heapsize=36m
#endif
dev.pm.dyn_samplingrate=1
persist.demo.hdmirotationlock=false

#CEC settings
ro.hdmi.device_type=4
persist.sys.hdmi.addr.playback=4

ro.hdmi.enable=true
persist.speaker.prot.enable=false
#0 is default(30 min)
persist.spkr.cal.duration=0
qcom.hw.aac.encoder=true
#
# system props for the cne module
#
persist.cne.feature=1

#system props for the MM modules

media.stagefright.enable-player=true
media.stagefright.enable-http=true
media.stagefright.enable-aac=true
media.stagefright.enable-qcp=true
media.stagefright.enable-fma2dp=true
media.stagefright.enable-scan=true
mmp.enable.3g2=true
mm.enable.smoothstreaming=true
media.aac_51_output_enabled=true

#3314291: Decimal sum after adding FLAC parser flag 131072
#37491 is decimal sum of supported codecs in AAL
#3314275 remove ASF
#3314547 add ASF 3GP
#codecs: DivX DivXHD AVI AC3 ASF AAC QCP DTS 3G2 MP2TS
#ifdef VENDOR_EDIT_FFMPEG
#lifei@OnePlus.MultiMediaService, 2015/04/27,add ffmpeg for Nuplayer mediaservice
#mm.enable.qcom_parser=3314291
#mm.enable.qcom_parser=3314275
mm.enable.qcom_parser=3314547
#endif/*VENDOR_EDIT_FFMPEG*/

# Enable AwesomePlayer stats
persist.debug.sf.statistics=1

#VENDOR_EDIT_AUDIOMIXER_PCM_24_BIT
#lifei@OnLineRD.MultiMediaService, 2015/03/23, temp Modify for support stagefright player
#lifei@OnLineRD.MultiMediaService, 2015/03/26, restore use Nuplayer for play native Music , follow google 5.0 code
media.stagefright.use-awesome=false
#end

# Print clip name being played
media.stagefright.log-uri=1

# VIDC: debug_levels
# 1:ERROR 2:HIGH 4:LOW 0:NOLOGS 7:AllLOGS
vidc.debug.level=1

# Additional i/p buffer in case of encoder DCVS
vidc.enc.dcvs.extra-buff-count=2

#
# system props for the data modules
#
ro.use_data_netmgrd=true
persist.data.netmgrd.qos.enable=true
persist.data.mode=concurrent
ro.data.large_tcp_window_size=true

#system props for time-services
persist.timed.enable=true

#
# system prop for opengles version
#
# 196608 is decimal for 0x30000 to report major/minor versions as 3/0
# 196609 is decimal for 0x30001 to report major/minor versions as 3/1
ro.opengles.version=196609

# System property for cabl guozhiming modify for close cabl
ro.qualcomm.cabl=0

#
# System props for telephony
telephony.lteOnCdmaDevice=0,0
persist.radio.rat_on=combine

#ifdef VENDOR_EDIT
#hanqingpu@Network enable MBN OTA prop, 20150530
persist.radio.start_ota_daemon=1
#endif

#
# System props for bluetooth
# System prop to turn on hfp client
bluetooth.hfp.client=1


#Simulate sdcard on /data/media
#
persist.fuse_sdcard=true

#system prop for Bluetooth SOC type
qcom.bluetooth.soc=rome

#system prop for A4WP profile support
ro.bluetooth.a4wp=true

#system prop for wipower support
ro.bluetooth.wipower=true

#
#snapdragon value add features
#
ro.qc.sdk.audio.ssr=false
##fluencetype can be "fluence" or "fluencepro" or "none"
#zhiguang.su@MultiDrv,default to use fluence for current acdb settings.
#ifndef VENDOR_EDIT
#ro.qc.sdk.audio.fluencetype=none
#else
ro.qc.sdk.audio.fluencetype=fluence
#endif

persist.audio.fluence.voicecall=true
persist.audio.fluence.voicerec=false
persist.audio.fluence.speaker=true

ro.qc.sdk.sensors.gestures=true
ro.qc.sdk.gestures.camera=false
ro.qc.sdk.camera.facialproc=false
#property to enable user to access Google WFD settings.
persist.debug.wfd.enable=1
#property to choose between virtual/external wfd display
persist.sys.wfd.virtual=0
tunnel.audio.encode = false
#enable gapless by default
audio.offload.gapless.enabled=true

#Buffer size in kbytes for compress offload playback
audio.offload.buffer.size.kb=64

#Enable offload audio video playback by default
av.offload.enable=true

#Disable 16 bit PCM offload by default
#ifdef VENDOR_EDIT
#lifei@oneplus.net 2015/09/01, slove UI block when play quanmingfeijidazhan games
audio.offload.pcm.16bit.enable=false
#endif  /* VENDOR_EDIT */

#Enable 24 bit PCM offload by default
audio.offload.pcm.24bit.enable=true

#property to enable VDS WFD solution
persist.hwc.enable_vds=1

#property for vendor specific library
ro.vendor.at_library=libqti-at.so
ro.vendor.gt_library=libqti-gt.so

#ifdef VENDOR_EDIT
#hieu@oneplus.net 2015/07/11, updated OP2 hwui properties
#hwui properties
ro.hwui.texture_cache_size=96
ro.hwui.layer_cache_size=64
ro.hwui.r_buffer_cache_size=12
ro.hwui.path_cache_size=39
ro.hwui.gradient_cache_size=1
ro.hwui.drop_shadow_cache_size=7
ro.hwui.texture_cache_flushrate=0.4
ro.hwui.text_small_cache_width=2048
ro.hwui.text_small_cache_height=2048
ro.hwui.text_large_cache_width=3072
ro.hwui.text_large_cache_height=2048
#else
#ro.hwui.texture_cache_size=72
#ro.hwui.layer_cache_size=48
#ro.hwui.r_buffer_cache_size=8
#ro.hwui.path_cache_size=32
#ro.hwui.gradient_cache_size=1
#ro.hwui.drop_shadow_cache_size=6
#ro.hwui.texture_cache_flushrate=0.4
#ro.hwui.text_small_cache_width=1024
#ro.hwui.text_small_cache_height=1024
#ro.hwui.text_large_cache_width=2048
#ro.hwui.text_large_cache_height=1024
#endif

# enable navigation bar
#ifdef VENDOR_EDIT
#liuhuisheng@framework disable navigation bar
qemu.hw.mainkeys=1
#else
#qemu.hw.mainkeys=0
#endif

#enable voice path for PCM VoIP by default
use.voice.path.for.pcm.voip=true

#selects CoreSight configuration to enable
persist.debug.coresight.config=none

#System property for FM transmitter
ro.fm.transmitter=false

#Enable property to enable ds2
audio.dolby.ds2.enabled=true

#enable property for hard bypass
audio.dolby.ds2.hardbypass=true

audio.offload.passthrough=false
audio.offload.multiple.enabled=true

#VENDOR_EDIT_AUDIOMIXER_PCM_24_BIT
#lifei@OnLineRD.MultiMediaService, 2015/01/07, Modify for support Add for 8k 16k 22.05k use HIGH_QUALITY resampler
af.resampler.quality=4

#ifdef VENDOR_EDIT
#yuzhongwen@network added to enable dpm fast dormancy 2015-7-6
persist.dpm.feature=1
#endif  /* VENDOR_EDIT */

#
# ADDITIONAL_BUILD_PROPERTIES
#
dalvik.vm.heapstartsize=8m
dalvik.vm.heapgrowthlimit=256m
dalvik.vm.heapsize=512m
dalvik.vm.heaptargetutilization=0.75
dalvik.vm.heapminfree=512k
dalvik.vm.heapmaxfree=8m
keyguard.no_require_sim=true
ro.com.android.dataroaming=true
ro.com.android.dateformat=MM-dd-yyyy
ro.carrier=unknown
ro.config.notification_sound=OnTheHunt.ogg
ro.config.alarm_alert=Alarm_Classic.ogg
ro.ril.hsxpa=1
ro.ril.gprsclass=10
ro.adb.qemud=1
ro.vendor.extension_library=libqti-perfd-client.so
persist.radio.apm_sim_not_pwdn=1
ro.setupwizard.mode=OPTIONAL
ro.com.google.gmsversion=5.1_r2
drm.service.enabled=true
ro.url.legal=http://www.google.com/intl/%s/mobile/android/basic/phone-legal.html
ro.url.legal.android_privacy=http://www.google.com/intl/%s/mobile/android/basic/privacy.html
ro.com.android.wifi-watchlist=GoogleGuest
ro.setupwizard.enterprise_mode=1
ro.com.google.clientidbase=android-oneplus
persist.sys.dalvik.vm.lib.2=libart.so
dalvik.vm.isa.arm64.features=div,needfix_835769
dalvik.vm.isa.arm.features=div
net.bt.name=Android
dalvik.vm.stack-trace-file=/data/anr/traces.txt
persist.gps.qc_nlp_in_use=1
persist.loc.nlp_name=com.qualcomm.location
ro.gps.agps_provider=1
ro.pip.gated=0

**Comment by ciupanezul** [comment]
Where do I find this file?
On Jan 23, 2016 07:55, Andrew Gunnerson <notifications@github.com> wrote:@ciupanezul I had to switch to using Android's Storage Access Framework (http://developer.android.com/guide/topics/providers/document-provider.html) because starting from Lollipop, it is the only way to write to an external SD card without root. Could you send me your build.prop file? I could add a simple check for OxygenOS so it uses the old file selection method.

**Comment by sguillon** [comment]
Hi 
i have added the build.prop from Oxygen 2.2.0 (base on 5.1.1)
PasteBin link to the file [http://pastebin.com/akNsgnMG](url)
If i can be of any help to test, will be more than happy :)

Seb

**Comment by chenxiaolong** [comment]
Should be fixed by cd5d3e9b03a6dd5ce3a33020ea190665a22842f8
