### ISSUE TITLE
[Sony] MBTool injected on TWRP

### ISSUE THREAD

**Issue by Caio99BR** [chenxiaolong/DualBootPatcher#533]
The new combined recovery ramdisk made by AdrianDC and used by default in most of sony devices in lineageos use a source built init that move original init to init.real (like DBP do) and load init after user choice, the advantage is because this file now contains keycheck, extract_ramdisk and commands need, but the problem start now.

This new scheme is not detect by DBP and since mbtool only know init.sh way and  don't know what is happening in this way, him just start, changing fstab to dual and make some operations in TWRP useless (mount/install/sdcard), basically broken TWRP.

Idk what to do, and this is a old bug, but this is annoying for me.

The custombootimg that explains new system: https://github.com/TeamVee-SS/android_device_sony_shuang/blob/cm-14.1/boot/custombootimg.mk

That's all thanks if you fix it soon :)

**Comment by chenxiaolong** [comment]
@Caio99BR I actually like this new way better :) Less work than handling the nested `sbin/ramdisk.cpio` stuff.

Can you give PR #534 a try?

**Comment by Caio99BR** [comment]
Testing :+1: 
While this you can finish a old milestone: https://github.com/chenxiaolong/DualBootPatcher/milestone/3

**Comment by chenxiaolong** [comment]
> While this you can finish a old milestone: https://github.com/chenxiaolong/DualBootPatcher/milestone/3

Done!

**Comment by Caio99BR** [comment]
You closed all :O 

Tested, but not fixed :(

**Comment by chenxiaolong** [comment]
> Tested, but not fixed issue, also I dont see any "init path" in dmesg :(

Can you post `/sdcard/MultiBoot.log`? The init path should have been logged there.

**Comment by Caio99BR** [comment]
It's fixed, I just reinstalled the ROM. The "Update Ramdisk" not worked.
Thanks, sorry for not reply before, I builded the ROM today (LineageOS14.1).

You can merge it :)

**Comment by Caio99BR** [comment]
+1 to merge

**Comment by chenxiaolong** [comment]
Merged. Thanks for testing!
