### ISSUE TITLE
mbtool does not remount /system as writable before restoring backup

### ISSUE THREAD

**Issue by chenxiaolong** [chenxiaolong/DualBootPatcher#535]

**Comment by Caio99BR** [comment]
Bump-up. The Restore feature is useless without this, and there is no workaround.

**Comment by webmaster33** [comment]
+1

**Comment by chenxiaolong** [comment]
I'll work on this today and create a test build. I don't have a phone at the moment though as I had to send in my Galaxy S8+ for replacement due to a defective screen.

**Comment by Caio99BR** [comment]
Thanks for take a look :)
PS1: Do a cleanup in already merged changes :P

**Comment by chenxiaolong** [comment]
@Caio99BR @webmaster33 Please give the test build here a try: #585
