### ISSUE TITLE
[Request]skip verification in of few more things 

### ISSUE THREAD

**Issue by TheScarastic** [chenxiaolong/DualBootPatcher#54]
Hey @chenxiaolong you know the issue of mine where mm roms were not getting flashed and after regular experimenting got the issue it was in updater-script Hope you will try to help in it :)

if is_mounted("/data") then
package_extract_file("META-INF/org/cyanogenmod/releasekey", "/tmp/releasekey");
run_program("/tmp/install/bin/otasigcheck.sh") != "31744" || abort("Can't install this package on top of incompatible data. Please try another package or run a factory reset");
else
mount("ext4", "EMMC", "/dev/block/bootdevice/by-name/userdata", "/data", "");
package_extract_file("META-INF/org/cyanogenmod/releasekey", "/tmp/releasekey");
run_program("/tmp/install/bin/otasigcheck.sh") != "31744" || abort("Can't install this package on top of incompatible data. Please try another package or run a factory reset");
unmount("/data");
endif;

Please try to solve it after removing these lines from updater-script rom gets flashed as well as boots too hoping to see a commit soon ;)

Ps:- after removing these lines [D] Child killed with signal: 11 this error also vanishes

**Comment by chenxiaolong** [comment]
@TheScarastic That's great to know!

Would you be able to pin down which exact line is causing the issue? For example, try removing just `run_program()` and see if it works, etc.

```
if is_mounted("/data") then
package_extract_file("META-INF/org/cyanogenmod/releasekey", "/tmp/releasekey");
else
mount("ext4", "EMMC", "/dev/block/bootdevice/by-name/userdata", "/data", "");
package_extract_file("META-INF/org/cyanogenmod/releasekey", "/tmp/releasekey");
unmount("/data");
endif;
```

**Comment by TheScarastic** [comment]
@chenxiaolong removing this lines also helps to flash the rom

run_program("/tmp/install/bin/otasigcheck.sh") != "31744" || abort("Can't install this package on top of incompatible data. Please try another package or run a factory reset");

So can i expect workaround now :D

**Comment by TheScarastic** [comment]
@chenxiaolong :( please see to it :'(

**Comment by Caio99BR** [comment]
Same erro

**Comment by chenxiaolong** [comment]
@Caio99BR You're ROM is also segfaulting (`[D] Child killed with signal: 11`) when installing?

**Comment by TheScarastic** [comment]
@chenxiaolong for me it goes after removing run_program line :)

**Comment by TheScarastic** [comment]
@chenxiaolong it seems u are not interested in this issue :(

**Comment by TheScarastic** [comment]
@chenxiaolong please respond :(
