### ISSUE TITLE
Random reboot while flashing secondary rom

### ISSUE THREAD

**Issue by kostoulhs** [chenxiaolong/DualBootPatcher#55]
Here chenxiaolong you can find the logs:
https://www.dropbox.com/s/hdzdatghtjlbpi7/20160123.194308.tar

**Comment by chenxiaolong** [comment]
Hmm, I'm not sure. It seems like it's rebooting when it's just simply copying files. Does it also do that when you flash the patched zip from recovery?

**Comment by kostoulhs** [comment]
I didn't test it to be honest! Is flashing from recovery possible? I have lost many episodes.. :P

**Comment by chenxiaolong** [comment]
Ah, yes, flashing the patched zip from recovery is actually the recommended way of doing it :) The in-app-flashing method is cool when it works, but sometimes there are incompatibilities with the ROM that is currently running.

**Comment by kostoulhs** [comment]
Good to know, will test when find some time. Thanks for this awesome tool ;)
BTW primary ROM was CyanogenMod 13 and secondary that I tried was CyanogenMod 11
