### ISSUE TITLE
minizip.make issue

### ISSUE THREAD

**Issue by Pablito2020** [chenxiaolong/DualBootPatcher#551]
About the computer:
Ubuntu version: 17.02
Cmake version: 3.7.2

Issue: When I'm trying to compile and every patch to the android ndk and sdk is good I have this compilation error:

`
-- Found LIBSEPOL: /home/pablito/project/DualBootPatcher/build/thirdparty/prebuilts/libsepol/7.1.1_r28-1/x86_64/include  
-- Found LZ4: /home/pablito/project/DualBootPatcher/build/thirdparty/prebuilts/lz4/131-1/x86_64/include  
-- Found LZO: /home/pablito/project/DualBootPatcher/build/thirdparty/prebuilts/lzo/2.10-1/x86_64/include  
CMake Error at cmake/dependencies/minizip.cmake:3 (add_subdirectory):
  The source directory

    /home/pablito/project/DualBootPatcher/external/minizip

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:54 (include)
  CMakeLists.txt:180 (include)

-- Found PROCPS: /home/pablito/project/DualBootPatcher/build/thirdparty/prebuilts/procps-ng/include  
-- Found SAFE_IOP: /home/pablito/project/DualBootPatcher/build/thirdparty/prebuilts/safe-iop/7.1.1_r28-1/x86_64/include  
-- Found JANSSON: /home/pablito/project/DualBootPatcher/build/thirdparty/prebuilts/jansson/2.10-1/x86_64/include  
-- NOTE: Android actually uses BoringSSL
-- Found OpenSSL: /home/pablito/project/DualBootPatcher/build/thirdparty/prebuilts/boringssl/r3955.bbfe603-1/x86_64/lib/libssl.a;/home/pablito/project/DualBootPatcher/build/thirdparty/prebuilts/boringssl/r3955.bbfe603-1/x86_64/lib/libcrypto.a  
-- Configuring incomplete, errors occurred!
See also "/home/pablito/project/DualBootPatcher/build/android/android-system_x86_64-prefix/src/android-system_x86_64-build/CMakeFiles/CMakeOutput.log".
See also "/home/pablito/project/DualBootPatcher/build/android/android-system_x86_64-prefix/src/android-system_x86_64-build/CMakeFiles/CMakeError.log".
android/CMakeFiles/android-system_x86_64.dir/build.make:105: fallo en las instrucciones para el objetivo 'android/android-system_x86_64-prefix/src/android-system_x86_64-stamp/android-system_x86_64-configure'
make[2]: *** [android/android-system_x86_64-prefix/src/android-system_x86_64-stamp/android-system_x86_64-configure] Error 1
CMakeFiles/Makefile2:1772: fallo en las instrucciones para el objetivo 'android/CMakeFiles/android-system_x86_64.dir/all'
make[1]: *** [android/CMakeFiles/android-system_x86_64.dir/all] Error 2
Makefile:160: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2
`

**Comment by chenxiaolong** [comment]
Did you grab all the submodules with this command?

```sh
git submodule update --init
```

**Comment by Pablito2020** [comment]
Yes. @chenxiaolong, now fixed. The issue now is that:
CPack: - Run preinstall target for: DualBootPatcher
CPack Error: Problem running install command: /usr/bin/cmake --build . --target "preinstall"
Please check /home/pablito/DualBootPatcher/build/_CPack_Packages/Linux/STGZ/PreinstallOutput.log for errors
CPack Error: Error when generating package: data

Sorry for all the issues... I'm still a noob in android apps compiling.
