### ISSUE TITLE
[Request] s3 neo please s3ve3g 

### ISSUE THREAD

**Issue by nikandlv** [chenxiaolong/DualBootPatcher#56]
Hi please add our device I can be tester any time , my telegram I'd : @imthemr

**Comment by nikandlv** [comment]
I successfully ported it :D

**Comment by chenxiaolong** [comment]
If you make a pull request, I will merge it :)

**Comment by nikandlv** [comment]
Hello sir in this device I faced some bugs , please help making it work for our device , if you have telegram app here's my id : 
telegram.me/imthemr 
We can easily chat there
