### ISSUE TITLE
error from dualboot patch win32 tool

### ISSUE THREAD

**Issue by mbskykill** [chenxiaolong/DualBootPatcher#569]
open it on windows 10

---------------------------
DualBootPatcher.exe - 系统错误
---------------------------
无法启动此程序，因为计算机中丢失 libnettle-6-1.dll。尝试重新安装该程序以解决此问题。 
---------------------------
确定   
---------------------------

whats the problem

**Comment by qiurigao** [comment]
我也是

**Comment by chenxiaolong** [comment]
This should be fixed in the latest version.
