### ISSUE TITLE
[Request] s3 neo please s3ve3g with a really good fast start up 

### ISSUE THREAD

**Issue by nikandlv** [chenxiaolong/DualBootPatcher#57]
Hello dev :) there are many people waiting for this device :) and I tryed to port it , and I saw its really close to moto g 2013 xt1032 so I changed my build.prop and make it like its that phone , and I opened the app add the Zip , converted it , then i select set the kernel then i installed it , and it was successful then I set that secondary ROM and rebooted everything was fine , I installed the app for the secondary ROM and changed back to my primary ROM and it booted back to first ROM :D so everything is right , but after second time booting into secondary ROM com.android.phone started stopping every two seconds and I think its SQL related here's logcat 
http://www.mediafire.com/view/69d91p9feccuq6x/Log_2016-01-26_02-39-24.txt
I hope it helps you 
Remember moto g 2013 xt1032 is close to our device
I'm ready to help and being a tester

**Comment by chenxiaolong** [comment]
The reason for that is the primary ROM probably has one of these lines in the `/init.*.rc` files:

    restorecon /data

or

    restorecon_recursive /data

When you boot into your primary ROM, the SELinux labels for all of the files in your secondary ROM will be reset. That will cause SELinux to block `com.android.phone` from accessing its own SQL databases (as you saw).

What you want to do is use the ramdisk update function for the primary ROM. This is equivalent to patching your primary ROM. The multiboot code will remove those two lines above to prevent the issue from happening :) Note that you'll probably have to wipe and reflash your secondary ROM after you do this.

**Comment by nikandlv** [comment]
Wow yayyyyy it works thank youuuu ❤❤❤

**Comment by nikandlv** [comment]
Will you add our phone ? Its working fine with these , but we cant flash some ROMs with simulating xt1032 because they made for s3 neo only , and gives this error "This package is for device: s3ve3g,s3ve3gds,s3ve3gjv; this device is xt1032.
This package is for device: s3ve3g,s3ve3gds,s3ve3gjv; this device is xt1032."
So can u add our device to app , and using same source of moto g xt1032 ??

**Comment by zeeshanhussain** [comment]
https://snapshots.noobdev.io/misc/getlogs/GetLogs-20160120.zip @nikandlv  flash and upload logs. :)

**Comment by nikandlv** [comment]
@zeeshanhussain where to flash ? Flashed and no logs , only a log named file with 0 byte in internal :(
