### ISSUE TITLE
[REQUEST] SKIP A CODE IN UPDATER-SCRIPT 

### ISSUE THREAD

**Issue by TheScarastic** [chenxiaolong/DualBootPatcher#59]
@chenxiaolong please see after removing this lines roms gets flashed perfectly so please do something for these lines  :)

`run_program("/tmp/install/bin/otasigcheck.sh") != "31744" || abort("Can't install this package on top of incompatible data. Please try another package or run a factory reset");`

**Comment by TheScarastic** [comment]
@chenxiaolong any update

**Comment by TheScarastic** [comment]
@chenxiaolong bumping the request

**Comment by hankching** [comment]
@TheScarastic 
The code protects a flash is a corrective device, therefore, no one can/should remove it, especially this app. Anyway, one can do anything one likes.

I don't agree this app doing something for that.
