### ISSUE TITLE
DualBootPatcher for Windows still not work.

### ISSUE THREAD

**Issue by Garry050** [chenxiaolong/DualBootPatcher#596]
Yes, startup error fixed. but i can't convert flashable zip.
any rom files return "Failed to read archive data for file" WTF?
<img src="https://i.ppn.pw/cc/645ca6c4/f1c892bd2.png">

**Comment by chenxiaolong** [comment]
This has finally been fixed in version 9.2.0.r197.g0c271fd (PR #632).

**Comment by Garry050** [comment]
confirmed. thx...
