### ISSUE TITLE
主系统无法正常系统更新

### ISSUE THREAD

**Issue by sun98** [chenxiaolong/DualBootPatcher#597]
主系统MIUI8，安卓7.0，副系统魔趣6.0，系统升级会重启至recovery(TWRP)页面，然后就没了，由于目前MIUI的7.0还在内测，没有卡刷包，无法更新了。

**Comment by abc0922001** [comment]
都做成補丁更新看看？

**Comment by sun98** [comment]
@abc0922001 谢谢提醒，已经解决。自带的更新包是存放在sd卡的，我可以直接用recovery刷
