### ISSUE TITLE
Patcher not working with CM13?

### ISSUE THREAD

**Issue by arvedviehweger** [chenxiaolong/DualBootPatcher#62]
I'm trying to install CM13 on my klimtlte with Dualboot. The zip flashes without any problems in recovery or the app, but it won't boot (But I know it boots). Anyone having the same issue?

**Comment by Caio99BR** [comment]
There is no "Anyone having the same issue?" you need to send logs, i already have see various dead topics saying this and no one solved nothing.
Get the logs and put then here in a .txt or .zip.

**Comment by haimann951** [comment]
[logs.zip](https://github.com/chenxiaolong/DualBootPatcher/files/140383/logs.zip)

Sorry for the late reply. Here are the logs.

**Comment by haimann951** [comment]
critical process 'lmkd' exited 4 times in 4 minutes; rebooting into recovery mode

This is the error that makes it to reboot into recovery

**Comment by chenxiaolong** [comment]
Hmm, yeah, that's definitely the issue. Are you able to make a logcat before it crashes so I can see why `lmkd` is crashing? (You might not be able to since `logd` is crashing also.)

I'm not really sure what might be causing it. The kernel log isn't too helpful in this case.

**Comment by haimann951** [comment]
I will try to get a logcat later today, but I think it won't recognize the device because it still looks like it's stuck in the bootloader.(no cm logo, but Samsung logo of bootloader)

**Comment by webmaster33** [comment]
I have no problem using patcher in CM13. Boots fine.
Using Samsung Galaxy S4 i9505.

**Comment by Caio99BR** [comment]
1 year expiration, could be closed.
