### ISSUE TITLE
Error with ndk and thirdparty files

### ISSUE THREAD

**Issue by nikandlv** [chenxiaolong/DualBootPatcher#64]
want to build a debug version . 
```
prebuilt-libmblog is using a horribly ugly ndk-build hack that will probably break in the future!
Android NDK: ERROR:/home/nikan/DualBootPatcher/build/thirdparty/Android.mk:procps-ng: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /home/nikan/DualBootPatcher/build/thirdparty/android/procps-ng/lib_armeabi-v7a/libprocps.a exists  or that its path is correct   
/home/nikan/android-ndk-r10d/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
make[2]: *** [libmbp/mbp-shared-android-prefix/src/mbp-shared-android-stamp/mbp-shared-android-build] Error 2
make[1]: *** [libmbp/CMakeFiles/mbp-shared-android.dir/all] Error 2
make: *** [all] Error 2

```
checked this and doesnt exist 
home/nikan/DualBootPatcher/build/thirdparty/android/procps-ng/lib_armeabi-v7a/libprocps.a

**Comment by nikandlv** [comment]
fixed

**Comment by chenxiaolong** [comment]
Can you try deleting `build/thirdparty/android/procps-ng`? It should automatically redownload and extract the procps-ng files.

**Comment by nikandlv** [comment]
folder is completely empty . can u upload the folder ?

**Comment by nikandlv** [comment]
all done . can i 
make apk with windows ?

**Comment by chenxiaolong** [comment]
> all done . can i 
> make apk with windows ?

No. At the moment, it is only possible to build the Android app from Linux.

**Comment by nikandlv** [comment]
OK . I have android SDK tools installed .
What are SDK tools I need to download ?
Because it says 
Android-23 not found I think ...

**Comment by chenxiaolong** [comment]
These are the packages I have installed:

![image](https://cloud.githubusercontent.com/assets/646253/13272342/53a8e76e-da69-11e5-92ad-2b5ae4f4401d.png)

**Comment by nikandlv** [comment]
OK sir thank you . I will try to get them . I will close the issue for now ;)

**Comment by nikandlv** [comment]
hello sir now i get this error 
`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Android_GUI'.
> A problem occurred configuring project ':neuteredsaf'.
   > Could not resolve all dependencies for configuration ':neuteredsaf:_debugCompile'.
      > Could not find com.android.support:support-v4:23.1.1.
        Searched in the following locations:
            https://jcenter.bintray.com/com/android/support/support-v4/23.1.1/support-v4-23.1.1.pom
            https://jcenter.bintray.com/com/android/support/support-v4/23.1.1/support-v4-23.1.1.jar
            file:/home/nikan/android-sdk-linux/extras/android/m2repository/com/android/support/support-v4/23.1.1/support-v4-23.1.1.pom
            file:/home/nikan/android-sdk-linux/extras/android/m2repository/com/android/support/support-v4/23.1.1/support-v4-23.1.1.jar
            file:/home/nikan/android-sdk-linux/extras/google/m2repository/com/android/support/support-v4/23.1.1/support-v4-23.1.1.pom
            file:/home/nikan/android-sdk-linux/extras/google/m2repository/com/android/support/support-v4/23.1.1/support-v4-23.1.1.jar
        Required by:
            Android_GUI:neuteredsaf:unspecified
      > Could not find com.android.support:appcompat-v7:23.1.1.
        Searched in the following locations:
            https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1.1/appcompat-v7-23.1.1.pom
            https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1.1/appcompat-v7-23.1.1.jar
            file:/home/nikan/android-sdk-linux/extras/android/m2repository/com/android/support/appcompat-v7/23.1.1/appcompat-v7-23.1.1.pom
            file:/home/nikan/android-sdk-linux/extras/android/m2repository/com/android/support/appcompat-v7/23.1.1/appcompat-v7-23.1.1.jar
            file:/home/nikan/android-sdk-linux/extras/google/m2repository/com/android/support/appcompat-v7/23.1.1/appcompat-v7-23.1.1.pom
            file:/home/nikan/android-sdk-linux/extras/google/m2repository/com/android/support/appcompat-v7/23.1.1/appcompat-v7-23.1.1.jar
        Required by:
            Android_GUI:neuteredsaf:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
`

**Comment by nikandlv** [comment]
support lib is installed ( 
![screenshot - -](https://cloud.githubusercontent.com/assets/14939611/13368524/666d063e-dd00-11e5-9a21-a1d1fd9c3051.png)
newer one )

**Comment by nikandlv** [comment]
if you open this link by browser

https://repo.jfrog.org/artifactory/libs-release-bintray/com/android/support/support-v4/23.1.1/support-v4-23.1.1.pom

that is requested by installtion you will face this :

`{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}`

**Comment by nikandlv** [comment]
all fixed thanks
