### ISSUE TITLE
Docker - building Linux patcher: could not find GTest

### ISSUE THREAD

**Issue by navhaxs** [chenxiaolong/DualBootPatcher#640]
First of all, @chenxiaolong your docker scripts are working great to build the Android app! Had zero issues on my Ubuntu machine.

However, building the Linux patcher has a problem (GTest?).

```
[builder@db35b473437f build]$ cmake .. -DMBP_TARGET_PLATFORM=desktop
Certificate stored in file </builder/DualBootPatcher/build/java_keystore_cert.des>
Warning: Overwriting existing alias androiddebugkey in destination keystore
-- Locking prebuilts directory: /builder/DualBootPatcher/thirdparty/prebuilts
-- Unlocking prebuilts directory: /builder/DualBootPatcher/thirdparty/prebuilts
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindGTest.cmake:200 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/dependencies/gtest.cmake:2 (find_package)
  cmake/Dependencies.cmake:22 (include)
  CMakeLists.txt:180 (include)


-- Configuring incomplete, errors occurred!
See also "/builder/DualBootPatcher/build/CMakeFiles/CMakeOutput.log".
[builder@db35b473437f build]$ 
```

As a side note, I can't get `build.sh` to work on Windows. Using cygwin bash shell + Docker for Windows, which I'm already using for other projects. I think I have a network problem with Docker for Windows since dnf is failing to connect to the internet, or in other runs the github.com host can't be found, etc. But this is only with the Fedora image; my Ubuntu containers connect to the internet fine??

**Comment by chenxiaolong** [comment]
First of all, this bug report made my day! I had no idea anyone was using those docker images.

> However, building the Linux patcher has a problem (GTest?).

Are you using the Linux-specific image for (eg. `chenxiaolong/dualbootpatcher:9.2.0-1-linux`) for building? It should have gtest installed. https://github.com/chenxiaolong/DualBootPatcher/blob/cfbba1c6eb479c43fe2ea9bcde3aab0eb7f38fd2/docker/template/Dockerfile.linux.in#L22

> As a side note, I can't get build.sh to work on Windows. Using cygwin bash shell + Docker for Windows, which I'm already using for other projects. I think I have a network problem with Docker for Windows since dnf is failing to connect to the internet, or in other runs the github.com host can't be found, etc. But this is only with the Fedora image; my Ubuntu containers connect to the internet fine??

Hmm, I'm not sure. I haven't tried Docker for Windows before. I'd suggest checking `/etc/resolv.conf` in both the Fedora and Ubuntu containers to see if the DNS servers are the same.

**Comment by navhaxs** [comment]
> Are you using the Linux-specific image for (eg. chenxiaolong/dualbootpatcher:9.2.0-1-linux) for building? It should have gtest installed.

Ah, I see! That was it, thanks. I'm quite new to Docker.
