### ISSUE TITLE
Mi6 stop when click System option

### ISSUE THREAD

**Issue by xiang473535976** [chenxiaolong/DualBootPatcher#646]
小米6安装后 能打开 但是当点击系统那个选项的时候 直接闪退 请修复哈 群里几个人都是这样的 安转的是昨天的最新版本！！

**Comment by xiang473535976** [comment]
![screenshot_2017-07-09-09-46-40-261_com miui bugre](https://user-images.githubusercontent.com/18111614/27990663-2b8aedd8-6490-11e7-9fd8-6d43122220e2.png)

**Comment by CDLLY** [comment]
The same issue is happening on Redmi note3 too.
R197 or older works well.

**Comment by abc0922001** [comment]
me too.

**Comment by yshalsager** [comment]
Try with an older version

**Comment by abc0922001** [comment]
I try R201, OK！

**Comment by chenxiaolong** [comment]
Fixed by #738.
