### ISSUE TITLE
xiaomi5 bug gemini bug

### ISSUE THREAD

**Issue by silentchild** [chenxiaolong/DualBootPatcher#648]
DualBootPatcherAndroid-9.2.0.r205.gc7e501e6-snapshot,It won't work after this version,Unable to switch to the new category

**Comment by silentchild** [comment]
hello？

**Comment by SkiFire13** [comment]
same problem here (mi5) the app crash after opening it (ROM menu)

**Comment by chenxiaolong** [comment]
Fixed by #738.
