### ISSUE TITLE
can't open the 'rom' Drawer in The App on specfic devices/roms

### ISSUE THREAD

**Issue by gcasdfghjkl** [chenxiaolong/DualBootPatcher#649]
on Oneplus 3T
mokee 7.1.2/Unofficial LOS 14.1, when using app version after 9.2.0 r205, the ROM Drawer can NOT Open and the app exit immediately.

**Comment by talkshowsonmute** [comment]
on oneplus 5
officical h2os 4th/5th edition ,supersu,9.2.0.r223/221 all exit immediately

**Comment by CyengineKiko** [comment]
On oneplus 2.
Both the stock OOS 3.6.0 and several custom roms cant open the same tab either.
r205 works fine while all versions after that would lead to FC.Should be some commits between r205 and r210 cause the FC I think.

_Sent from my OnePlus ONE A2001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ab123321** [comment]
Same on Xperia XZ, stock ROM. Opening ROMs drawer causes FileNotFoundException (/storage/emulated/0/MultiBoot/primary/config.json) that leads to libmbcommon.so segmentation fault.

**Comment by ab123321** [comment]
@chenxiaolong, according to @CyengineKiko, possible cause of issue is https://github.com/chenxiaolong/DualBootPatcher/commit/2b12b6e5fc405bb14d51c5c472ff870756c43fd7

**Comment by atxoxx** [comment]
@ab123321 seems that the creator of dualboot patcher added that commit but I still have that issue... 
Earlier build are working but doesn't support my device (m8)

**Comment by gcasdfghjkl** [comment]
I've got a FC report on Redmi 4X with RR/AEX rom too.

**Comment by Cinhi** [comment]
Same as upstairs... I should have a try to install build 240 or less

**Comment by g3mb1x** [comment]
Same here
Fatal signal on redmi note 3 rom nitrogen os with magisk

**Comment by talkshowsonmute** [comment]
using xda forum debug version is ok

**Comment by atxoxx** [comment]
@talkshowonmute any link ?

**Comment by chenxiaolong** [comment]
Fixed by #738.

**Comment by gcasdfghjkl** [comment]
THX for the fix.
