### ISSUE TITLE
Use JSON schema to validate device definitions

### ISSUE THREAD

**Issue by chenxiaolong** [chenxiaolong/DualBootPatcher#665]
There are currently quite a few device definitions that have syntactically valid, but semantically invalid. A JSON schema will help prevent that, as well as giving more meaningful messages than the current custom validator. This will require porting everything from using jansson to using RapidJSON as it's one of the few C++ libraries that supports JSON schemas.

- [x] Port libraries to use RapidJSON
- [x] Replace libmbdevice's custom validator with RapidJSON's schema validator
- [x] Create schema file for device definitions

**Comment by chenxiaolong** [comment]
libmbdevice port is complete. Just need to finish removing the jansson code so we don't depend on two JSON libraries.

**Comment by wazeeahmed** [comment]
Great news . Would you please check issue #669 . I'm having a lot of pain regarding the ramdisk update problem . Now I can't force update a ramdisk and dbp force closes .
