### ISSUE TITLE
Cannot encrypt with Lineage OS on Galaxy S7

### ISSUE THREAD

**Issue by Juul** [chenxiaolong/DualBootPatcher#666]
When I try to encrypt my device it goes to a green on black android logo line-drawing (with the android body separated into two cogs) for about a second and then straight to the Lineage OS startup animation, seemingly having rebooted.

I'm using the Lineage OS nightly from July 21st 2017 which has been patched with Dual Boot Patcher to use a data slot. I'm using Dual Boot Patcher 9.2.0.r237.g.71108409-SNAPSHOT

My primary rom is an unpatched Superman rom running the stock Nougat kernel.

This is on a Galaxy S7 flat. 

Are there any logs I can gather or anything I can do to help troubleshoot this?

**Comment by padraigdoran** [comment]
On my S7 (sm-d930f) using lineage-14.1-20170725-nightly-herolte-signed fresh install / full wipe, I cannot get encryption going. I have the exact same symptoms that you have. I don't think this is a DualBootPatcher issue.

**Comment by padraigdoran** [comment]
On my S7 (sm-d930f) using lineage-14.1-20170725-nightly-herolte-signed fresh install / full wipe, I cannot get encryption going. I have the exact same symptoms that you have. I don't think this is a DualBootPatcher issue.

**Comment by Juul** [comment]
I just tried wiping my S7 completely and installing Lineage OS alone, with no DualBootPatcher, and encryption works fine. This is definitely an issue with DualBootPatcher.

**Comment by Juul** [comment]
Alright I tried first installing Lineage OS as primary, then encrypting, then installing SuperMan as secondary. This just made my system unbootable. Is using encryption just not possible with DualBootPatcher?

**Comment by Juul** [comment]
This is what `adb logcat` says during the attempt at encrypting from within Lineage OS running as secondary:

```
07-29 03:40:46.727  3935  6985 E Cryptfs : Unexpected value for crypto key location
07-29 03:40:46.727  3935  6985 E Cryptfs : Cannot open block device 
```

**Comment by chenxiaolong** [comment]
Unfortunately, DualBootPatcher no longer supports encrypted devices. It did at one point, but only AOSP ROMs for the Galaxy S4 were supported.

The way DualBootPatcher is designed does not allow for loading crypto keys from the hardware keystore. Implementing that correctly is very difficult. (Consider that even TWRP only supports AOSP-style encryption on some devices.) On top of that, with Samsung devices, volumes encrypted when booted with the stock kernel cannot be used with non-stock kernels and vice versa.

Unless the situation improves, you'll have to leave your device unencrypted.
