### ISSUE TITLE
Fatal signal

### ISSUE THREAD

**Issue by g3mb1x** [chenxiaolong/DualBootPatcher#672]
App crash when open roms tab
Device: Redmi Note 3 (kenzo)
Rom: Nitrogen OS
Root: Magisk 13.3

--------- beginning of crash
07-31 21:51:00.171  7427  7546 F libc    : Invalid address 0x7712616040 passed to free: value not allocated
07-31 21:51:00.172  7427  7546 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 7546 (pool-3-thread-1)
07-31 21:51:07.576  7567  7605 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x77136002f8 in tid 7605 (pool-1-thread-1)
--------- beginning of main
07-31 22:03:40.206 12188 12188 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
07-31 22:03:40.280 12188 12188 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
07-31 22:03:40.410 12188 12209 I Adreno  : QUALCOMM build                   : bc01238, I8e5c908169
07-31 22:03:40.410 12188 12209 I Adreno  : Build Date                       : 12/06/16
07-31 22:03:40.410 12188 12209 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.03
07-31 22:03:40.410 12188 12209 I Adreno  : Local Branch                     : 
07-31 22:03:40.410 12188 12209 I Adreno  : Remote Branch                    : quic/LA.BR.1.3.6_rb1.10
07-31 22:03:40.410 12188 12209 I Adreno  : Remote Branch                    : NONE
07-31 22:03:40.410 12188 12209 I Adreno  : Reconstruct Branch               : NOTHING
07-31 22:03:40.416 12188 12209 I OpenGLRenderer: Initialized EGL, version 1.4
07-31 22:03:40.416 12188 12209 D OpenGLRenderer: Swap behavior 1
07-31 22:20:49.218 14750 14750 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
07-31 22:20:49.286 14750 14750 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
07-31 22:20:49.407 14750 14771 I Adreno  : QUALCOMM build                   : bc01238, I8e5c908169
07-31 22:20:49.407 14750 14771 I Adreno  : Build Date                       : 12/06/16
07-31 22:20:49.407 14750 14771 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.03
07-31 22:20:49.407 14750 14771 I Adreno  : Local Branch                     : 
07-31 22:20:49.407 14750 14771 I Adreno  : Remote Branch                    : quic/LA.BR.1.3.6_rb1.10
07-31 22:20:49.407 14750 14771 I Adreno  : Remote Branch                    : NONE
07-31 22:20:49.407 14750 14771 I Adreno  : Reconstruct Branch               : NOTHING
07-31 22:20:49.416 14750 14771 I OpenGLRenderer: Initialized EGL, version 1.4
07-31 22:20:49.417 14750 14771 D OpenGLRenderer: Swap behavior 1
07-31 22:20:51.922 14750 14750 D SwitcherService: onCreate()
07-31 22:20:51.932 14750 14750 D SwitcherService: onBind(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherService })
07-31 22:20:51.934 14750 14750 D SwitcherService: onStartCommand(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherService }, flags=0, startId=1)
07-31 22:20:52.039 14750 14750 D SwitcherService: Added runnable com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask@4465e01 to thread pool: default
07-31 22:20:52.092 14750 14776 E RomConfig: Failed to load /storage/emulated/0/MultiBoot/primary/config.json
07-31 22:20:52.092 14750 14776 E RomConfig: java.io.FileNotFoundException: /storage/emulated/0/MultiBoot/primary/config.json (No such file or directory)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at java.io.FileInputStream.open(Native Method)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at java.io.FileInputStream.<init>(FileInputStream.java:99)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at java.io.FileReader.<init>(FileReader.java:58)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.RomConfig.loadFile(RomConfig.java:221)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.RomConfig.getConfig(RomConfig.java:79)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.RomUtils.loadConfig(RomUtils.java:300)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.RomUtils.getRoms(RomUtils.java:275)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask.execute(GetRomsStateTask.java:71)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.switcher.service.BaseServiceTask.run(BaseServiceTask.java:125)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.ThreadPoolService$1.run(ThreadPoolService.java:181)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-31 22:20:52.092 14750 14776 E RomConfig: 	at java.lang.Thread.run(Thread.java:761)
07-31 22:20:52.097 14750 14776 D RomUtils: mbtool says current ROM ID is: primary
07-31 22:20:53.792 14750 14776 D GetRomsStateTask: Getting active ROM ID
07-31 22:20:53.804 14750 14776 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7711400ac8 in tid 14776 (pool-1-thread-1)
07-31 22:20:55.307 14785 14785 D SwitcherService: onCreate()
07-31 22:20:55.318 14785 14785 D SwitcherService: onStartCommand(intent=null, flags=0, startId=2)
07-31 22:20:55.968 14785 14785 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
07-31 22:20:56.042 14785 14785 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
07-31 22:20:56.202 14785 14807 I Adreno  : QUALCOMM build                   : bc01238, I8e5c908169
07-31 22:20:56.202 14785 14807 I Adreno  : Build Date                       : 12/06/16
07-31 22:20:56.202 14785 14807 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.03
07-31 22:20:56.202 14785 14807 I Adreno  : Local Branch                     : 
07-31 22:20:56.202 14785 14807 I Adreno  : Remote Branch                    : quic/LA.BR.1.3.6_rb1.10
07-31 22:20:56.202 14785 14807 I Adreno  : Remote Branch                    : NONE
07-31 22:20:56.202 14785 14807 I Adreno  : Reconstruct Branch               : NOTHING
07-31 22:20:56.215 14785 14807 I OpenGLRenderer: Initialized EGL, version 1.4
07-31 22:20:56.215 14785 14807 D OpenGLRenderer: Swap behavior 1
07-31 22:26:54.086 14785 14785 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
07-31 22:26:57.471 14785 14790 I art     : Do partial code cache collection, code=27KB, data=29KB
07-31 22:26:57.472 14785 14790 I art     : After code cache collection, code=20KB, data=26KB
07-31 22:26:57.472 14785 14790 I art     : Increasing code cache capacity to 128KB
07-31 22:27:03.164 14785 14785 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
07-31 22:27:03.345 14785 14785 D SwitcherService: onBind(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherService })
07-31 22:27:03.346 14785 14785 D SwitcherService: onStartCommand(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherService }, flags=0, startId=3)
07-31 22:27:03.387 14785 14790 I art     : Do partial code cache collection, code=54KB, data=58KB
07-31 22:27:03.387 14785 14790 I art     : After code cache collection, code=54KB, data=58KB
07-31 22:27:03.387 14785 14790 I art     : Increasing code cache capacity to 256KB
07-31 22:27:03.392 14785 14785 D SwitcherService: Added runnable com.github.chenxiaolong.dualbootpatcher.switcher.service.BootUIActionTask@1e234ce to thread pool: default
--------- beginning of main
07-31 22:27:03.629 14785 15739 D SwitcherService: Attempting to stop service
07-31 22:27:03.629 14785 15739 D SwitcherService: Not stopping: # of operations: 0, is bound: true
07-31 22:27:12.795 14785 14807 D OpenGLRenderer: endAllActiveAnimators on 0x7713782400 (ListView) with handle 0x771160f840
07-31 22:27:13.164 14785 14785 D SwitcherService: onUnbind(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherService })
07-31 22:27:13.164 14785 14785 D SwitcherService: Attempting to stop service
07-31 22:27:13.164 14785 14785 D SwitcherService: Calling stopSelf(): there are no more operations
07-31 22:27:13.193 14785 14785 D SwitcherService: onDestroy()
07-31 22:27:26.422 14785 14785 D SwitcherService: onCreate()
07-31 22:27:26.428 14785 14785 D SwitcherService: onBind(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherService })
07-31 22:27:26.431 14785 14785 D SwitcherService: onStartCommand(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherService }, flags=0, startId=1)
07-31 22:27:26.454 14785 14785 D SwitcherService: Added runnable com.github.chenxiaolong.dualbootpatcher.switcher.service.BootUIActionTask@61ab3bc to thread pool: default

**Comment by chenxiaolong** [comment]
Fixed by #738.
