### ISSUE TITLE
[HELP[ Not able to build DualBootPatcher

### ISSUE THREAD

**Issue by zeeshanhussain** [chenxiaolong/DualBootPatcher#7]
Hi, i would love to see this in my Moto E (condor), i have added /dev/block/mmcblk0p* paths for condor in patcherconfig.cpp. debug build builds fine without any error , but when i try to update ramdisk it says unable to update ramdisk here is the ramdisk log output http://pastebin.com/VHsLTvEn though the app is able to patch roms for condor but i cant see any rom in roms tab. I tried building release builds too but it always gave me this error http://pastebin.com/r6avDsrv  a help will be appreciated.

**Comment by zeeshanhussain** [comment]
@chenxiaolong i am sure it is related to mbtoo. I tried to edit it to include the hexadecimal-representation of the certficate for the key used to sign the Android app . but it still gives that error . here is my android.certs.mk

# Allow debug certificate?
# WARNING: Dangerous!
ALLOW_DEBUG_CERT := true
ALLOW_RELEASE_CERT := true
ALLOW_CI_CERT := true

# Specify the certificate here (see validcerts.cpp for more info)
DEBUG_CERT :="6b6579746f6f6c206572726f723a206a6176612e6c616e672e457863657074696f6e3a204b657973746f72652066696c6520646f6573206e6f742065786973743a20594f55525f4b455953544f52455f46494c450a"

RELEASE_CERT :="6b6579746f6f6c206572726f723a206a6176612e6c616e672e457863657074696f6e3a204b657973746f72652066696c6520646f6573206e6f742065786973743a20594f55525f4b455953544f52455f46494c450a"

CI_CERT := "6b6579746f6f6c206572726f723a206a6176612e6c616e672e457863657074696f6e3a204b657973746f72652066696c6520646f6573206e6f742065786973743a20594f55525f4b455953544f52455f46494c450a"

Hope this can help to get the fix

**Comment by chenxiaolong** [comment]
@zeeshanhussain Your string appears to be ~10 times too short. To get the hex-representation of the debug certificate, you'll want to run:

```sh
keytool -alias androiddebugkey -keystore ~/.android/debug.keystore -exportcert | hexdump -ve '1/1 "%.2x"'; echo
```

(the default password the Android SDK uses is "android").

I should really integrate this into the build system. This is an annoying an uncessary step.

**Comment by zeeshanhussain** [comment]
@chenxiaolong  this is my hex-representation of the debug certificate  http://pastebin.com/7aQ3UQ2k


the debug build fines and it check packages signs too here is the output http://pastebin.com/nchaVVfq , thanks for helping but i am still unable to build release build here is the output of release build http://pastebin.com/bH99x0eL . I can do a pull request for my device :package:  so that you can build for us from your server :dancers:  


p.s - yes the daemon logs signature check failures

**Comment by zeeshanhussain** [comment]
@chenxiaolong  my build works fine now :dancer:
