### ISSUE TITLE
Any version of dual boot patcher app not working in Lenovo P2 (kuntao)

### ISSUE THREAD

**Issue by redking12** [chenxiaolong/DualBootPatcher#700]
I have tried the official app but as soon as i select the ROM s options it asked for some permission. And I gave the permission and then again tapped on ROMs option by swiping right and then the app crashed again. I have uploaded logcat to https://mega.nz/#!s2hCmDBQ!MUZFGOcNmFSQ-H4yOXbm_qEQh_rU0t77eNh-I82TpO0

**Comment by yshalsager** [comment]
try this, it's working 
https://transfer.sh/o9sgd/Android_GUI-debug.apk

**Comment by 911N-X** [comment]
@yshalsager Yes it's working but still changes not merged in latest build. Can you open pull request with the changes you made?

**Comment by redking12** [comment]
Yes that's working.

**Comment by chenxiaolong** [comment]
Fixed by #738.
