### ISSUE TITLE
Force closes (ramdisk update, patching zip files)

### ISSUE THREAD

**Issue by MisiekDP** [chenxiaolong/DualBootPatcher#726]
Hello Chen,
I got some FC in the newest version of DPB. You can see it on my uploaded gifs. Maybe these errors are similar to [**_this_**](https://github.com/chenxiaolong/DualBootPatcher/issues/683) but I am using the newest version 9.2.0.r339.ge167fe8f. I attach logs form recovery (GetLogs-20161128-1.zip), logcat and gifs. 

[20170823.083941.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/1244706/20170823.083941.tar.gz)

[logcat DBP.txt](https://github.com/chenxiaolong/DualBootPatcher/files/1244705/logcat.DBP.txt)

![patching-zip1](https://user-images.githubusercontent.com/22171619/29606327-356f202c-87ee-11e7-883b-fd23edc31811.gif)
![patching-zip2](https://user-images.githubusercontent.com/22171619/29606328-3584259e-87ee-11e7-90f2-7b941013bf66.gif)

**Comment by chenxiaolong** [comment]
Thanks! I'm looking into the issue now.

**Comment by chenxiaolong** [comment]
@MisiekDP Can you make it crash again and then upload `/sdcard/MultiBoot/logs/crash.log` and also the `/data/tombstones` folder? Thanks!

**Comment by MisiekDP** [comment]
@chenxiaolong I don't have a crash.log file.
![screenshot_20170823-142729](https://user-images.githubusercontent.com/22171619/29616001-2dff9aa2-8810-11e7-9c84-0cf3271f5d1f.png)

[tombstones.zip](https://github.com/chenxiaolong/DualBootPatcher/files/1245366/tombstones.zip)

**Comment by chenxiaolong** [comment]
Thanks, it looks like the tombstones file doesn't contain enough information.

Can you try the debug build here and then upload `/data/tombstones` again? https://dbp.noobdev.io/DualBootPatcherAndroid-9.2.0.r339.ge167fe8f.CRASH_DEBUG.apk

I will take a look at it after work.

**Comment by MisiekDP** [comment]
:) 
[tombstones.zip](https://github.com/chenxiaolong/DualBootPatcher/files/1245589/tombstones.zip)

**Comment by chenxiaolong** [comment]
Fixed by #738.
