### ISSUE TITLE
FC in MIUI

### ISSUE THREAD

**Issue by silentchild** [chenxiaolong/DualBootPatcher#730]
this app not work in MIUI system

**Comment by vortex1911** [comment]
+1
Even I'm facing the same problem. Device is redmi 3s prime (land).

**Comment by hzy2003** [comment]
OK,it also FC on mi 5
The system is re latest
And there's no voice from the video and music,but have some voice from system

**Comment by chenxiaolong** [comment]
Fixed by #738.
