### ISSUE TITLE
Both snapshot version and debug version crash on Xiaomi 5S plus(natrium)

### ISSUE THREAD

**Issue by XuanStar** [chenxiaolong/DualBootPatcher#733]
**Both snapshot version and debug version crash on my device.**

![1](https://user-images.githubusercontent.com/22031498/29676723-65d065c6-892b-11e7-89dd-ae327a4d9dc3.gif)
I don‘t have any logs except these.

![screenshot_20170825-005512](https://user-images.githubusercontent.com/22031498/29678416-12ea8188-8931-11e7-8fd6-93ca5be9ee16.png)

[logs.zip](https://github.com/chenxiaolong/DualBootPatcher/files/1249655/logs.zip)

**Comment by chenxiaolong** [comment]
Fixed by #738.
