### ISSUE TITLE
Great utility but no support for my device geehrc ( LG G e975 Intl-eu)

### ISSUE THREAD

**Issue by marxenegls** [chenxiaolong/DualBootPatcher#734]
I did manage to get it installed via sideload but when it came to patch the zip file it told me it couldn't because the device was not compatible .
I have modified twrp-multirom and multirom port for geehrc by MrMex i believe.
 
bootloader :  macoz10f 
hardware: geehrc 
arch : armv7l 

I'd appreciate any suggestions as to how i could port it 
thanks

**Comment by yshalsager** [comment]
Here's detailed guide by me
https://forum.xda-developers.com/android/software-hacking/guide-dualbootpatcher-build-source-t3663076
