### ISSUE TITLE
Broken support for Note 4 Exynos

### ISSUE THREAD

**Issue by alessandrodilo** [chenxiaolong/DualBootPatcher#740]
The last working snapshot for the Exynos variant of Samsung Note 4 is r202 , released on jun 24th , after that the app and the utilities do not recognize the phone as supported anymore, so it fails to set the kernel and update the ramdisk, it also crashes when trying to create a patched zip.

**Comment by chenxiaolong** [comment]
Please try `9.2.0.r347.g5525c524` or newer. This should be fixed.

**Comment by alessandrodilo** [comment]
Thank you!
