### ISSUE TITLE
[Request] Add support for Sony Xperia Z1 (honami)

### ISSUE THREAD

**Issue by zhuoyang** [chenxiaolong/DualBootPatcher#8]
Please add support for Xperia Z1

userdata -> /dev/block/mmcblk0p25
system -> /dev/block/mmcblk0p23
boot -> /dev/block/mmcblk0p14
cache -> /dev/block/mmcblk0p24

**Comment by zeeshanhussain** [comment]
@zhuoyang  path of recovery is needed too :dart:

**Comment by zhuoyang** [comment]
@zeeshanhussain sony devices doesn't have recovery partition

**Comment by Caio99BR** [comment]
From twrp.me: "The Xperia devices have a recovery-in-boot arrangement."

**Comment by chenxiaolong** [comment]
The patcher can handle the modification of Sony's ELF-based boot images, but it doesn't really handle the recovery-in-boot system yet. With the way DualBootPatcher wraps /init right now, you would probably have no way of booting into recovery after flashing a second ROM. In addition, the in-app flashing feature will probably never work without a dedicated recovery partition.

**Comment by zhuoyang** [comment]
it works , I pointed recovery to FOTAKernel parition

**Comment by chenxiaolong** [comment]
This device will be supported soon. See #174.
