### ISSUE TITLE
Add support for variant A6020l36 (Vibe K5 plus)

### ISSUE THREAD

**Issue by DarkGhoul** [chenxiaolong/DualBootPatcher#802]
Hello, while this tool supports the variant A6020l36 (Vibe K5 plus) lt isn't listed as a supported variant. Can we get this variant added to the list of supported codenames?

**Comment by yshalsager** [comment]
@DarkGhoul Flash https://dbp.noobdev.io/misc/getlogs/GetLogs-20161128-1.zip from twrp
The zip will save many logs from /sdcard/MultiBoot and device information from /dev, /proc, and /sys to /sdcard/logs/[Date&Time].tar. Please attach this tar archive and i'll add your device

**Comment by DarkGhoul** [comment]
@yshalsager Here's the log.
[19700223.064357.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/1350224/19700223.064357.tar.gz)

**Comment by yshalsager** [comment]
@DarkGhoul it must work with current K5 config, so edit your build.prop
ro.product.name=A6020
ro.product.device=A6020

**Comment by DarkGhoul** [comment]
@yshalsager I edited build.prop but it still showing "Could not determine the boot partition because this device's Codename 'A6020l36' is not recognized"

**Comment by yshalsager** [comment]
@DarkGhoul edit "A6020l36" to "A6020"

**Comment by DarkGhoul** [comment]
@yshalsager Yeh, I edited it but it only works on Stock ROM

**Comment by DarkGhoul** [comment]
@yshalsager  Works fine on Lenovo Stock firmware but on Custom Roms is not recognized even putting "A6020" on build.prop. So can you add my variant ? Sorry for my english

**Comment by DarkGhoul** [comment]
Fixed by 4a2349c75a0351f0aad2959e1b0c87fe1a01b690
