### ISSUE TITLE
Add support for Prestigio PSP5551DUO

### ISSUE THREAD

**Issue by miras10** [chenxiaolong/DualBootPatcher#807]
Please add support for Prestigio PSP5551DUO.

**Comment by miras10** [comment]
https://yadi.sk/d/NvBD9Wvz3NT9t8

**Comment by yshalsager** [comment]
@miras10 Here you are
https://transfer.sh/M45wC/Android_GUI-debug.apk

**Comment by miras10** [comment]
The application does not work correctly

**Comment by miras10** [comment]
You can fix it

**Comment by miras10** [comment]
The application does not work

**Comment by miras10** [comment]
Please rebuild the application

**Comment by miras10** [comment]
Use these logs https://yadi.sk/d/6y_CC5mi3NXK6z

**Comment by miras10** [comment]
Dual boot patcher 9.3.0 does not work
