### ISSUE TITLE
Error when building the APK

### ISSUE THREAD

**Issue by arvedviehweger** [chenxiaolong/DualBootPatcher#81]
Hi,

I get the following error when building the apk from sources on Ubuntu 14.04 LTS using openjdk:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Android_GUI'.
> Could not resolve all dependencies for configuration ':_ciCompile'.
   > Could not resolve com.github.afollestad.material-dialogs:core:0.8.5.6.
     Required by:
         :Android_GUI:unspecified
      > Could not resolve com.github.afollestad.material-dialogs:core:0.8.5.6.
         > Could not get resource 'https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.6/core-0.8.5.6.pom'.
            > Could not GET 'https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.6/core-0.8.5.6.pom'.
               > peer not authenticated
   > Could not resolve com.github.afollestad.material-dialogs:commons:0.8.5.6.
     Required by:
         :Android_GUI:unspecified
      > Could not resolve com.github.afollestad.material-dialogs:commons:0.8.5.6.
         > Could not get resource 'https://jitpack.io/com/github/afollestad/material-dialogs/commons/0.8.5.6/commons-0.8.5.6.pom'.
            > Could not GET 'https://jitpack.io/com/github/afollestad/material-dialogs/commons/0.8.5.6/commons-0.8.5.6.pom'.
               > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.637 secs

Anyone knows a fix for that?

**Comment by chenxiaolong** [comment]
Do you have OpenJDK 7 or 8 installed? I ran into that a couple weeks ago on my second build server and updating to OpenJDK 8 fixed the issue, though I'm not sure why.

**Comment by zeeshanhussain** [comment]
@haimann951  install android support library and android support repository.
