### ISSUE TITLE
Failed to flash magisk 14.0

### ISSUE THREAD

**Issue by SkiFire13** [chenxiaolong/DualBootPatcher#844]
I can't flash magisk 14.0 (nor previous versions) in a data slot.
Didn't tried in primary slot.

MultiBoot.log: https://pastebin.com/35LD7mWP
Device: Xiaomi Mi 5

**Comment by marnix409** [comment]
I'm having the same issue on my galaxy s8+
Failed to flash magisk and also xposed. Also, after patching the zips, they decrease in size significantly (i.e from 20mb to 2.5mb)

Tried flashing through dualboot patcher and also through twrp.

**Comment by SkiFire13** [comment]
Up. Do devs have something to say? Any workaround?

**Comment by kalawy** [comment]
Try to flash magisk 12 patched for the secondery rom 
And when it boots install magisk apk and in module part choose the + sign and  browse to magisk 15.3 .. Let it do its magic .. Don' reboot .. Open dual boot patcher and it will detect and prompt you to set the modified kernel .. Let it be set then you can reboot 


This solution worked on mi max 2 

** credits go to a guy who put this in xda in mi max 2 forum on xda 
** i don't know if the magisk 12 he put in the topic was modified .. So if the original magisk 2 doesnt work .. You can use his version ... It's in the guides section of mi max 2 forum in xda
