### ISSUE TITLE
[Request] Would you mind add "hlteskt" and "hltektt" to patcherconfig.cpp ? 

### ISSUE THREAD

**Issue by dinhbao88** [chenxiaolong/DualBootPatcher#85]
I have read the thread [http://forum.xda-developers.com/galaxy-s5/general/dual-boot-t2841957/post60078398#post60078398](http://forum.xda-developers.com/galaxy-s5/general/dual-boot-t2841957/post60078398#post60078398) and found that the issue "device's codename is not recognized" can be fix with adding codename to patcherconfig.cpp. Would you mind add two codename "hlteskt" and "hltektt" (Samsung SM-N900K) to hlte codenames ? Thank you.

**Comment by dinhbao88** [comment]
*it should be /libmbp/devices/samsung.cpp if I wasn't wrong.

**Comment by chenxiaolong** [comment]
Closing since the codenames were added recently.
