### ISSUE TITLE
Add support to Samsung T959

### ISSUE THREAD

**Issue by baolong24** [chenxiaolong/DualBootPatcher#864]
build.prop

# begin build properties
# autogenerated by buildinfo.sh
ro.build.id=LRX22G
ro.build.display.id=RR_vibrantmtd-rodman01 5.0.2 LRX22G
ro.build.version.incremental=52dbc07b11
ro.build.version.sdk=21
ro.build.version.codename=REL
ro.build.version.all_codenames=REL
ro.build.version.release=5.0.2
ro.build.date=So  3 Mai 2015 14:57:33 CEST
ro.build.date.utc=1430657853
ro.build.type=userdebug
ro.build.user=rodman01
ro.build.host=rodmans-pc.local
ro.build.tags=test-keys
ro.product.brand=samsung
ro.product.name=SGH-T959
ro.product.device=vibrantmtd
ro.product.board=aries
# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,
# use ro.product.cpu.abilist instead.
ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product.cpu.abilist=armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=
ro.product.manufacturer=samsung
ro.product.locale.language=en
ro.product.locale.region=US
ro.wifi.channels=
ro.board.platform=s5pc110
# ro.build.product is obsolete; use ro.product.device
ro.build.product=SGH-T959
ro.product.model=SGH-T959
ro.product.device=SGH-T959
# Do not try to parse description, fingerprint, or thumbprint
ro.build.description=SGH-T959-user 2.2 FROYO UVKB5 release-keys
ro.build.fingerprint=Samsung/SGH-T959/SGH-T959/SGH-T959:2.2/FROYO/UVKB5:user/release-keys
ro.build.characteristics=default
ro.cm.device=vibrantmtd
# end build properties
#
# from device/samsung/vibrantmtd/system.prop
#
#
# system.prop for vibrantmtd
#

rild.libpath=/system/lib/libsec-ril.so
rild.libargs=-d /dev/ttyS0
ro.sf.lcd_density=240

#
# ADDITIONAL_BUILD_PROPERTIES
#
ro.rommanager.developerid=cyanogenmod
ro.com.google.clientidbase=android-google
keyguard.no_require_sim=true
ro.url.legal=http://www.google.com/intl/%s/mobile/android/basic/phone-legal.html
ro.url.legal.android_privacy=http://www.google.com/intl/%s/mobile/android/basic/privacy.html
ro.com.android.wifi-watchlist=GoogleGuest
ro.setupwizard.enterprise_mode=1
ro.com.android.dateformat=MM-dd-yyyy
ro.com.android.dataroaming=false
ro.build.selinux=1
persist.sys.dun.override=0
persist.sys.root_access=1
ro.rr.version=vibrantmtd
ro.rr_modversion=Resurrection_Remix_LP_v5.3.9
ro.resurrection.version=Resurrection_Remix_LP_5.0-20150503
ro.cmlegal.url=https://cyngn.com/legal/privacy-policy
persist.sys.recovery_update=false
ro.cm.display.version=Resurrection_Remix_LP_v5.3.9-20150503-T959
ro.config.notification_sound=Argon.ogg
ro.config.alarm_alert=Helium.ogg
ro.config.ringtone=C.Y.E-Resurrection.mp3
ro.carrier=unknown
ro.opengles.version=131072
debug.hwui.render_dirty_regions=false
ro.zygote.disable_gl_preload=true
wifi.interface=wlan0
ro.telephony.ril_class=SamsungExynos3RIL
ro.telephony.ril.config=icccardstatus,datacall,signalstrength,facilitylock
mobiledata.interfaces=pdp0,eth0,gprs,ppp0
ro.bq.gpu_to_cpu_unsupported=1
ro.ril.hsxpa=1
ro.ril.gprsclass=10
ro.adb.qemud=1
ro.ril.enable.managed.roaming=1
ro.ril.emc.mode=2
ro.phone_storage=1
ro.additionalmounts=/storage/sdcard1
ro.config.low_ram=false
ro.sys.fw.bg_apps_limit=16
ro.config.max_starting_bg=10
ro.ksm.default=1
dalvik.vm.dex2oat-Xms=8m
dalvik.vm.dex2oat-Xmx=96m
dalvik.vm.image-dex2oat-Xms=48m
dalvik.vm.image-dex2oat-Xmx=48m
dalvik.vm.dex2oat-filter=interpret-only
dalvik.vm.image-dex2oat-filter=speed
camera2.portability.force_api=1
camera2.port.operation_time_ms=5000
ro.hwui.disable_scissor_opt=true
ro.com.google.locationfeatures=1
ro.com.google.networklocation=1
dalvik.vm.dexopt-data-only=1
ro.kernel.android.checkjni=0
dalvik.vm.checkjni=false
dalvik.vm.heapstartsize=5m
dalvik.vm.heapgrowthlimit=48m
dalvik.vm.heapsize=128m
dalvik.vm.heaptargetutilization=0.75
dalvik.vm.heapminfree=512k
dalvik.vm.heapmaxfree=2m
persist.sys.dalvik.vm.lib.2=libart.so
dalvik.vm.isa.arm.features=default
dalvik.vm.lockprof.threshold=500
dalvik.vm.dexopt-flags=m=y
net.bt.name=Android
dalvik.vm.stack-trace-file=/data/anr/traces.txt

**Comment by yshalsager** [comment]
If you have twrp, Flash logs https://dbp.noobdev.io/misc/getlogs/GetLogs-20161128-1.zip
attach tar file and let me add it.
@baolong24
