### ISSUE TITLE
Fingerprint password always lose

### ISSUE THREAD

**Issue by exodius48** [chenxiaolong/DualBootPatcher#889]
I always lose fingerprint password everytime i change from primary rom to secondary rom or vice versa.

Here my setup:
Device: Redmi Note 4X (codename: mido)
Primary rom: crDroid Official v3.8.2 (Android 7.1.2)
Secondary rom: MIUI 9 v9.0.4.0 (Android 7.0)
Recovery: Red-Wolf 021 based on TWRP 3.1.1

**Comment by chenxiaolong** [comment]
Unfortunately, I don't think this is possible to fix. Most devices (especially Samsung) will save the fingerprints in hardware and the bootloader will wipe those fingerprints if it detects that the kernel image was changed/modified.
