### ISSUE TITLE
Delete ROMs

### ISSUE THREAD

**Issue by rickysarraf** [chenxiaolong/DualBootPatcher#924]
The user interface does not have a clean easy of deleting the ROMs.

It would be nice to have a clean interface for the same

**Comment by rickysarraf** [comment]
Please see screenshot.

How to delete these ROMs ?

s3nt fr0m a $martph0ne, excuse typ0s

**Comment by chenxiaolong** [comment]
To delete a ROM, first boot into another ROM. Then open DualBootPatcher, click the 3 dots next to the ROM you want to delete, tap Wipe ROM and the bottom, and check all of the boxes.

(PS. I don't see the screenshot you mentioned)
