### ISSUE TITLE
Force Close on self made Build

### ISSUE THREAD

**Issue by schwabe93** [chenxiaolong/DualBootPatcher#930]
Hello,

i added today a Samsung Tablet, i changed everything for my tab like partitions etc.
i complied the app in Docker succsesfull but when i start the app and select anything it force closes the app.
 here you can see my commit: https://github.com/schwabe93/DualBootPatcher/commit/052c525c2b6c18d84a5ad2dcd7339e7c18dd519a
And here the Crash: [crash.log](https://github.com/chenxiaolong/DualBootPatcher/files/1594524/crash.log)

**Comment by chenxiaolong** [comment]
Looks like the data archive is missing:
```
12-30 14:45:12.756 24059 24104 E AndroidRuntime: Caused by: java.io.FileNotFoundException: data-9.3.0.tar.xz
12-30 14:45:12.756 24059 24104 E AndroidRuntime: 	at android.content.res.AssetManager.openAsset(Native Method)
12-30 14:45:12.756 24059 24104 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:423)
12-30 14:45:12.756 24059 24104 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:397)
12-30 14:45:12.756 24059 24104 E AndroidRuntime: 	at com.github.chenxiaolong.dualbootpatcher.FileUtils.extractAsset(FileUtils.java:252)
12-30 14:45:12.756 24059 24104 E AndroidRuntime: 	at com.github.chenxiaolong.dualbootpatcher.patcher.PatcherUtils.extractPatcher(PatcherUtils.java:166)
12-30 14:45:12.756 24059 24104 E AndroidRuntime: 	... 7 more
```
Did you run `cpack` after `make`?

**Comment by schwabe93** [comment]
HI,

ohh man i forget to run cpack , shame on me.
Now its working :) i created a Pull Request https://github.com/chenxiaolong/DualBootPatcher/pull/934

Thanks for your Help :)

**Comment by chenxiaolong** [comment]
No problem! Glad you got it working.
