### ISSUE TITLE
Lose SIM card recognition from both main and secondary ROM

### ISSUE THREAD

**Issue by lisandrocarmona** [chenxiaolong/DualBootPatcher#94]
I'm using DualBoot on Asus Zenfone 2 and after flashing the secondary ROM to a data slot, when booting, everything goes fine except the SIM card is not recognized. When booting the main ROM again it is not recognized too. I have to restore a nandroid.

I've tested with both non sharing app and then sharing apps.

A user tried to explain the "solution", but I could not follow the directions.
http://forum.xda-developers.com/showpost.php?p=66877539&postcount=131

I can only imagine the Ramdisk is involved as it occurs in both ROMs.

**Comment by lisandrocarmona** [comment]
Tested again with clean flashing the secondary ROM at data slot. I lost SIM card recognition in both ROMs. I'm using latest patcher v.268.

**Comment by Caio99BR** [comment]
1 year expiration, could be closed.
