### ISSUE TITLE
Support for OPPO A53 , thanks very much.

### ISSUE THREAD

**Issue by 0toN** [chenxiaolong/DualBootPatcher#946]
It's the Flash logs 
[19720210.110220.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/1602582/19720210.110220.tar.gz)

**Comment by yshalsager** [comment]
Please test this https://transfer.sh/GTmg8/Android_GUI-debug-060118-15h39m.apk
@0toN

**Comment by 0toN** [comment]
Well, i tested it which is run normally,hope add to release version soon,thanks.
@yshalsager

**Comment by yshalsager** [comment]
@0toN Here is release version
https://dbp.noobdev.io/files/9.3.0.r313.g673bb21d/Android/DualBootPatcherAndroid-9.3.0.r313.g673bb21d-snapshot.apk

**Comment by 0toN** [comment]
Good job!
