### ISSUE TITLE
Samsung Galaxy J7 (2016)

### ISSUE THREAD

**Issue by tolikes1** [chenxiaolong/DualBootPatcher#948]
https://transfer.sh/FW0R9/20180101.172050.tar.gz
All saved wait the update thanks very much

**Comment by tolikes1** [comment]
I have android 7.0 stock rooted magisk

**Comment by yshalsager** [comment]
@tolikes1 Please test this https://transfer.sh/GTmg8/Android_GUI-debug-060118-15h39m.apk

**Comment by tolikes1** [comment]
i start testing thanks

**Comment by tolikes1** [comment]
Stuck in boot i restore my j7 2016
