### ISSUE TITLE
Lack of space on system image in external sdcard

### ISSUE THREAD

**Issue by lisandrocarmona** [chenxiaolong/DualBootPatcher#95]
While trying to flash modified ROM (Resurrection Remix) and Gapps (pico version OpenGapps) to a slot on external sdcard, I've got insufficient free space error. I remember that, in older versions of DualBootPatcher, we can resize/increase the partitions images. Now I cannot find such command and the system image is lacking of free space to flash even the pico version of Gapps. Device: Asus Zenfone 2 (Z00A).

**Comment by theman480** [comment]
Create a blank image, of the size you want to expand the original (in my example I use 5GB);

dd if=/dev/zero of=/path/to/temp_image bs=1 count=1 seek=5G

Append this to the original image:

cat /path/to/temp_image >> /path/to/customrom.img

Resize the filesystem that lives at the end of the disk (usually this is the one you want bigger):

resize2fs -f /path/to/rasperrypi.img

**Comment by lisandrocarmona** [comment]
Thanks. I'll try later, but I'm not sure it will help with my major issue described here: https://github.com/chenxiaolong/DualBootPatcher/issues/94, i.e., if I don't correct the major issue it won't even worth to test installing in the sdcard as I'm lost the SIM card recognition.

**Comment by Caio99BR** [comment]
1 year expiration, could be closed. No logs uploaded.
