### ISSUE TITLE
support for samsung galaxy core 2

### ISSUE THREAD

**Issue by tim241** [chenxiaolong/DualBootPatcher#97]
here you have the log files from the getlog flashable zip: https://goo.gl/4749ci
I hope you guys can port it,
Thanks for your help,
Tim

**Comment by ttimz1313** [comment]
You need to set up an account on.. Git Hub. Any never answer the question
is your device rooted.. that's why it's not working your device isn't rooted

**Comment by tim241** [comment]
I am rooted but my question was: can the owner port this to my device with the getlog files?

**Comment by ttimz1313** [comment]
The owner has to put the phone at the. git hub. You have to have access to
the phone to do it right

**Comment by tim241** [comment]
i know but i asked if the owner could add support for my device
