### ISSUE TITLE
Error in "make" while building apk

### ISSUE THREAD

**Issue by sunnykatiyar50** [chenxiaolong/DualBootPatcher#975]
I tried to build apk but unable to solve this issue... 

root@sunny:~/Downloads/DualBootPatcher/build# make
[  1%] Performing configure step for 'hosttools'
-- Implicit C compiler include paths:
--   /usr/include
--   /usr/lib/gcc/x86_64-linux-gnu/7/include
--   /usr/local/include
--   /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
--   /usr/include/x86_64-linux-gnu
--   /usr/include
-- Implicit C++ compiler include paths:
--   /usr/include
--   /usr/include/c++/7
--   /usr/include/x86_64-linux-gnu/c++/7
--   /usr/include/c++/7/backward
--   /usr/lib/gcc/x86_64-linux-gnu/7/include
--   /usr/local/include
--   /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
--   /usr/include/x86_64-linux-gnu
--   /usr/include
-- Configuring done
CMake Error in libmbcommon/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "mbcommon-shared".

CMake Error in libmbcommon/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "mbcommon-static".

CMake Error in libmbbootimg/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "mbbootimg-shared".

CMake Error in libmbbootimg/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "mbbootimg-static".

CMake Error in libmbdevice/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "mbdevice-shared".

CMake Error in libmbdevice/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "mbdevice-static".

CMake Error in libmbdevice/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "schemas2cpp".

CMake Error in libmblog/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "mblog-shared".

CMake Error in libmblog/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "mblog-static".

CMake Error in libmbsign/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "mbsign-shared".

CMake Error in libmbsign/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "mbsign-static".

CMake Error in libmbsparse/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "mbsparse-static".

CMake Error in misc/CMakeLists.txt:
  Specified unknown feature "c_std_11" for target "file-contexts-tool".

CMake Error in signtool/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "signtool".

CMake Error in devicesgen/CMakeLists.txt:
  Specified unknown feature "cxx_std_17" for target "devicesgen".

-- Generating done
-- Build files have been written to: /root/Downloads/DualBootPatcher/build/hosttools/hosttools-prefix/src/hosttools-build
hosttools/CMakeFiles/hosttools.dir/build.make:105: recipe for target 'hosttools/hosttools-prefix/src/hosttools-stamp/hosttools-configure' failed
make[2]: *** [hosttools/hosttools-prefix/src/hosttools-stamp/hosttools-configure] Error 1
CMakeFiles/Makefile2:257: recipe for target 'hosttools/CMakeFiles/hosttools.dir/all' failed
make[1]: *** [hosttools/CMakeFiles/hosttools.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chenxiaolong** [comment]
Which version of cmake do you have? You need 3.7 or later.

**Comment by sunnykatiyar50** [comment]
I am using 3.7.2

**Comment by chenxiaolong** [comment]
Ah okay. I remembered incorrect. It looks like `cxx_std_17` was added in CMake 3.8: 
https://cmake.org/cmake/help/v3.8/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html
