### ISSUE TITLE
issue when compiling apk!!

### ISSUE THREAD

**Issue by tim241** [chenxiaolong/DualBootPatcher#98]
hi,
I tried to compile the apk from your github source. I followed your steps and installed and downloaded everything. I keep getting an error: 
`There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating goal targets....
 File 'Android_GUI/CMakeFiles/apk.dir/build' does not exist.
   File 'apk' does not exist.
     File 'Android_GUI/CMakeFiles/apk' does not exist.
    Must remake target 'Android_GUI/CMakeFiles/apk'.
Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to "55c32853b5a3868d3219a9a4e86a91161f9a794f"

FAILURE: Build failed with an exception.

* Where:
Build file '/home/tim/DualBootPatcher/Android_GUI/build.gradle' line: 10

* What went wrong:
A problem occurred evaluating root project 'Android_GUI'.
> Failed to apply plugin [id 'com.android.application']
   > Could not create plugin of type 'AppPlugin'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.464 secs
Android_GUI/CMakeFiles/apk.dir/build.make:57: recipe for target 'Android_GUI/CMakeFiles/apk' failed
make[3]: *** [Android_GUI/CMakeFiles/apk] Error 1
CMakeFiles/Makefile2:681: recipe for target 'Android_GUI/CMakeFiles/apk.dir/all' failed
make[2]: *** [Android_GUI/CMakeFiles/apk.dir/all] Error 2
CMakeFiles/Makefile2:688: recipe for target 'Android_GUI/CMakeFiles/apk.dir/rule' failed
make[1]: *** [Android_GUI/CMakeFiles/apk.dir/rule] Error 2
Makefile:325: recipe for target 'apk' failed
make: *** [apk] Error 2
tim@tim-HP-Compaq-dc7900-Small-Form-Factor:~/DualBootPatcher$ 
`
I can't seem to fix this issue. Please help me.
Regards,
Tim

**Comment by zeeshanhussain** [comment]
export ANDROID_DAILY_OVERRIDE =55c32853b5a3868d3219a9a4e86a91161f9a794f 

or update sdk :+1:

**Comment by tim241** [comment]
That fixed that error. Now I have an other Error:
`:emulatorview:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':emulatorview:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/tim/Android/Sdk/build-tools/23.0.3/aapt'' finished with non-zero exit value 127

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 58.231 secs
Android_GUI/CMakeFiles/apk.dir/build.make:57: recipe for target 'Android_GUI/CMakeFiles/apk' failed
make[3]: *** [Android_GUI/CMakeFiles/apk] Error 1
CMakeFiles/Makefile2:681: recipe for target 'Android_GUI/CMakeFiles/apk.dir/all' failed
make[2]: *** [Android_GUI/CMakeFiles/apk.dir/all] Error 2
CMakeFiles/Makefile2:688: recipe for target 'Android_GUI/CMakeFiles/apk.dir/rule' failed
make[1]: *** [Android_GUI/CMakeFiles/apk.dir/rule] Error 2
Makefile:325: recipe for target 'apk' failed
make: *** [apk] Error 2
tim@tim-HP-Compaq-dc7900-Small-Form-Factor:~/DualBootPatcher$ 
`

**Comment by ttimz1313** [comment]
Don't compel at gapps .. used open source made for the phone whoever wrote
your system
