### ISSUE TITLE
Add Support For Moto E4 Perry

### ISSUE THREAD

**Issue by electricboy207** [chenxiaolong/DualBootPatcher#985]
Hi, I really want to use this on my Moto E4, but the only support for this device is for the woods model A.K.A. Mediatek. Please add support for the Qualcomm (Perry) E4!

**Comment by electricboy207** [comment]
Here's the log 
[20180128.221017.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/1672157/20180128.221017.tar.gz)

**Comment by electricboy207** [comment]
Anybody able to help?

**Comment by xc920718** [comment]
https://github.com/xc920718/DualBootPatcher/commit/0a94df41683c4224ffe69150a442b70361609cf6
Wait for a while，please！
and close the issues

**Comment by electricboy207** [comment]
How long should it take for the device to be added to the main site?

**Comment by electricboy207** [comment]
Can you build a version I can test?
