### ISSUE TITLE
Phone Doesn't Boot After Updating Ramdisk

### ISSUE THREAD

**Issue by electricboy207** [chenxiaolong/DualBootPatcher#998]
I was using the latest build of the patcher app from Jenkins, and I went to update the ramdisk. After pressing restart, the phone shows the N/A screen, buzzes 5 times, then reboots into twrp. I'm on a Moto E4 XT1766, and also used the second to latest build which had the same problem. Here's the logs.

**Comment by electricboy207** [comment]
[20180203.175123.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/1692327/20180203.175123.tar.gz)

**Comment by electricboy207** [comment]
Tried the same on AEX, did the same exact thing.

**Comment by chenxiaolong** [comment]
Is your `/data` partition formatted with F2FS or EXT4?

It looks like it's failing to boot because the ROM only supports F2FS-formatted `/data`:

```
[    1.857678,1] [1970-02-06T21:18:28.680707000+00:00][1:1][debug] mbtool/mount_fstab: fstab: /dev/block/bootdevice/by-name/userdata       /data        f2fs    rw,discard,nosuid,nodev,noatime,nodiratime,nobarrier,inline_xattr,inline_data      wait,check,formattable,encryptable=/dev/block/bootdevice/by-name/metadata
[    1.857736,1] [1970-02-06T21:18:28.680769000+00:00][1:1][debug] mbtool/mount_fstab: -> /data entry
```

but it's failing to mount:

```
[    1.868320,2] F2FS-fs (mmcblk0p54): Magic Mismatch, valid(0xf2f52010) - read(0x59936abf)
[    1.868329,2] F2FS-fs (mmcblk0p54): Can't find valid F2FS filesystem in 1th superblock
[    1.868518,2] F2FS-fs (mmcblk0p54): Magic Mismatch, valid(0xf2f52010) - read(0x6c07f213)
[    1.868525,2] F2FS-fs (mmcblk0p54): Can't find valid F2FS filesystem in 2th superblock
[    1.868535,2] F2FS-fs (mmcblk0p54): Magic Mismatch, valid(0xf2f52010) - read(0x59936abf)
[    1.868541,2] F2FS-fs (mmcblk0p54): Can't find valid F2FS filesystem in 1th superblock
[    1.868549,2] F2FS-fs (mmcblk0p54): Magic Mismatch, valid(0xf2f52010) - read(0x6c07f213)
[    1.868555,2] F2FS-fs (mmcblk0p54): Can't find valid F2FS filesystem in 2th superblock
```

**Comment by electricboy207** [comment]
Sorry if this sounds stupid, but how do I check whether it's f2fs or ext4?

**Comment by chenxiaolong** [comment]
No problem at all. If you run the following command in a terminal app or in ADB, it will say either `ext4` or `f2fs`.

```sh
grep ' /data ' /proc/mounts
```

**Comment by electricboy207** [comment]
The output was multiple lines, but I only saw one f2fs and no ext4 mentioned.

**Comment by electricboy207** [comment]
![screenshot_20180205-222711](https://user-images.githubusercontent.com/33522919/35840357-c08531b2-0ac3-11e8-8595-a0c293b38902.png)

**Comment by chenxiaolong** [comment]
Thanks for the screenshot! So the issue was not what I expected. The `/dev/block/dm-0` is the cause of the issue. It means that your data partition is encrypted.

Unfortunately, there's no way for DualBootPatcher to support encrypted partitions, so you might need to check XDA to see if there's a way to decrypt your device.

**Comment by electricboy207** [comment]
Thank you! I'll check on there now.

**Comment by electricboy207** [comment]
Decrypted my data and it works great! Thank you for the awesome support!

**Comment by chenxiaolong** [comment]
Awesome! Glad you got it working!
